### ISSUE TITLE
how to get result with double Click Or button?

### ISSUE THREAD

**Issue by nekooee** [Norserium/vue-advanced-cropper#1]
Hi
how can I get result with double Click Or button on the image?

**Comment by Norserium** [comment]
Hello!

Currently, you are able to get the result only by subscribing to `change` event.
https://norserium.github.io/vue-advanced-cropper/tutorials/recipes.html#getting-result

It emits on every change of cropped area or image.

Do you need a special method to get the result (via ref, for example)? Why does it suit more to your goals than subscribing to event?

**Comment by nekooee** [comment]
1- my image bind with the input form. when getting the result from a change event and set direct in form, it is repeated in the loop. see below:

![error](https://user-images.githubusercontent.com/6003803/60804504-ef15ef00-a192-11e9-8a23-25f50d382a66.gif)

2- The user expects, after the area he chose, with the key or double-click it to confirm and close the component, or it is canceled.

I try to create a custom component and emit results, my self. I use your custom sample code but I get the error : Height undefine

**Comment by Norserium** [comment]
Look at the [demo](https://codesandbox.io/s/vue-template-nzpuk) please. Could you fix it to correspondent your problem?

**Comment by Norserium** [comment]
I've added `getResult` method in `0.8.3`. The example of using this method is [here](https://norserium.github.io/vue-advanced-cropper/tutorials/recipes.html#getting-result).

**Comment by nekooee** [comment]
very thank you.

**Comment by Norserium** [comment]
You are welcome! Did it solve your problem?

**Comment by nekooee** [comment]
Yes. my problem solved.  thanks
