### ISSUE TITLE
Zoom in/out 

### ISSUE THREAD

**Issue by bluelupin** [Norserium/vue-advanced-cropper#10]
Is there any way we can zoom in or out the image.

**Comment by Norserium** [comment]
Hello, @bluelupin!

This cropper implies that user resize and move stencil (that rectangle/circle) and one represents the cropped area.

Why do you need resize image?  Is there any example of what you want to get?

**Comment by matamune94** [comment]
i think he say like this https://fengyuanchen.github.io/cropperjs/examples/fixed-crop-box.html
this feature good for mobile

**Comment by Norserium** [comment]
@bluelupin, @matamune94 I will consider this feature request.

**Comment by Suruat** [comment]
+1 for feature

**Comment by Norserium** [comment]
@bluelupin, @matamune94, @Suruat, I'm glad to say you that this feature is in the active development stage.

You could event test it himself at the [documentation pages](https://norserium.github.io/vue-advanced-cropper/tutorials/recipes.html#fixed-stencil).

**Comment by Norserium** [comment]
This feature is added in `1.4.0`. Please update to this version to get it.

**Comment by tcdsantos** [comment]
Hello!

Firstable, i would like to congratulate the developers of this cool cropper. Despite of being in an early development stage, it is already a very handy vue component.

I am trying to create two buttons that will programmatically zoom in and zoom out the image.

The result i am looking for is the same as if i scroll the mouse up/down in the exact center of the circle stencil. Is there a native way of doing it?

I am trying to use the setCoordinates method but with no luck - i tried to manipulate the `width`, `height`, `left` and `top` properties but i can't figure out how to achieve the desired zoom in/out effect.

I would appreciate if someone could help me achieving this behaviour.

Thank you.

**Comment by Norserium** [comment]
@tcdsantos, thank you! 

Unfortunately there is no API to programmatically zoom cropper. So I will consider this comment as feature request.

**Comment by tcdsantos** [comment]
@Norserium, thank you!

**Comment by Norserium** [comment]
@tcdsantos, `zoom` method is finally added. Please update to `0.17.1` version.

**Comment by tcdsantos** [comment]
> @tcdsantos, `zoom` method is finally added. Please update to `0.17.1` version.

Thank you very much @Norserium!!
