### ISSUE TITLE
How can I make preview like this?

### ISSUE THREAD

**Issue by ANaumow** [Norserium/vue-advanced-cropper#100]
### How can I make avatar preview like this?

![example](https://user-images.githubusercontent.com/31388766/104770758-226f0c00-5782-11eb-9a65-27b5e6206a18.jpg)

I know that I can do this by `canvas.toDataURL()` but it is slow, is there a better way?

**Comment by Norserium** [comment]
@ANaumow, check [this example](https://codesandbox.io/s/vue-advanced-cropper-preview-native-dblzn?file=/src/App.vue). If the result is good for you, then update to `1.2.1` and use the new `Preview` component.

**Comment by Norserium** [comment]
There is [the corresponding section](https://norserium.github.io/vue-advanced-cropper/guides/recipes.html#preview-the-result) in the documentation now also.

**Comment by ANaumow** [comment]
Thanks, this is what I needed!
