### ISSUE TITLE
canvas.toDataURL() without rendering the component

### ISSUE THREAD

**Issue by CalebJTSmith** [Norserium/vue-advanced-cropper#102]
Is it possible to crop an image without rendering the cropping tool itself? Example - we are putting together a tool to allow for consumers to crop images and some products do not allow cropping, but we want to capture the blob data from saved coordinates to render back on the frontend.

I have tried using a v-show on the component and fetching the data through the $ref, but it returned empty. I could show the cropper and disable it.. but I am hoping for a more elegant solution.

**Comment by Norserium** [comment]
@CalebJTSmith, alas, I don't understand your use-case completely. Do you need to crop the image programmatically by known coordinates? Do you need do it only to preview the cropped area?

**Comment by CalebJTSmith** [comment]
Yes exactly! It's a little odd, but I have a "soft crop" of coordinates that I set when I initialize the cropper. In most cases, the end user will start cropping with that as the starting point. If consumer cropping is disabled, then I just want to grab the soft crop and continue.

The actual flow for this use case: Consumer picks a product -> Consumer picks an image for this product (with predefined cropped coordinates) -> We display the cropped blob data in a preview slot.

**Comment by Norserium** [comment]
Do you need to use blob data anywhere else? If not, you can use `Preview` component for this case. [Example](https://codesandbox.io/s/vue-advanced-cropper-preview-native-dblzn?file=/src/App.vue).

In your case I suppose it would be look as follows:
```html
<preview
     :width="widthOfPreview"
     :height="heightOfPreview"
     :image="{
        src: yourImageSrc
     }
    :coordinates="croppedCoordinates"
/>
```

**Comment by CalebJTSmith** [comment]
I had no idea this was available! Oh this is fantastic. This should take care of my issue.

**Comment by Norserium** [comment]
It was added 4 days ago, so it's not surprising. There is some words about it in the documentation also that may be helpful ([documentation](https://norserium.github.io/vue-advanced-cropper/components/preview.html), [example](https://norserium.github.io/vue-advanced-cropper/guides/recipes.html#preview-the-result))
