### ISSUE TITLE
On iOS, page reloads, when you try to crop photo

### ISSUE THREAD

**Issue by Zahod** [Norserium/vue-advanced-cropper#103]
Device: iPhone 11 Pro.
You can see this issue on recipes page, when you upload photo created by phone camera:
https://norserium.github.io/vue-advanced-cropper/guides/recipes.html#load-image-from-a-disc

I believe this is all because of large image size.

Before that I used old version 0.15.3, and it worked well in that point.

**Comment by Norserium** [comment]
@Zahod, alas, I don't have got iPhone 11 Pro. Could you record a screen video?

**Comment by Zahod** [comment]
@Norserium It might not only iPhone 11 Pro issue, I think any iOS device has this problem.
Video:
https://www.dropbox.com/s/gfp2qqi7w8b7bdd/RPReplay_Final1611223423.MP4?dl=0
In sandbox - same issue
https://www.dropbox.com/s/6c1njcvjhiwq4sc/RPReplay_Final1611224076.MP4?dl=0

P.S: On Android phones everything works well

**Comment by Norserium** [comment]
@Zahod I currently don't have any iOS device, so I need your assistance now. 

Could you test the following sandboxes: [1.21.1](https://codesandbox.io/s/vue-avanced-cropper-basic-jfy5w), [1.1.0](https://codesandbox.io/s/peaceful-northcutt-wjplp), [1.0.2](https://codesandbox.io/s/cocky-smoke-gjh9b), [0.20.1](https://codesandbox.io/s/morning-glade-mv7ot)?

The video is not needed now, just check if there is the problem.

**Comment by Norserium** [comment]
I found also the following [thread](https://apple.stackexchange.com/a/56165). This issue may be linked with memory insufficiency problem.

**Comment by Zahod** [comment]
@Norserium
 [1.21.1](https://codesandbox.io/s/vue-avanced-cropper-basic-jfy5w), [1.1.0](https://codesandbox.io/s/peaceful-northcutt-wjplp), [1.0.2](https://codesandbox.io/s/cocky-smoke-gjh9b) - has this issue
[0.20.1](https://codesandbox.io/s/morning-glade-mv7ot) - works well !

So, it might be a memory issue on device, but modern phones has a lot of memory. To reach the limit you will need to try hard. In this case it would be a performance issue

**Comment by Norserium** [comment]
> To reach the limit you will need to try hard. In this case it would be a performance issue

Yes, it would be. I just try to find some clues.

Could you test [1.0.0](https://codesandbox.io/s/eloquent-sky-vxi16) also?

**Comment by Zahod** [comment]
> Could you test 1.0.0 also?

Yep, It works too.

**Comment by Norserium** [comment]
It's interesting. Could you test [1.0.1](https://codesandbox.io/s/distracted-swartz-fer1c?file=/src/main.js) also?

**Comment by Zahod** [comment]
> It's interesting. Could you test 1.0.1 also?

Has that issue, page reloads.

**Comment by Norserium** [comment]
It's really bad, because it may be associated with transforms. Thanks for the investigation, I will check what can I do.

**Comment by Zahod** [comment]
Let me know if I can help!
I will stay on 0.15.3 version for now.

**Comment by Norserium** [comment]
Could you send me one of the photos that cause the issue? In the archive.

**Comment by Zahod** [comment]
[test_photos.zip](https://github.com/Norserium/vue-advanced-cropper/files/5850679/test_photos.zip)

**Comment by Norserium** [comment]
Could you test [this image](https://github.com/Norserium/vue-advanced-cropper/files/5850968/photo.zip)?

**Comment by Norserium** [comment]
If you encounter trouble with this image also, then please try to upload this image to [this sandbox](https://codesandbox.io/s/stupefied-paper-dgjr2?file=/src/App.vue).

**Comment by Norserium** [comment]
@Zahod, could you test [1.2.2](https://codesandbox.io/s/vue-avanced-cropper-basic-jfy5w?file=/src/main.js) with one of your previous images also?

**Comment by Zahod** [comment]
@Norserium, page reloads in both sandboxes. I tried to upload  your sent photo and my old - same result.

**Comment by Norserium** [comment]
@Zahod do you have any troubles with loading [this sandbox](https://codesandbox.io/s/heuristic-lehmann-xfogt?file=/src/App.vue)?

**Comment by Zahod** [comment]
Yep, same issue. Here [screen video](https://www.dropbox.com/s/gblaz7lm47j9tev/RPReplay_Final1611307861.MP4?dl=0)

**Comment by Norserium** [comment]
Could you load [this sandbox](https://codesandbox.io/s/adoring-frost-elbm2?file=/src/App.vue)?

**Comment by Zahod** [comment]
This sandbox working fine. Also with new uploaded photo.

**Comment by Norserium** [comment]
It's nice! Now I want to figure out what changes actually help. Could you test this sandboxes: [(1)](https://codesandbox.io/s/adoring-frost-elbm2?file=/src/App.vue), [(2)](https://codesandbox.io/s/bold-fog-bzuw0?file=/src/App.vue), [(3)](https://codesandbox.io/s/wispy-firefly-hq1xf?file=/src/App.vue), [(4)](https://codesandbox.io/s/lucid-rosalind-thzgw?file=/src/App.vue), [(5)](https://codesandbox.io/s/ecstatic-pike-0p1t3)?

**Comment by Zahod** [comment]
1, 3, 4, 5 - work
2 - reloads page

**Comment by Norserium** [comment]
Could you test [1.2.3](https://codesandbox.io/s/vue-avanced-cropper-basic-jfy5w?file=/src/App.vue)?

**Comment by Zahod** [comment]
> Could you test 1.2.3?

This one is working!

**Comment by Norserium** [comment]
Do you plan to use this version in your application? If so, it would be nice to receive feedback.

Anyway, thank you very much for your help. It was very helpful for all our community.

**Comment by Zahod** [comment]
> Do you plan to use this version in your application?

Yes, but not right now, I will try to update version in next releases, and let you know. I was glad to help.

Could you explain, if it possible, what was the case, and how you fixed that? It might be helpful in my future developments and 
will help to improve performance on mobile devices.

**Comment by Norserium** [comment]
I've removed `will-change: transform` for the image elements. This property is useful, but I made the mistake by using it here.

**Comment by Norserium** [comment]
If you have time, could you test [the rotation of your images](https://codesandbox.io/s/vue-advanced-cropper-rotate-2-k37kl?file=/src/App.vue) on iOS?

**Comment by Zahod** [comment]
Hey @Norserium thanks for your answer!
Just now I tested rotation on my phone in sandbox. 
When I try to rotate uploaded image - page reloads. Looks like the same issue

**Comment by Norserium** [comment]
@Zahod thanks. Alas, it looks not fixable. Could you test [1.0.0](https://codesandbox.io/s/vue-advanced-cropper-rotate-2-forked-gj1s7?file=/src/App.vue) also?

**Comment by Zahod** [comment]
This one is works!

**Comment by Norserium** [comment]
@Zahod I suppose that you will get the similar error when you try to resize image in 1.0.0. Am I right?

**Comment by Norserium** [comment]
@Zahod could you test also [1.2.5](https://codesandbox.io/s/vue-advanced-cropper-rotate-2-k37kl?file=/src/App.vue)?

**Comment by Norserium** [comment]
@Zahod, if you could find the time, it would be very helpful if you test the two cases above.

**Comment by Zahod** [comment]
Hey @Norserium !
Sorry, I was a little busy last week. I will try to answer as fast as I can.

> I suppose that you will get the similar error when you try to resize image in 1.0.0. Am I right?

This version is working in any cases: rotate, zoom, change cropper size. Looks stable.

> could you test also 1.2.5?

This version is also work. Only image [disappear](https://www.dropbox.com/s/97rjcz8x5qtc9yi/RPReplay_Final1612259466.MP4?dl=0) for a short time when I try to rotate first time. But, I think , it is fine.

**Comment by Norserium** [comment]
@Zahod, awesome! 

The disappearing of the image is a minor bug compared with the bugs described above. Anyway, I will investigate it later and I've add its mention to the bugs list.

Thank you for your help again.  I suppose issue maybe close now?

**Comment by Zahod** [comment]
> I suppose I may close the issue now?

Yep! 
On my project, I updated to v1.2.4. For my purposes it works well.

**Comment by Norserium** [comment]
@Zahod, I'm wondering why did you chose `1.2.4` rather than `1.2.5`? The last version fixes crash on an image rotate.

**Comment by Zahod** [comment]
@Norserium No troubles. 
At the moment when I push new release, 1.2.4 was the latest. I am not using image rotate on my project. I will switch to latest version, on my next release.

**Comment by Norserium** [comment]
@Zahod I got it. I close the issue then, if you encounter any troubles, feel free to open it.
