### ISSUE TITLE
Disable auto zoom when resizing stencil programatically

### ISSUE THREAD

**Issue by zalemmm** [Norserium/vue-advanced-cropper#104]
Hello and thanks for this great tool ! 
I'm using a static cropper that can be resized programatically. 
I don't want fixed ratio because it's the user that defines it choosing width and height. 
It works well except that when adjusting the width and height, there's an auto zoom and move of the picture that i found no way to deactivate.

Here is the cropper when page is loaded (stencil fits the width and height of the picture):
![Screenshot_2021-01-21 iddeco - France banderole(2)](https://user-images.githubusercontent.com/8736892/105343835-6e86da00-5be2-11eb-960d-42086aab916d.png)

e.g. now when moving the height or width cursors:
![Screenshot_2021-01-21 iddeco - France banderole(3)](https://user-images.githubusercontent.com/8736892/105343912-85c5c780-5be2-11eb-977a-a28520d3bac3.png)

e.g. of what i want : no zoom and picture staying at top left position: 
![Screenshot_2021-01-21 iddeco - France banderole(4)](https://user-images.githubusercontent.com/8736892/105343991-a42bc300-5be2-11eb-85c6-17f68674f2f3.png)

Thanks for your help !

**Comment by Norserium** [comment]
@zalemmm could you provide codesandbox or the cropper source code at least?

**Comment by zalemmm** [comment]
https://codesandbox.io/s/sn1fb?file=/src/App.vue

**Comment by Norserium** [comment]
Why do you set the stencil size explicitly?

**Comment by zalemmm** [comment]
i set the size explicitly because the user can quickly save the picture for a standard default ratio corresponding at 200*300 cm relative to pic's size. Otherwise, he can choose his height and width, and while changing ratio the stencil is supposed to stick to picture borders, left/right or top/bottom depending on picture size that can be different and rectangle stencil's orientation... I thought auto zoom was my issue but there's may be other ways to get this behavior...

**Comment by Norserium** [comment]
@zalemmm I suppose there is little misunderstanding. 

The prop `stencil-size` sets the physical size of the stencil, not the actual cropped area. It should be obvious if you look at the following screenshot:
![Explanation](https://user-images.githubusercontent.com/9862719/105469358-25e62400-5ca9-11eb-8d91-8016e33e35dd.png)

**Comment by Norserium** [comment]
Also, I don't understand exactly what you want to get. For example, what does centimetres means? There is no centimetres in the browser, only pixels.

**Comment by zalemmm** [comment]
ok sorry i took shortcuts with fixed dimensions in the sandbox but it's more like this in the app i'm working on: 
https://codesandbox.io/s/festive-ramanujan-vtrmq?file=/src/App.vue
I get pictures from an api, various sizes and orientations. from theses pics we print real wallpapers according to user chosen dimensions in centimeters. 
The user chose his wall size and he can preview in the cropper what part of the picture can be included and move the pic into it, then crop the image.

**Comment by Norserium** [comment]
@zalemmm I'm not sure that I understand you correctly, but there is [probable solution](https://codesandbox.io/s/vue-advanced-cropper-dynamic-aspect-ratio-goyu6?file=/src/App.vue).

**Comment by zalemmm** [comment]
exactly !!! sorry if i was not very clear but you understood correctly, thanks a lot !

**Comment by Norserium** [comment]
@zalemmm, you are welcome!

**Comment by Norserium** [comment]
@zalemmm try also this variation with [custom auto zoom](https://codesandbox.io/s/vue-advanced-cropper-dynamic-aspect-ratio-autozoom-nnpvr?file=/src/App.vue). It should guarantee the centering of the stencil.

**Comment by Lejla94** [comment]
Hello friends.
I want to achieve the same thing. 
When the aspect ration changes the stencil should be max width or height. By changing width and height.
But i do not want the autozoom to move the picture left and right when the stencil moves.
I saw the codesandbox and left only the autozoom. When i change dimensions it is fine, but i do not want the cropper to move the image.
So the image should be fixed, and only the stencil to choose.

Thanks in advance

**Comment by Norserium** [comment]
@Lejla94, sorry but it's not clear what you want to get. Could you show example of such behavior or draw something?

**Comment by Lejla94** [comment]
Goal: When i change the aspectRatio the stencil should fit the width or height on the whole picture. Then the user can move the stencil to become smaller or choose another part.
Currently: When someone changes aspectRatio or widht and height, the stencil makes it smaller until it reaches the minimum height or width.
Problem: On the codesandbox you provided, i can do this with the autozoom prop. But the picture moves when the stencil moves, so the picture should be fixed.
Sorry but the repo you provided by removing the other props that makes it fixed (could not resize stencil), leaving the autozoom, but the picture is zooming to the left or right then.

**Comment by Norserium** [comment]
@Lejla94, well, let's try to clear it by examples. Is [this example](https://codesandbox.io/s/vue-advanced-cropper-new-autozoom-p4y1h?file=/src/App.vue) more close to your desired result?

**Comment by Lejla94** [comment]
The Problem is that when the stencil changes size then it zooms.
I want it full size. when i dynamically change the aspect ratio, then the stencil should fit the image, but with the needed aspect ratio.
Sorry for not being clearer.

**Comment by Lejla94** [comment]
it should fit the image when the aspect ratio changes. When the stencil resizes the image should not move.

**Comment by Lejla94** [comment]
The Stencil take the whole width or height when aspect ratio changes: like this picture
![Screenshot from 2021-08-18 13-18-44](https://user-images.githubusercontent.com/39634562/129889394-21ef54c1-4e77-4831-ab0b-3d49d6ae9e8f.png)

Or could be resized without changing the zoom or picture:
![Screenshot from 2021-08-18 13-19-08](https://user-images.githubusercontent.com/39634562/129889451-04d9ed69-03fc-49d4-84ba-9a9dfdc550f6.png)

**Comment by Norserium** [comment]
@Lejla94, I still don't understand, what do you mean by "aspect ratio changes". Is it static and changed by the external field? Otherwise, it can be changed on every slight resize.

**Comment by Lejla94** [comment]
the aspect ratio changes based on the numbers given.
E.x. The part of the width or height that dynamically sets aspect ratio.
But when this happens the stencil expands to the full image based on that.

**Comment by Norserium** [comment]
@Lejla94, check [this example](https://codesandbox.io/s/vue-advanced-cropper-aspect-ratio-dtx0m?file=/src/App.vue). I'm not sure, that it's the desired result, because it looks too simple.

**Comment by Lejla94** [comment]
At least it is better then before, i am gonna use this and see what else can i do.
Thanks a lot. I gave a star to the project.

**Comment by Norserium** [comment]
@Lejla94, let's end with it. What's wrong now? The screenshots would be very helpful.

**Comment by Lejla94** [comment]
A question. :default-size="fullImage" is the start size or what?

It just does not work well at me, i am going to debug and see what my error is.
![image](https://user-images.githubusercontent.com/39634562/129900268-b6ce5250-ff64-4e08-9288-c3b61a3cc400.png)

It seems working the same as if the default size is or is not there.

**Comment by Norserium** [comment]
@Lejla94, yes it's. Do you have limitations for maximum width and maximum height?

**Comment by Lejla94** [comment]
I should not spend you more time. I am gonna implement this, but if it is the case i will create a github repo for example.
The inputs can not take more then referenced.
Thanks

**Comment by Norserium** [comment]
@Lejla94, if you want provide the cropper definition in the template:
```html
<cropper
   ...
/>
```

I assume it will be sufficiently to find the reason of such behavior. Also, check that you use the latest version of the cropper.

**Comment by Lejla94** [comment]
```
    <cropper
      class="cropper"
      boundingBoxClass="main-photo"
      :src="require(`../../assets/shower-back-wall/${imgCategory}/${mainImg}`)"
      :default-size="defaultSize"
      minWidth="20"
      minHeight="20"
      :stencil-component="$options.components.Stencil"
      :stencil-props="{
        gridLeft: gridLeft,
        gridLeftSecond: gridLeftSecond,
        aspectRatio: aspectRatio,
      }"
      @change="change"
    ></cropper>

```

**Comment by Norserium** [comment]
@Lejla94, well, it's not enough. I was wrong. Check the default size function calculation result (by debugger or `console.log`).

**Comment by Lejla94** [comment]
i forgot to mention i am using vue 3.
You do not need to worry, it is my issue.
i used this:

```
const defaultSize = computed(() =>  {
      let aspectRatio = Number(neededWidth.value/neededHeight.value) || 1;
      if (aspectRatio > imagePlacement.width / imagePlacement.height) {
        return {
          width: imagePlacement.width,
          height: imagePlacement.width / aspectRatio,
        };
      } else {
        return {
          width: imagePlacement.height * aspectRatio,
          height: imagePlacement.height,
        };
      }
    })
```

**Comment by Norserium** [comment]
@Lejla94, I assume it's. 

I don't know what `imagePlacement` is, but if it's the image size, I recommend you define the `defaultSize` as a method, like in my example.

**Comment by Lejla94** [comment]
my repo:
https://github.com/KLala94/cropper-issue

**Comment by Norserium** [comment]
@Lejla94, my advice is still actual:
```js
const defaultSize = ({ imageSize }) =>  {
  let aspectRatio = Number(neededWidth.value/neededHeight.value) || 1;
  if (aspectRatio > imageSize.width / imageSize.height) {
    return {
      width: imageSize.width,
      height: imageSize.width / aspectRatio,
    };
  } else {
    return {
      width: imageSize.height * aspectRatio,
      height: imageSize.height,
    };
  }
}
```

Theoretically, it might help.

**Comment by Lejla94** [comment]
Thanks. It is working now after refactoring and other stuff.
The problem was to my complicated code writing. After making it simpler it was easy to see the problem.
You can refer to the repository for reference [myrepo](https://github.com/KLala94/cropper-issue).
That's it

**Comment by Norserium** [comment]
@Lejla94, you are welcome!
