### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by ionicsolutions** [Norserium/vue-advanced-cropper#105]
I modified the RectangularStencil for one of my projects and stumbled across the fact that there is no `LICENSE` file in the repository which shows the proper attribution (i.e., which name and date range to use).

Hence, I'd like to ask if [this license notice](https://github.com/XAI-Demonstrator/xai-demonstrator/blob/master/visual-inspection/inspection-frontend/src/components/ExplanationStencil.vue) is appropriate/correct and suggest that you add a `LICENSE` file that others can copy from.

Thanks for the great component, looking forward to using 1.0!

**Comment by Norserium** [comment]
@ionicsolutions I've added the license file. In short:
> The source code is licensed under MIT. The documentation and the used photos / images are copyrighted to their respective owners.

> Thanks for the great component, looking forward to using 1.0!

You already can use this version. It's published on [NPM](https://www.npmjs.com/package/vue-advanced-cropper/v/1.2.4).

**Comment by ionicsolutions** [comment]
Thanks! I'll make sure to update both the license notice and the code as soon as possible.

**Comment by Norserium** [comment]
@ionicsolutions you are welcome! If you encounter any issues with migration to the new version (that is not described in [the guide](https://norserium.github.io/vue-advanced-cropper/introduction/migration.html)), feel free to create the issue. It would be helpful for other users.
