### ISSUE TITLE
Crop images without vue component

### ISSUE THREAD

**Issue by m0jimo** [Norserium/vue-advanced-cropper#108]
I'm happy i've found `vue-advanced-cropper` which is easy to implement and has a nice UI.

Is there a way how to crop images outside a vue component?

I'm developing Chrome extension which should  take screenshots of active tab in intervals (in the `background.js` process ) and compare cropped parts of snapshots based on saved dimension (or already cropped image) from the vue component cropper.

**Comment by Norserium** [comment]
Hello, @m0jimo! 

I assume that you are already using the canvas to compare images, hence you can easily crop image by using the canvas. That's how the cropper crops the image internally ([source](https://github.com/Norserium/vue-advanced-cropper/blob/master/src/core/canvas.ts)).

**Comment by m0jimo** [comment]
It was too late when I posted my issue and was not thinking much. Thanks for the answer with link and thanks for a great component.

**Comment by Norserium** [comment]
@m0jimo, you are welcome!
