### ISSUE TITLE
Get stencil coordinates after change & auto-zoom

### ISSUE THREAD

**Issue by Dylan190774** [Norserium/vue-advanced-cropper#109]
I have a Cropper with `auto-zoom` set to `true`.
I wish to get the absolute coordinates of the stencil, after something has changed.

To do this I do something like this in the `v-on:change` event:

        let stencil = document.querySelector(".vue-rectangle-stencil");
        let stencil_rect = stencil.getBoundingClientRect();

With that I 'm able do what I want (overlay the stencil with some stuff).
This works fine while dragging the handles, but after I release a handle, because of the `auto-zoom`, the stencil is moved to the center and resized. But it doesn't trigger a change-event anymore after that, so I'm not able to update my overlay with the new coordinates.

Any way to trigger some event after the auto-zoom has finished ?

**Comment by Norserium** [comment]
Hello, @Dylan190774! 

I'm wondering why do you need to get absolute coordinates of the stencil? 

To answer your question, there is no such feature now. To be clear, I should note, that auto-zoom changes the coordinates immediately and the smooth animation of resizing is the result of using transitions. By the way, I have some plans about adding `transition-end` and `transition-start` events that would be helpful in this case with some limitations. But I'm not sure that they will be implemented soon.

Anyway, there are workarounds to solve your problem (they're workarounds, so use them carefully). For example, you can calculate the relative coordinates of the stencil yourself:
```
const cropper = this.$refs.cropper;
if (cropper) {
    const cropperCoordinates = cropper.$el.getBoundingClientRect();
    const stencilCoordinates = cropper.stencilCoordinates;
    const left = cropperCoordinates.left + stencilCoordinates.left;
    const top = cropperCoordinates.top + stencilCoordinates.top;
}
```

[The sandbox.](https://codesandbox.io/s/vue-advanced-cropper-stencil-coordinates-workaround-hqb46?file=/src/App.vue)

**Comment by Dylan190774** [comment]
I understand that this can be used to calculate the coordinates, but the problem was when to do this. 
Somehow it needs to be triggered when the transition has ended. A `transition-end` event would be great :)

A `slot `in the cropper (or stencil) component would als be nice, so I could use this to put the overlay in, but I understand that's even more complicated :)

**Comment by Norserium** [comment]
Could you explain why do you need to get the coordinates? Why do you need to put overlay in? There is the overlay right now.

**Comment by Dylan190774** [comment]
I'm making some kind of graphics editor that can turn a picture into a mosaic. 
It would be nice to display the calculated mosaic directly onto the editor, without switching to another page/tab.

See this page for examples of what I'm trying to do: http://close-pixelate.desandro.com/

**Comment by Dylan190774** [comment]
I added the following to achieve what I want:

```
     let that = this;
     const cropper = document.querySelector('.cropper');
      cropper.addEventListener('transitionend', () => {
         that.cropper_update();
     });

```

In the `cropper_update `method I redraw the overlay.
This works when I use the handles to resize the stencil, but somehow it doesn't work right when I move the stencil, because it doesn't catch the latest position. 
Also the transitionend event is fired multiple times, which of course slows down the process.

**Comment by Norserium** [comment]
> I'm making some kind of graphics editor that can turn a picture into a mosaic.
It would be nice to display the calculated mosaic directly onto the editor, without switching to another page/tab.

I don't get the idea completely. Do you need to pixelate the whole image? Could you provide any screenshot of the current result?

**Comment by Dylan190774** [comment]
I'm still in the beginning stages, so not much to see yet, but I'll keep you posted :)

By the way, the following solution seems to work a lot better than my previous one:

```
 ,  mounted () {
      let that = this;

      that.$watch(
          () => {
              return that.$refs.cropper.transitionsActive;
          },
        (val) => {
          that.cropper_update();
        }
      )
    }
```

**Comment by Norserium** [comment]
> I'm still in the beginning stages, so not much to see yet, but I'll keep you posted :)

You could illustrate your idea in a some picture editor. Select by color the areas that should be pixelated and it will answer on my previous question.

**Comment by Dylan190774** [comment]
![image](https://user-images.githubusercontent.com/16488685/109291231-00f54b80-7829-11eb-8fa9-501044355acd.png)

Here's the idea of the editor. The overlay is now simply red ;) , but would be the mosaic when it's finished.

**Comment by Norserium** [comment]
Now I get it. Thanks.

**Comment by Norserium** [comment]
@Dylan190774, I suppose [it's](https://codesandbox.io/s/vue-advanced-cropper-pixelate-hqb46?file=/src/PixelatedPreview.vue) what you want to get. Yes?

**Comment by Dylan190774** [comment]
Wow, that's absolutely fantastic. Great work!
This is exactly the idea that I have in mind.

**Comment by Norserium** [comment]
You are welcome! And keep in mind two things:
1. It's a still fast made sketch. It may have different disadvantages and limitations. For example, it doesn't support the image rotate / scale (but it's fixable).
2. I didn't use the `close-pixelate` library normally. I cat the needed code and transform it to functions, it's much flexible and suitable. I suppose it's pretty normal approach, considering the library is 9 years old. It won't be changed.

**Comment by Dylan190774** [comment]
I wrote my own version of this library already, so that's ok.

The only thing that bothers me a little bit, is that quite a lot of duplicated code in the new Stencil component is needed to make it work., for example the onMove, onMoveEnd methodes, etc. When you'd change the default Stencil, these changes would have to be made in the custom Stencil too.

So it'd still be great if an event was sent to the Cropper-component when the transition is done. My `watch `works, but it's still a little bit fiddly, I think. I'm no expert in Vue communication between components though.

**Comment by Norserium** [comment]
I suppose that the current solution is the most idiomatic solution for this library. Why? Because the pixelated preview is actually the part of the stencil. 

You shouldn't worry about the future changes of default stencil if you don't plan to create the universal stencil for the community. It's the core feature of this library: creating of your own stencils. Just create the stencil that you need. I will try to assure that breaking changes will appear only in the next major releases.

**Comment by Dylan190774** [comment]
Thank you for your effort.
The pixelation-logic depends on a lot of different variables (multiple layers, palette, shapes, masks, all kinds of settings, etc.). All this is defined and configured in the main vue-file. What do you think is the best option to pass all this to the stencil?
Somehow I still think it's better that the pixelation is done in the vue file that in the cropper/stencil, but I could be wrong :)

**Comment by Norserium** [comment]
You can pass any props by using `stencil-props` prop in the cropper.

**Comment by Norserium** [comment]
I close the issue. Feel free to reopen if necessary.
