### ISSUE TITLE
Coordinates do not clear properly when using Firefox

### ISSUE THREAD

**Issue by Willdta** [Norserium/vue-advanced-cropper#11]
When uploading an image the first time, it works as expected. When uploading another image consecutively after, the coordinates do not clear properly. Left and top coordinates become NaN and height and width stay the same.

On Chrome, coordinates clear properly each time.

**Comment by Norserium** [comment]
Hello! 

I've just tested this scenario and it is processed correctly.

Could you test uploading images at [this example](https://norserium.github.io/vue-advanced-cropper/tutorials/recipes.html#custom-restrictions)?

What's the uploading images? What's the version of Firefox do you use?

**Comment by Willdta** [comment]
The version of Firefox I'm using is 69.0.1. The images are just regular PNG's, JPG's, JPEG's. I used the exact method you linked in the first place.

After further investigation, it seems like it clears at first but once my image is actually saved to the db, the coordinates mess up.

**Comment by Norserium** [comment]
Let's define. Does this problem occur in my examples or this problem is specific to your code only? In the second case me need additional details about your code or an example at the [codesandbox](https://codesandbox.io/).

**Comment by Willdta** [comment]
> Let's define. Does this problem occur in my examples or this problem is specific to your code only? In the second case me need additional details about your code or an example at the [codesandbox](https://codesandbox.io/).

Do you want anything specific in terms of my code?

**Comment by Norserium** [comment]
First of all, I want to know, could you reproduce this problem at the documentation examples.

Secondly, if it's not possible, me need details about your specific case. Maybe, code that uses this library or something else.

**Comment by Willdta** [comment]
1. No, I could not.

2. When uploading the image I'm using the code you listed in the documentation. When clearing the input, I'm setting my image to null and my coordinates back to 0. Maybe I'm not correctly resetting my state? Here's what I'm using to reset it:

`this.coordinates = { left: 0, height: 0, top: 0, width: 0}`
`this.uploadedPhoto = ""`
`this.croppedPhoto = null`

I have also noticed these errors but I don't know if it's of any help:

<img width="942" alt="Screen Shot 2019-09-27 at 1 20 43 PM" src="https://user-images.githubusercontent.com/34286283/65788796-e39aea00-e129-11e9-9b72-b5ec32c663b6.png">

**Comment by Norserium** [comment]
Could you provide more code? What is `this` here? What's props do you send to cropper?

**Comment by Willdta** [comment]
> Could you provide more code? What is `this` here? What's props do you send to cropper?

`this` is in reference to my local component data.

Cropper component:

```
<cropper
  :src="uploadedPhoto"
  class="cropper"
  @change="cropImage"
/>
```

cropImage method (using TypeScript):

```
cropImage({ coordinates, canvas }: {
    coordinates: { width: number, height: number, left: number, top: number },
    canvas: HTMLCanvasElement
  }) {
    this.coordinates = coordinates;
    canvas.toBlob(blobData => {
      this.croppedPhoto = blobData;
    })
  }
```

**Comment by Norserium** [comment]
And what's happening with `uploadedPhoto`?

**Comment by Willdta** [comment]
> And what's happening with `uploadedPhoto`?

Exactly what is in your docs when uploading a photo.

**Comment by Norserium** [comment]
Am I right, that you have the copy of example code and it doesn't work? It's pretty strange.

**Comment by Norserium** [comment]
Try to update to `0.12.4`. I suppose, that the cause of this issue is incorrect handling of setting empty `src` prop value.

**Comment by Willdta** [comment]
> Try to update to `0.12.4`. I suppose, that the cause of this issue is incorrect handling of setting empty `src` prop value, and I've fixed this bug in the new version.

This fixed it!

There are some type errors I thought you should know about though:

<img width="782" alt="Screen Shot 2019-09-27 at 6 51 55 PM" src="https://user-images.githubusercontent.com/34286283/65806524-e7ddfc00-e157-11e9-8ba0-ad79fd664f98.png">

**Comment by Norserium** [comment]
It's the serious error. Thanks.

When was this thrown?

**Comment by Willdta** [comment]
> Canvas is `undefined` if `src` prop is empty. Maybe it's not obviously, but sending an empty canvas value is not the best solution too.
> 
> There is temporary fix:
> 
> ```js
> cropImage({ coordinates, canvas }: {
>     coordinates: { width: number, height: number, left: number, top: number },
>     canvas: HTMLCanvasElement
>   }) {
>     this.coordinates = coordinates;
>     if (canvas) {
>       canvas.toBlob(blobData => {
>         this.croppedPhoto = blobData;
>       })
>    } else {
>       this.croppedPhoto = null;
>    }
> }
> ```

Awesome man. Thanks so much for helping me out. I really appreciate it!

**Comment by Norserium** [comment]
You are welcome!
