### ISSUE TITLE
Canvas max size

### ISSUE THREAD

**Issue by Nemesis19** [Norserium/vue-advanced-cropper#111]
Dear Developer,

I'm using the lib mostly on mobile and Safari is a must use browser for the situation.

With specific photos over about 4000x4000 pixels, coming i.e. from a professional camera (like canon etc), I receive from safari the errors like this "Canvas area exceeds the maximum limit (width * height > 16777216)."

If I resize the canvas after the `const { canvas } = this.$refs.cropper.getResult();` the image gets corrupted and I can't upload it normally like in any other situation.

Is there a config setting of the cropper to fix a max canvas size? Even though I don't know if this can solve the problem...

here my code:
```
const { canvas } = this.$refs.cropper.getResult();
	const img = new Image();
	img.src = canvas.toDataURL('image/jpeg', 0.9);

	img.onload = async () => {
		const height = canvas.height > 1200 ? 1200 : canvas.height;
		const width = canvas.width > 1200 ? 1200 : canvas.width;
		const elem = document.createElement('canvas');
		elem.width = width;
		elem.height = height;
		const context = elem.getContext('2d');
		context.drawImage(img, 0, 0, width, height);

		this.blob = await new Promise(resolve => context.canvas.toBlob(resolve, 'image/jpeg', 0.85));
	};
```
I'm creating the blob at a previous step before sending it to the server via a post API, this is to reduce the loading time of publishing a post with large images.

Thanks as always

**Comment by Norserium** [comment]
Hello, @Nemesis19! 

Nice to meet you again. 

On the one hand the described problem affects I suppose many real users (however, it's hard to reproduce this problem on desktop devices). On the other hand I'm not sure that there is the universal solution that will suit for all cases.

Perhaps, the optimal solution is the documenting of approaches to solve your problem. The first approach that comes to my mind is [preliminary image resizing](https://codesandbox.io/s/vue-advanced-cropper-reduce-uploaded-image-size-h7n9i?file=/src/App.vue). It should be tested careful, because I'm not sure that it will work in IE-11, for example.

But it looks nice. The [pica](https://github.com/nodeca/pica) library is used under the hood and it splits the large image on tiles that give it possibility to resize enormous images.

**Comment by Nemesis19** [comment]
Thanks for your reply, I understand your point and I also saw the references you sent me.

But the problem here seems to be about giving to the cropper canvas a preliminary constraint. I'll try to explain better.

If from my code above I just leave the `const { canvas } = this.$refs.cropper.getResult();` removing all the rest, Safari keeps prompting with the warning of excess of canvas limit.
I put a console log after `const { canvas } = this.$refs.cropper.getResult();` and I see that the canvas gets it's width and height after the file upload (I pick the file from the input file).

What I'm asking you is if "there is a way to add to the canvas that Cropper creates a max width & height" in order to  to fit in there whatever image I want even 10000x10000 pixel as example.

I don't know if this will solve the issue but can be worth a try? Instead what you pointed out seems to me an "after" approach and it's something that I already do because I don't send to the sever images bigger than 1200x1200.

The downside here is that the issue is just with stupid Safari and iOS 😅 and that warning is instead a blocking thing because when that warning fires, what happens actually is that the canvas gets corrupted and the blob I create (in my code above) is empty as it's empty the multipart/form I send to the api.

Please let me know if I can be clearer in my explainations.

**Comment by Norserium** [comment]
> Instead what you pointed out seems to me an "after" approach and it's something that I already do because I don't send to the sever images bigger than 1200x1200.

No, I suggested "before" approach, i.e. resize image before passing it to the cropper.

Anyway, I've published 1.3.1 now version that has `maxCanvasSize` prop. It's still the experimental feature, but it works pretty well. This prop doesn't have a default value so set the one that will suit your needs. I suppose it's [3 * 1024 * 1024](https://discussions.apple.com/thread/4975106#:~:text=The%20maximum%20size%20for%20a,300%20pixels%20if%20not%20specified.).

**Comment by Nemesis19** [comment]
Thanks for the reply.

Man, I must tell you, you just anticipate my needs! I updated the lib to 1.3.1, you say it's experimental but I don't know how many tests you need to do...for me it's production ready. It just SOLVES MY PROBLEM!

Thank you, that's a very useful feature, especially for  problematic browsers like Safari!

**Comment by Norserium** [comment]
@Nemesis19, you are welcome!

**Comment by Norserium** [comment]
@Nemesis19, `max-canvas-size` property is deprecated now and it will be deleted soon (as long as it was not documented, in next **minor** releases).

It replaced in `1.5.0` by the possibility to set options in [`canvas`](https://norserium.github.io/vue-advanced-cropper/components/cropper.html#canvas) property.

I.e. this:
```html
<cropper
	:src="image"
	:max-canvas-size="4096*4096"
/>
```

Should be replaced by this:

```html
<cropper
	:src="image"
	:canvas="{
		maxArea: 4096 * 4096
	}"
/>
```

Also you can limit maximum width and height. The example is in ["Resize the result"](https://norserium.github.io/vue-advanced-cropper/guides/recipes.html#resize-the-result) section.

**Comment by Nemesis19** [comment]
thank you for you notification!
