### ISSUE TITLE
Zoom to cropped area programmatically without auto-zoom

### ISSUE THREAD

**Issue by Elvincth** [Norserium/vue-advanced-cropper#116]
How to zoom in and zoom out to a cropped area programmatically without auto-zoom being set?

For instance if I cropped to an area e.g.
![image](https://user-images.githubusercontent.com/6602723/111111484-5bb4d400-8599-11eb-8f88-04516b5d4f89.png)

And I want to programmatically  zoom into the cropped area without auto zoom props passed in (PS. I have tried zoom with left top setted but no luck the targeted center will move):
![image](https://user-images.githubusercontent.com/6602723/111111602-9dde1580-8599-11eb-91aa-c5f8838aec56.png)

Thanks in advance, really appreciate your amazing work.

**Comment by Elvincth** [comment]
UPDATE:
Got working with:
```js 
const publicProperties = this.cropper.getPublicProperties();
      this.cropper.zoom(0, {
        top: publicProperties.coordinates.top,
        left: publicProperties.coordinates.left,
      });
```

```js 
this.cropper.setCoordinates(coordinates, { autoZoom: true });
```

But the cropped area is not being center

**Comment by Norserium** [comment]
Could you describe your use-case in more detail? Why do you need to auto zoom programatically?

Anyway, it's pretty tough to implement this, especially if you want to have transitions during this zoom. Perhaps, I should provide some method that gives the possibility to change coordinates and visible area simultaneously, but even in this case you should calculate the visible area and coordinates very careful to prevent the breaking different limits.

As an alternative you can re-implement auto-zoom algorithm and use the undocumented feature `runAutoZoom`. There is [the example](https://codesandbox.io/s/vue-advanced-cropper-zoom-bx5bp?file=/src/App.vue). The biggest disadvantage that it contains the copy-pasted code from the library to implement auto zoom. I have plans to update `advanced-cropper` library that contains the internal cropper algorithms to provide them to developer, but it is still in work.

**Comment by Elvincth** [comment]
> Could you describe your use-case in more detail? Why do you need to auto zoom programatically?
> 
> Anyway, it's pretty tough to implement this, especially if you want to have transitions during this zoom. Perhaps, I should provide some method that gives the possibility to change coordinates and visible area simultaneously, but even in this case you should calculate the visible area and coordinates very careful to prevent the breaking different limits.
> 
> As an alternative you can re-implement auto-zoom algorithm and use the undocumented feature `runAutoZoom`. There is [the example](https://codesandbox.io/s/vue-advanced-cropper-zoom-bx5bp?file=/src/App.vue). The biggest disadvantage that it contains the copy-pasted code from the library to implement auto zoom. I have plans to update `advanced-cropper` library that contains the internal cropper algorithms to provide them to developer, but it is still in work.

I would like to use it as annotation viewer, e.g., it first highlighted the annotated area in a full non-zoomed in image, and there would be a zoom in button, that the user could click to zoom in more details in the annotated area (Act just like auto zoom options), that is what I am trying to achieve.

**Comment by Elvincth** [comment]
Okay got it working by setting autoZoom true and false and calling  this.cropper.onChange() simultaneous

**Comment by Elvincth** [comment]
@Norserium Btw a quick question would there a lazy loading be available for loading the images through src ?

**Comment by Norserium** [comment]
@Elvincth what do you mean by lazy loading? The possibility to add `loading` attribute to `img`?

**Comment by Elvincth** [comment]
> @Elvincth what do you mean by "lazy loading"? The possibility to add `loading` attribute to `img`?

Using library like:
https://github.com/ApoorvSaxena/lozad.js for loading images in cropper

**Comment by Elvincth** [comment]
> Could you describe your use-case in more detail? Why do you need to auto zoom programatically?
> 
> Anyway, it's pretty tough to implement this, especially if you want to have transitions during this zoom. Perhaps, I should provide some method that gives the possibility to change coordinates and visible area simultaneously, but even in this case you should calculate the visible area and coordinates very careful to prevent the breaking different limits.
> 
> As an alternative you can re-implement auto-zoom algorithm and use the undocumented feature `runAutoZoom`. There is [the example](https://codesandbox.io/s/vue-advanced-cropper-zoom-bx5bp?file=/src/App.vue). The biggest disadvantage that it contains the copy-pasted code from the library to implement auto zoom. I have plans to update `advanced-cropper` library that contains the internal cropper algorithms to provide them to developer, but it is still in work.

Yes that true, that is excatly what I need! Thanks for your quick reply and creating this amazing library

**Comment by Norserium** [comment]
@Elvincth, you are welcome!
