### ISSUE TITLE
Set canvas to false is not working

### ISSUE THREAD

**Issue by Elvincth** [Norserium/vue-advanced-cropper#117]
` <cropper
           ...
            :canvas="false"`

I have followed [https://norserium.github.io/vue-advanced-cropper/components/cropper.html#props](url) and set the canvas to false, but still when I inspect the cropper it still got canvas, also in vue inspect tool there isn't a prop call canvas.

Still got canvas in the elemet:
![image](https://user-images.githubusercontent.com/6602723/111136634-eb1daf80-85b8-11eb-8e8a-b917dad36741.png)

No canvas prop:
![image](https://user-images.githubusercontent.com/6602723/111136753-05578d80-85b9-11eb-9e1e-e90143f21b22.png)

**Comment by Norserium** [comment]
@Elvincth why do you want to eliminate the `canvas` elements?

**Comment by Elvincth** [comment]
> @Elvincth why do you want to eliminate the `canvas` elements?

For better performance, as I would like to use the cropper to show "annotation" part of the image, the user won't be able to resize, or change the stencile, so canavs would not be use I guess? 

e.g.
![image](https://user-images.githubusercontent.com/6602723/111138632-20c39800-85bb-11eb-802d-b67b1f2cb1ec.png)

**Comment by Norserium** [comment]
Actually, that canvases are empty, until you try to get the `canvas` property of the result.

**Comment by Elvincth** [comment]
> Actually, that canvases are empty, until you try to get the `canvas` property of the result.

Got it ! Then it should be ok. Thankas a lot.
