### ISSUE TITLE
npm install @next installs v2.2.0 not v2.2.1

### ISSUE THREAD

**Issue by TheVaan** [Norserium/vue-advanced-cropper#118]
Hello,

I used the @next-suffix and npm installed v2.2.0. You may take a look why npm thinks, that this is still the next version.
![image](https://user-images.githubusercontent.com/1108485/111239990-a286e600-85fa-11eb-9418-4bd8a1467408.png)

Thank you for your great component!

**Comment by Norserium** [comment]
@TheVaan, thank you for your report. Fixed.
