### ISSUE TITLE
Looking for a way to use a mix of image type restrictions

### ISSUE THREAD

**Issue by xariusdesai** [Norserium/vue-advanced-cropper#123]
Hi,

So I'm trying to get a functionality akin to this:

I want the image to be constrained to the cropper as in fit-area (ie. I can zoom in as much as I want, but can only zoom out as much as the max image height / width)

but I want to be able to use the crop itself like the image restriction is none (ie. I can add transparent areas to my crop).

<img width="674" alt="Screenshot 2021-03-24 at 14 51 47" src="https://user-images.githubusercontent.com/32044588/112331040-7b8e7b00-8cb0-11eb-8a3b-c3fa1df8f128.png">

My use case is that I want to create some square images from some rectangular ones, and sometimes I'll need the whole height/width so what I'm actually looking to do is pad the image into a square one.

Is there a way to currently do this?

Thanks

**Comment by Norserium** [comment]
@xariusdesai, hello! In other words, you want to get the behavior like `image-restriction: none` but without the possibility to make the image smaller than visible area?

**Comment by xariusdesai** [comment]
@Norserium thats exactly what I'm looking to do. Is it possible to do currently?

**Comment by Norserium** [comment]
@xariusdesai, I assume it's possible. Try [this example](https://codesandbox.io/s/vue-advanced-cropper-custom-area-restriction-vlhkx?file=/src/App.vue).

**Comment by xariusdesai** [comment]
@Norserium thanks for that, I need to make some tweaks depending on my use case but its got me most of the way there!

**Comment by Norserium** [comment]
@xariusdesai, you are welcome!
