### ISSUE TITLE
File gets to large when convert it to blob.

### ISSUE THREAD

**Issue by TaeyoonKwon** [Norserium/vue-advanced-cropper#125]
It seems the file size gets too large after converting the canvas to a blob.

I am using `toBlob()` method as instructed in the documetation.

```
const fr = new FileReader();
fr].readAsDataURL(this.files[0].file);
fr.onload = () => {
    this.cropper = fr.result;
}
```

`const blob = await new Promise((resolve) => canvas.toBlob(resolve));`

I am currently using stencil to crop the canvas, the result is cropped, so I think the file size should be smaller, but it results bigger. For example, one of my image's original size is 1.3MB but results in 5MB.

**Comment by Norserium** [comment]
@TaeyoonKwon, did I answer your question?

**Comment by TaeyoonKwon** [comment]
@Norserium Thank you for the answer. Though it still increases the file size, I understand it is not the conern of the library.

**Comment by Norserium** [comment]
@TaeyoonKwon, take a look at [the updated upload example](https://norserium.github.io/vue-advanced-cropper/guides/recipes.html#load-image-from-a-disc).
