### ISSUE TITLE
How to start the cropper full size?

### ISSUE THREAD

**Issue by Dylan190774** [Norserium/vue-advanced-cropper#127]
Hi, I can't figure out how to set the cropper to the full width and height of the image from the start.
It always starts with about a 10 percent margin around it.
I'd like to be able to set it to maximum when a new image is loaded, but let the user change it if necessary.

I found the defaultSize, defaultPosition and defaultVisibleArea props quite confusing, since the examples work with size in pixels, but I load all kinds of images of different sizes, so I just need this to be 100% or something like that.

A prop to just set the default margin to 0 would also be very welcome.

**Comment by Dylan190774** [comment]
Oops, should have searched a bit further.
This seems to work:

```
      //METHOD defaultSize
      defaultSize({ imageSize }) {
        return {
          width: imageSize.width
        , height: imageSize.height
        };
      }

```
with  an
`              :default-size="defaultSize"`
attribute in the HTML of the cropper

**Comment by Norserium** [comment]
@Dylan190774, yes, the redefining of default `defaultSize` prop value is the right approach. The default value is [the following function](https://github.com/Norserium/vue-advanced-cropper/blob/0a9af38761e864b81cfafa19f2ba921ce1e017e8/src/core/algorithms/defaultSize.ts#L33). It, indeed, tries to leave 20% margin.

**Comment by Dylan190774** [comment]
Thanks, would you consider making the 0.8 value optional through a prop?

**Comment by Norserium** [comment]
@Dylan190774, I suppose it will be redundant. It's pretty specific case, and if the developer indeed need to set the different percents, he can easily redefine the `default-size` prop.

I have added the example for your case in [the documentation](https://norserium.github.io/vue-advanced-cropper/guides/advanced-recipes.html#default-size-and-position).

**Comment by Norserium** [comment]
By the way, nice to meet you. How is your progress with [this issue](https://github.com/Norserium/vue-advanced-cropper/issues/109)?

**Comment by Norserium** [comment]
@Dylan190774, any news?

**Comment by Norserium** [comment]
I close the issue. Feel free to reopen if necessary.
