### ISSUE TITLE
Size of cropped image become very big(After cropping)

### ISSUE THREAD

**Issue by Akhil-bridge** [Norserium/vue-advanced-cropper#128]
Example,
If i have an image with big resolution and small size(120KB), then upload and cropped using vue-advanced-cropper, Then the image size is more than (~) 3Mb. Any solution for it? it seriously affect the performance of my web app. Please help !!

**Comment by Norserium** [comment]
@Akhil-bridge, I'm not sure that it's the concern of this library. I assume that you converts the canvas to a base64 encoded string by using the method [`toDataURL()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL) without setting the first argument `type`.

I can recommend the following:
1. Use [`toBlob`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob) method, it gives lighter result.
2. Set the appropriate mime type (the second argument) during the conversion, i.e. for an uploaded jpeg image set `image/jpg`, for an uploaded png image set `image/png` and etc.

[The similar issue](https://github.com/Norserium/vue-advanced-cropper/issues/41).

**Comment by Norserium** [comment]
@Akhil-bridge, take a look at [the updated upload example](https://norserium.github.io/vue-advanced-cropper/guides/recipes.html#load-image-from-a-disc).

**Comment by Akhil-bridge** [comment]
@Norserium Thanks for your support. As you said its mot am issue with the library. As per you guidance I fixed the issue
