### ISSUE TITLE
Cropper appears with way to much 'height'

### ISSUE THREAD

**Issue by eMZetta** [Norserium/vue-advanced-cropper#129]
I have following problem with implementing the minimal example:

I try to make it exactly according to the served example, but the image appears in the browser only after several scrolls way too far down.

This is a PrintScreen from the browser zoomed out 75%:
![browser](https://user-images.githubusercontent.com/6057036/114279330-5762c600-9a34-11eb-93c9-b8de0f59b841.jpg)

Elements in development tools:
![Bildschirmfoto von 2021-04-10 18-28-59](https://user-images.githubusercontent.com/6057036/114277287-d94df180-9a2a-11eb-8d07-08f0e07737ff.png)

Here is my code:

```
<div>
                    <cropper
                        class="cropper"
                        :src="img"
                        :stencil-props="{
                            aspectRatio: 10/12
                        }"
                        @change="change"
                    ></cropper>
</div>
```
`img: string = 'https://images.pexels.com/photos/226746/pexels-photo-226746.jpeg';`
````
change(){
        console.log('changed');
    }
```
```
.cropper {
    height: 600px;
    background: #DDD;
}
```

I hope my problem can be understood, thanks in advance

**Comment by Norserium** [comment]
@eMZetta, I assume that you didn't load the cropper's styles:
`import 'vue-advanced-cropper/dist/style.css';`

By the way, where did you find this minimal example?

**Comment by eMZetta** [comment]
>  I assume that you didn't import the cropper's styles: import 'vue-advanced-cropper/dist/style.css';

That caused not the problem. I've imported the styles.

> By the way, where did you find this minimal example?

https://www.npmjs.com/package/vue-advanced-cropper in the 'Usage'-section

> /*
  Maybe you need to set the limits for the cropper sizes or its container sizes
  otherwise a cropping image will try to fill all available space
*/

What exactely is meant with this?

**Comment by Norserium** [comment]
@eMZetta, could you reproduce your problem in codesandbox? Could you provide more source code?

> What exactely is meant with this?

Cropper tries to take all available place for its image. For the used image it's 3698 x 5547.

**Comment by eMZetta** [comment]
Finally, shame on me, this is embarrassing. I had the wrong path to the style.css file.
After I fixed the path, everything works fine.

I was able to solve it thanks to your reference to the codesandbox. You can reproduce my issue just deleting the import statement of the style.css.

@Norserium Thank you a lot for your support and this great component!

**Comment by Norserium** [comment]
@eMZetta, it's okay. You are welcome!
