### ISSUE TITLE
How to resize the image result?

### ISSUE THREAD

**Issue by metalsadman** [Norserium/vue-advanced-cropper#130]

**Comment by Norserium** [comment]
@metalsadman, hello!

 I've added the possibility to limit the result canvas size in `1.5.0` in the [`canvas`](https://norserium.github.io/vue-advanced-cropper/components/cropper.html#canvas) property.  Take a look at the real-time example in ["Resize the result"](https://norserium.github.io/vue-advanced-cropper/guides/recipes.html#resize-the-result) section.

It uses the default canvas image scaling procedure under the hood. If the result doesn't suit you, try to use the external libraries
to resize image ([pica](https://github.com/nodeca/pica), [downscale](https://github.com/ytiurin/downscale) and etc.)

**Comment by 9mm** [comment]
Hey @Norserium thats really helpful. Can you let me know what might not suit people about that method? It looks very simple out of the box, but really my only concern is quality. Does it preserve the original image quality at 100%? Other than that I don't need fancy bells and whistles.

Thanks

**Comment by Norserium** [comment]
@9mm, I decided to use the standard canvas image resizing algorithm for a while. When it downscale large images, they may become slightly noisy. There are [examples](https://stackoverflow.com/questions/2303690/resizing-an-image-in-an-html5-canvas). 

To increase the quality you can set `imageSmoothingQuality` parameter to `high`:
```html
<cropper
   :src="image"
   :canvas="{
        imageSmoothingQuality: 'high',
        maxWidth: 200,
        maxHeight: 200
   }"
```

> Does it preserve the original image quality at 100%? 

Nobody preserves original quality if it comes to a image resize.

**Comment by 9mm** [comment]
Wow, thats very interesting. Thanks so much. Sorry, 100% is the wrong word, but something very close to photoshop downscaling resampling algorithms.

**Comment by 9mm** [comment]
I'll have a look at these libraries again, huge help 👍🏼

**Comment by Norserium** [comment]
You are welcome!

**Comment by stylefieber** [comment]
Thank you for that great component. I also struggle with downscaling quality. Am I right, that I would have to implement the cropping and resizing completely again to be able to use one of that libraries?

**Comment by Norserium** [comment]
@stylefieber, could you provide the example of quality decreasing? Did you try to set the `imageSmoothingQuality` parameter to high?

**Comment by Norserium** [comment]
There is [the example](https://codesandbox.io/s/vue-advanced-cropper-resize-image-0vpx6?file=/src/App.vue) of image resizing using [the external library](https://github.com/nodeca/pica).

**Comment by 9mm** [comment]
On chrome at least that example seems to not keep the original proportions

**Comment by stylefieber** [comment]
@Norserium 
![image](https://user-images.githubusercontent.com/13904842/116796370-1b270080-aadc-11eb-8b73-f249a1e71f99.png)

here is an example with imageSmoothingQuality set to high. Unfortunately very noisy.

Thank your for the example. I have a look.

**Comment by Norserium** [comment]
@9mm, I've fixed the example. Take a look.

**Comment by 9mm** [comment]
@Norserium awesome, thanks! I'm about to be working on this this weekend, I appreciate these awesome examples.

Off the top of your head, do you know which of these optional resize libraries which use better algorithms than canvas perform best? If you aren't sure I planned to just try a bunch of them, but I wasn't sure if one stood out far above the rest as far as quality (speed not as important in my use case) 😎 

Thanks

**Comment by Norserium** [comment]
@9mm, alas, I can't answer your question, because I didn't compare this libraries. I advice you to play with [the library options](https://github.com/nodeca/pica#resizefrom-to-options---promise) to get the result similar to, as you said, results of Photoshop's scaling. The developers helpfully published [the guide](https://github.com/nodeca/pica/wiki/Unsharp-params-in-popular-softare) for it.

After all, if you won't be able to get the needed result, you can try to find the implementation of the specific algorithm that you used in Photoshop in JavaScript (for example, `Bicubic Sharper`).

**Comment by Norserium** [comment]
@9mm, I've tried the options for Photoshop and, frankly, it looks pretty different. So I play around with settings and get something more similar, take a look at [the example](https://codesandbox.io/s/vue-advanced-cropper-resize-image-0vpx6?file=/src/App.vue).

**Comment by stylefieber** [comment]
@Norserium So it's okay with pica now. But, of course, now I have to calculate the width and height and so on by my self. Before, your component did this for me by defining min and max width/height.
Maybe you could think about implementing pica in your code, so that there is no need for custom code. I guess the image quality when resizing is one of the most important aspects when using a cropper. So the work might worth it :) If you don't mind, I could provide a pull request. Just have a week off and could contribute.

But again: Thank you for that awesome component.

**Comment by Norserium** [comment]
> But, of course, now I have to calculate the width and height and so on by my self. 

Could you explain, why it's the problem if you use external library anyway?

> Maybe you could think about implementing pica in your code, so that there is no need for custom code.

It's too heavy ([28.5 kB](https://bundlephobia.com/result?p=pica@6.1.1), almost the half of this library), so I'm not sure, that it worth a shot.

By the way, I fixed the passing options parameter to the context, so the quality setting was repaired. Try to update to `1.5.2`.

**Comment by 9mm** [comment]
Awesome! Thanks for that code .. I'm having a look at this today and I'll report back after a lot of testing.

I also found this for anyone browsing this thread, it has some great info in it: https://stackoverflow.com/questions/18922880/html5-canvas-resize-downscale-image-high-quality

**Comment by Norserium** [comment]
@9mm, try also the last version in your tests.

**Comment by 9mm** [comment]
One fast question, does `getResults()` always return base64? I don't need to support old browsers so I was wondering if there were a way to continue working with blobs (for performance + memory reasons).

Looking great so far, still working through these 😎

**Comment by stylefieber** [comment]
@Norserium The fix for "imageSmoothingQuality" seems to work. The quality is much better now, even without pica.

Anyways - it could be implemented as optional module, so that you only add the overhead when really needed. 
Maybe you could add the "imageSmoothingQuality" to the docs.

**Comment by Norserium** [comment]
@stylefieber, actually, I set its default value to `'high'` in the last version. And it's documented in [the corresponding documentation section](https://norserium.github.io/vue-advanced-cropper/components/cropper.html#canvas).

**Comment by stylefieber** [comment]
Oh okay? Could it have been a bug, that the parameter was not correctly recognized or so?

I just had a look. You're right. But it seems that I did not set "imageSmoothingEnabled". Was it default "false" in the previous version?

**Comment by Norserium** [comment]
> Was it default "false" in the previous version?

The parameters `imageSmoothingEnabled` and `imageSmoothingQuality` were not passed to context at all.
