### ISSUE TITLE
How can i mask the cropped region with some color

### ISSUE THREAD

**Issue by srinivaas14** [Norserium/vue-advanced-cropper#133]
Hi @Norserium , the plugin is awesome with so many useful features.
Currently I have a requirement , in which the cropped region of the image should be masked with the color, so please let me know/provide any guidelines to achieve this functionality.
Thanks

**Comment by Norserium** [comment]
@srinivaas14, could you provide the example of what you want to get? It's not clear now.

**Comment by srinivaas14** [comment]
@Norserium ,Sure please check the below images

Original Image: 
![2](https://user-images.githubusercontent.com/26761231/115400980-8123a600-a207-11eb-9f50-b7c042c51960.png)

Expected image format after cropping:
![cropped_output](https://user-images.githubusercontent.com/26761231/115401109-a9130980-a207-11eb-809d-7f16fcd37c9a.png)

**Comment by Norserium** [comment]
If you want to colorize the cropped region after crop, then it doesn't concern of this library. The cropper has done his work. You got the coordinates.

You should do it on your own. There is [the simplest example](https://codesandbox.io/s/vue-advanced-cropper-terminator-eye-pymub).

**Comment by srinivaas14** [comment]
@Norserium , I agree with your comment related to functionality. I've checked the given example. Thanks for the help and also for this awesome library.
