### ISSUE TITLE
Cropper component inaccessible via ref in composition-api.

### ISSUE THREAD

**Issue by metalsadman** [Norserium/vue-advanced-cropper#136]
In composition api, using a ref on `<cropper />` always results to null, this works in options api.

Please see codepen and check logs in browser devtool.
https://codepen.io/metalsadman/pen/eYgagpO?editors=1010
1. click on to select an image
![image](https://user-images.githubusercontent.com/31038838/116515968-941d3100-a8ff-11eb-9882-407f22e17d3d.png)
2. choose an image
3. check logs to see `cropperRef` still null.

What I tried: `:ref=" el => { cropperRef = el }"` did not work.
Workaround: `<cropper @change="v => { cropperRef = v.canvas.parentNode['__vue__'].$parent }"` ...`

**Comment by Norserium** [comment]
Hello!

You forgot to return `cropperRef` in `useCropperData` result.

```js
return {
      cropperRef, // <<<
      dialog,
      stencilProps,
      stencilSize,
      canvasSize,
      imageSrc,
      cropper,
      flip,
      rotate,
      save,
      zoom,
      show,
      hide,
      onDialogHide,
      onOKClick,
      onCancelClick,
      cropperReady,
      processImage
    }
```

**Comment by metalsadman** [comment]
oops, yes it seem like it works in codepen but oddly in my real project, I can't seem to get the cropper ref, without the workaround. anyway no biggie, the `@change` emitting the canvas is good enough for me atm. thanks.

**Comment by Norserium** [comment]
@metalsadman I assume that there is another problem in your real project. Ensure that `cropperRef ` is in your component instance (with `null` value at least).

**Comment by metalsadman** [comment]
> @metalsadman I assume that there is another problem in your real project. Ensure that `cropperRef` is in your component instance (with `null` value at least).

yes I do have it, in codepen I just added that `cropperRef` for example, in my real one the reference is just the `cropper` ref, and I tested it again just now and the reference still ends up null. Only difference is the component is called in a plugin that is created in another Vue instance kinda portal like, but it does hold the parent component's context, but yeah like I explained this works ok if I use options api with the same cropper component and implementation.

here an updated codepen of what I was actually doing, I've made 2 components using the different apis. https://codepen.io/metalsadman/pen/JjEqJVr?editors=1010

**Comment by Norserium** [comment]
I assume it's the some sort of `QuasarDialog` issue, not this libary. Try to set ref on the other element and you will get the same result. 

Anyway I can offer the better workaround:
```js
    const instance = getCurrentInstance();
    function cropperReady (v) {
      console.log('on Ready: Cropper Ref ->', instance.refs.cropper)
   }
```

**Comment by Norserium** [comment]
@metalsadman, I assume that it's combined `quasar` and `composition-api` issue. Somehow ref from `setup` is not passing to string ref (no matter what element).

> though it looks like it's not playing well within an iframe, as you can see in the codepen.

You didn't load cropper styles in codepen.

**Comment by metalsadman** [comment]
> @metalsadman, I assume that it's combined `quasar` and `composition-api` issue. Somehow ref from `setup` is not passing to string ref (no matter what element).
> 
> > though it looks like it's not playing well within an iframe, as you can see in the codepen.
> 
> You didn't load cropper styles in the codepen.

my bad :facepalm:, which one is it?

**Comment by Norserium** [comment]
```html
<link rel="stylesheet" href="https://unpkg.com/vue-advanced-cropper@^1.5.1/dist/style.css" />
```

**Comment by metalsadman** [comment]
> ```
> <link rel="stylesheet" href="https://unpkg.com/vue-advanced-cropper@^1.5.1/dist/style.css" />
> ```

yeah, thanks again. 
![image](https://user-images.githubusercontent.com/31038838/116567736-7ae5a600-a93a-11eb-9104-577c425c1529.png)

**Comment by Norserium** [comment]
You are welcome! Nice result, by the way.
