### ISSUE TITLE
Mime-Type Problem

### ISSUE THREAD

**Issue by 9mm** [Norserium/vue-advanced-cropper#137]
Hello,

I'm following the directions from here: https://norserium.github.io/vue-advanced-cropper/guides/recipes.html#load-image-from-a-disc

But the mimeType seems to always be blank. Specifically here:

    const byteArray = (new Uint8Array(file)).subarray(0, 4);

This will always return `[]` from what I find. Do you have any idea what might be the problem? In your code, the format of `file` is... `data:image/png;base64,iVBORw0KGgo........`

**Comment by 9mm** [comment]
I believe this line:

```
// Start the reader job - read file as a data url (base64 format)
				reader.readAsDataURL(files[0]);
```

needs to be changed to `reader.readAsArrayBuffer(files[0]);`

**Comment by Norserium** [comment]
@9mm, the example is fixed now. Thank you.
