### ISSUE TITLE
How to achieve this cropper?

### ISSUE THREAD

**Issue by 9mm** [Norserium/vue-advanced-cropper#138]
Hey, I really love this cropper so far - excellent work (I'm using the Vue 3 version).

I have it about 80% to my liking but there are 2 areas I'm still investigating and I'm wondering if you could give your expert opinion on how to solve this.

1. How can I completely disable all zooming? All the examples I find from other issues still have zooming. I just want to disable it all (which leads to point 2)
2. How do I make the cropper show everything on the screen at once? I'm going to be putting it in a modal which should be set at `max-height: 80vh` and `max-width: 80vw`, but really any way to make the modal "fit" would work. The problem is making the cropper understand it's parent size, and then scaling.

**Comment by Norserium** [comment]
> How can I completely disable all zooming? 

Could you explain what it means? You can disable zoom by touch and mouse wheel. Yes, it won't guarantee that any possible zoom will be disabled, but at least something.

**Comment by 9mm** [comment]
Basically the image should never change size. It's just a fixed image. In my gif, even though you can't see it, I'm moving the scroll wheel and the image is not changing size.

This also means however that the whole cropper needs to be visible at once so they can access all areas of it.

Did I explain it better?

**Comment by Norserium** [comment]
Thanks. I assume, that you encounter the problem when cropper "cuts" some parts of image instead of reducing its size?

**Comment by 9mm** [comment]
No, I haven't even gotten to the part where I use the cropper output, I'm still just styling it. The problem is I literally just dont want the image to get bigger and smaller as I think it's very jarring to the user experience. It offers a higher granularity of cropping at the cost of things moving too much and being disruptive (for my use case anyway).

I always want the image to fit on the screen, and the most they can do is move the cropper around, and if they're trying to create a crop which is really small, then they simply lose their precision (I'm fine with this, as the benefits outweigh this con).

I have tried adding the disable zoom props but I could still zoom... maybe I did it wrong? Where does it go in here?

```
        <cropper
          ref="cropper"
          v-if="imageData.src"
          :src="imageData.src"
          :debounce="500"
          :min-width="formattedValidations.width"
          :min-height="formattedValidations.height"
          image-restriction="fit-area"
          :stencil-props="{
            aspectRatio: formattedValidations.width / formattedValidations.height,
          }"
          class="photoshop-grid"
        />
```

**Comment by Norserium** [comment]
@9mm, I assume you want to obtain [this behavior](https://codesandbox.io/s/vue-advanced-cropper-static-visible-area-yjdgx?file=/src/App.vue)?

**Comment by 9mm** [comment]
Yes!! Thats awesome! I have one more (way more fun) challenge but let me add it into your code sandbox.

**Comment by 9mm** [comment]
You are like the crop 👑 

<img src="https://media.giphy.com/media/K55exy0toWjQc/giphy.gif">

**Comment by Norserium** [comment]
> Yes!! Thats awesome!

Ironically, but a long time ago something like it was the default behavior (when zoom was not supported at all).

**Comment by 9mm** [comment]
ha 🤣 

I'm just modifying this code sandbox quick to show you something

**Comment by 9mm** [comment]
Ok I edited this code sandbox to show my use case. Its supposed to be emulating a modal popup.

Theres 2 things I'm trying to achieve:

1. The modal seems to be taking up 100% vertical and horizontal space whenever possible. I want those to be max-widths and not actual widths. I'm trying to get the modal to simply match the size of the image when possible (see my original gif, how the modal always matches the image size, and they both scale together).
2. I added a Photoshop-style background grid that should only show for images with transparency (image #1). For images without transparency no grid will show because the modal will collapse in size (bullet 1). You will notice however that for image #1 with transparency, the background grid is not the same size. I want the grid to be "lit up" just like the photo, which this seems to work very closely except now the background image is changing scale along with the image. It should line up with the background grid.

https://codesandbox.io/s/vue-advanced-cropper-static-visible-area-forked-ui4ux?file=/src/App.vue

Here are the 2 images in the codesandbox, with one of them commented out

```
// SHOULD show checkerboard (its actually transparent):
image: "https://i.imgur.com/x1X6UsT.png",
// shouldn't show any checkerboard and should fit width:
// image: "https://images.pexels.com/photos/3268526/pexels-photo-3268526.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
```

**Comment by Norserium** [comment]
> The modal seems to be taking up 100% vertical and horizontal space whenever possible. I want those to be max-widths and not actual widths. I'm trying to get the modal to simply match the size of the image when possible (see my original gif, how the modal always matches the image size, and they both scale together).

I don't get it.

You have set:
```css
.wrapper {
  width: 100vw;
  height: 100vh;
  ...
}
```

**Comment by 9mm** [comment]
Thats simply the wrapper which contains the modal, not the modal itself. The `.wrapper` class typically has a 50% opacity background so the user can't click other elements, and it must be full size.

It's the `.modal` box which is the actual modal itself which needs to center within that 100% w/h space, and only take up as much room as it needs.

If the wrapper were not 100% width and height then the modal couldn't be vertically and horizontally centered.

**Comment by Norserium** [comment]
> I added a Photoshop-style background grid that should only show for images with transparency (the Apple Jacks image). You will notice however that the background grid doesnt line up. I want the grid to be "lit up" just like the image (no dark overlay within stencil). Now the background image is changing scale along with the image. It should line up with the background grid.

It's a tough one. I can offer you only [a workaround](https://codesandbox.io/s/vue-advanced-cropper-static-visible-area-forked-wf3su?file=/src/App.vue) now. Moreover, conceptually, all solutions that I see will look similar.

**Comment by Norserium** [comment]
> I'm trying to get the modal to simply match the size of the image when possible (see my original gif, how the modal always matches the image size, and they both scale together).

Could you draw some examples, that illustrates your desired result?

**Comment by 9mm** [comment]
Wow the background workaround is incredible, that's perfect. And sure, let me draw.

**Comment by 9mm** [comment]
# Example 1 (image with transparency)

## ACTUAL:

![image](https://user-images.githubusercontent.com/1386207/117055545-1dea4700-acd0-11eb-808d-16e9ae0adadc.png)

## GOAL:

![image](https://user-images.githubusercontent.com/1386207/117055503-1034c180-acd0-11eb-9877-a32ccd128159.png)

# Example 2 (image with no transparency)

## ACTUAL:

![image](https://user-images.githubusercontent.com/1386207/117055757-5db12e80-acd0-11eb-8f8d-f468c810a276.png)


## GOAL:

![image](https://user-images.githubusercontent.com/1386207/117055879-889b8280-acd0-11eb-9943-72ea43a2523f.png)

**Comment by 9mm** [comment]
One more example where small images already work correctly (images which don't need to be resized to fit within the browser window)

![image](https://user-images.githubusercontent.com/1386207/117057015-ce0c7f80-acd1-11eb-872a-984578c55f1f.png)

**Comment by Norserium** [comment]
Try [this](https://codesandbox.io/s/vue-advanced-cropper-static-visible-area-forked-4z325?file=/src/App.vue).

**Comment by 9mm** [comment]
🙏🏼 🙏🏼  Dude you are Legend 🙏🏼 🙏🏼 

Do you have one of those links where I buy you a coffee?

**Comment by 9mm** [comment]
I will try it out shortly, it looks really close if not dead on at first glance 😆

**Comment by Norserium** [comment]
> Do you have one of those links where I buy you a coffee?

Currently there is no such link. But thank you for the wish.

**Comment by 9mm** [comment]
You are so awesome, I am eternally grateful. Both solutions work perfectly.

![](https://media.giphy.com/media/fDzM81OYrNjJC/source.gif)

Only one small revision for anyone that finds this, the bottom line of last example should be this instead:

    stretcher.style.height = `${cropper.clientWidth / ratio}px`;

**Comment by Norserium** [comment]
@9mm, yeah, it's misspell. Fixed.

**Comment by Norserium** [comment]
I assume the issue may be closed?

**Comment by 9mm** [comment]
Yeah! It works really, really well. Thanks so much, you are the bomb 😎

**Comment by Norserium** [comment]
You are welcome!
