### ISSUE TITLE
How can I apply filtering to an image?

### ISSUE THREAD

**Issue by drlim29** [Norserium/vue-advanced-cropper#141]
Hi, I would like to know how to apply filtering on image.

- How can I apply filtering to an image?
- After I edit the `canvas` then rotate it, it is restored to original one.
   May I know what is the issue with it?
- I would like to apply grayscale to an image, Please let me know how.

**Comment by Norserium** [comment]
@drlim29, any news?

**Comment by Norserium** [comment]
@drlim29, I close the issue. Feel free to reopen.
