### ISSUE TITLE
Feature Request: Fill image background with specific color

### ISSUE THREAD

**Issue by kostaskoukouvis** [Norserium/vue-advanced-cropper#142]
Awesome tool! Would it be possible to add a prop to fill the cropped image background with a specific color?

Currently if you zoom out of the image and crop part of it the rest of the resulting image will be transparent. It would be nice if there was an option to fill that space with a color, probably with a prop sent to `canvas`? 
 
Essentially that would require changing the `updateCanvas` function to do fillRect() before calling the drawImage() method. As far as I understood it is not possible to manually modify that method before calling `getResults()` right?

**Comment by kostaskoukouvis** [comment]
Dude! You rock! Thanks a lot!

**Comment by Norserium** [comment]
@kostaskoukouvis, you are welcome!
