### ISSUE TITLE
Cannot read property 'toDataURL' on canvas=false

### ISSUE THREAD

**Issue by alejandri** [Norserium/vue-advanced-cropper#143]
Hi, on this great package. I have a problem with Cors t show image from server, then I set attr canvas="false". With this solve image display. But I want save img, All examples are based on canvas object. How I can save cropped img?

      <cropper
            ref="cropper"
            class="cropper"
            :src="avatar"
            :canvas="false"
            :transitions="true"
            default-boundaries="fill"
            image-restriction="fit-area"
            @change="change"
          /> 
          <v-btn text @click="download"> aplicar </v-btn>

```
    download({ coordinates }) {
      const { canvas } = this.$refs.cropper.getResult();
      const newTab = window.open();
      newTab.document.body.innerHTML = `<img src="${canvas.toDataURL()}"></img>`;
    }
```

Laravel 8, Vue Js 2

**Comment by Norserium** [comment]
@alejandri, you can't. If the response doesn't have appropriate `Access-Control-Allow-Origin` header, you can't retrieve the image content in the browser by security reasons. 

There is [the CORS guide](https://norserium.github.io/vue-advanced-cropper/guides/cross-origin.html#introduction) in the documentation. I hope it will be helpful for you.

**Comment by Norserium** [comment]
@alejandri, I close the issue due inactivity. Feel free to reopen.
