### ISSUE TITLE
More lines and handlers in specific place

### ISSUE THREAD

**Issue by KLala94** [Norserium/vue-advanced-cropper#146]
Hello, I am Klala.
I like the documentation and the cropper.
But i want to have two more lines in the middle.
i tried the:
```
    <cropper class="cropper" boundingBoxClass="main-foto" :handlers="{
	eastNorth: false,
	north: false,
	westNorth: false,
	west: false,
	westSouth: false,
	south: false,
	eastSouth: false,
	east: false
}
" :linesClasses="{
	default: 'line',
	hover: 'line--hover',
	north: 'line--north',
	west: 'line--west',
	south: 'line--south',
	east: 'line--ease',
    middle: 'line-middle'
}
" lines="{
	north: false,
	west: false,
	south: false,
	east: false,
    middle: false
}
" :src="require('../assets/' + mainImg)" :stencil-props="{
      aspectRatio: 12/12
    }" @change="change">
    </cropper>
```

Is there a way to achieve this?
Thanks in advance.

**Comment by Norserium** [comment]
@KLala94 do you have a picture of the desired result?

**Comment by KLala94** [comment]
![Screenshot from 2021-06-18 16-34-47](https://user-images.githubusercontent.com/33783714/122577620-4b5a3c80-d053-11eb-91c6-3b61275cac4f.png)
the two lines in the middle are what i need.

**Comment by KLala94** [comment]
![Screenshot from 2021-06-18 16-46-13](https://user-images.githubusercontent.com/33783714/122579003-bfe1ab00-d054-11eb-9a5c-cf4ab3f7964c.png)

I did this with duplicating nodes.
I want to control the middle lines and handlers with a class and have them be one or two on conditions.
Thanks for your time.

**Comment by Norserium** [comment]
Should the middle lines and the corresponding handlers be interactive? If so, what happens with the stencil when an user interacts with them?

**Comment by KLala94** [comment]
they are only to be visually.

**Comment by KLala94** [comment]
i just want to have the posibility to see them in different spacing

**Comment by Norserium** [comment]
It may mislead an user, that will try to move middle handlers. They looks just like the other handlers, but they are static.

**Comment by KLala94** [comment]
then maybe just the lines, so that they will be visible.
i need to show that the image could be shown in parts, something that i am still making, the preview will have those lines and i wanted to be on the cropper too.
Thanks

**Comment by Norserium** [comment]
> the preview will have those lines and i wanted to be on the cropper too

I didn't understand it. The lines are placed on preview on the examples above.

**Comment by KLala94** [comment]
i made that picture with developent tools of mozilla, by duplicating the lines, i want them on the cropper and on the image shown after the cropper changes. Am i misunderstanding something?
I will make them in the picture, but have no idea on the cropper.
The lines position would be on the ideal changed by a class.

**Comment by Norserium** [comment]
I still don't get the idea. Let's try the another approach. What's wrong with [this example](https://codesandbox.io/s/vue-advanced-cropper-custom-stencil-nhxf2)?

**Comment by KLala94** [comment]
i am still looking at it, but i think this may work.
Thanks, you may close this issue.

**Comment by Norserium** [comment]
@KLala94, it can be used to illustrate your idea more clearly. What do you want to change in it?

**Comment by KLala94** [comment]
i am about to change the top only, but thanks, no need to worry anymore.

**Comment by Norserium** [comment]
@KLala94, you are welcome!
