### ISSUE TITLE
stencilProps issue

### ISSUE THREAD

**Issue by itsikhar** [Norserium/vue-advanced-cropper#15]
Hi,
I have an issue to load image with dimensions equals (also the minimum dimensions I configured) to the asspect ratio.

for example:
the image dimensions is exacly width: 1500px and height: 375px.

when using the following asspect ratio:
{
        minAspectRatio: 4 / 1,
        maxAspectRatio: 4 / 1
}

the stencil deminisions is 0 for width, height, left, top and also a console error received with the following message:

" (index):1 Uncaught (in promise) Current aspect ratio can't is uncompatible with minimum/maximum height and width settings. Can't setup default coordinates"

when using the following ratio:
{
        minAspectRatio: 1 / 1,
        maxAspectRatio: 1 / 1
}

It's working perfect.

the total conponent configuration i'm passing into the cropper:

`
<Cropper ref="cropper"
                 :src="file"
                 class="cropper-element"
                 areaClassname="copperContainer"
                 :restrictions="resPixels"
                 :minHeight="375"
                 :minWidth="1500"
                 :stencilProps="{
        minAspectRatio: 4 / 1,
        maxAspectRatio: 4 / 1
}"
                 @change="change"></Cropper>

 resPixels(minWidth, minHeight, maxWidth, maxHeight, imageWidth, imageHeight) {
                return {
                    minWidth: this.minWidth > 400 ? this.minHeight * this.cropperRatio.maxAspectRatio : minWidth,
                    minHeight: this.minHeight > 400 ? this.minHeight : minHeight,
                    maxWidth: imageWidth,
                    maxHeight: imageHeight
                }
            }

`

Please your kind help for detecting if it's a bug or a configuration issue.
Itsik.

**Comment by Norserium** [comment]
Hello! 

I've created [the fiddle](https://jsfiddle.net/L6nfmybk/) for your example. And it works.

Could you send me an image that breaks it?

And additional remarks:
- currently you can't use `this` in `restrictions` callbacks, so `this.minWidth` and `this.minHeight` are undefined now
- why do you use `minAspectRatio` and `maxAspectRatios` instead of `aspectRatio`?

**Comment by Norserium** [comment]
What's version of `vue-advanced-cropper` do you use?

**Comment by itsikhar** [comment]
Hi,

as you can see in the image, the cropper has no width and height:
![image](https://user-images.githubusercontent.com/32879944/66910159-b3eb4d80-f016-11e9-8352-990e5cfed460.png)


> currently you can't use this in restrictions callbacks, so this.minWidth and this.minHeight are undefined now
> why do you use minAspectRatio and maxAspectRatios instead of aspectRatio?

I Fixed those remarks, thanks.

Current version: 0.10.0

thank you for your quick response :)
Itsik.

**Comment by itsikhar** [comment]
Yes, you help me few month ago :)
I'll update the version and write you back with the result

**Comment by itsikhar** [comment]
Hi,

Same error after the update.
But now the cropper not loaded and a black screen appears instead.

![image](https://user-images.githubusercontent.com/32879944/66913154-c23c6800-f01c-11e9-9d37-0be40f0a0a00.png)

**Comment by Norserium** [comment]
It's strange. Could you test my [fiddle](https://jsfiddle.net/L6nfmybk/)?

**Comment by itsikhar** [comment]
same error as before:

" (index):1 Uncaught (in promise) Current aspect ratio can't is uncompatible with minimum/maximum height and width settings. Can't setup default coordinates"

**Comment by Norserium** [comment]
And what's about fiddle?

**Comment by itsikhar** [comment]
` resPixels(minWidth, minHeight, maxWidth, maxHeight, imageWidth, imageHeight) {
                let _minWidth = this.minWidth;
                let _minHeight = this.minHeight;
                return {
                    minWidth: _minWidth > 400 ? _minWidth : minWidth,
                    minHeight: _minHeight > 400 ? _minHeight : minHeight,
                    maxWidth: imageWidth,
                    maxHeight: imageHeight
                }
            }`

**Comment by Norserium** [comment]
It's a very strange code. What it does?
```
resPixels(minWidth, minHeight, maxWidth, maxHeight, imageWidth, imageHeight) {
    let _minWidth = this.minWidth;
    let _minHeight = this.minHeight;
    return {
        minWidth: _minWidth > 400 ? _minWidth : minWidth,
        minHeight: _minHeight > 400 ? _minHeight : minHeight,
        maxWidth: imageWidth,
        maxHeight: imageHeight
    }
}
```

It looks that it's equal to the following code:
```
resPixels(minWidth, minHeight, maxWidth, maxHeight, imageWidth, imageHeight) {
    return {
        minWidth: minWidth,
        minHeight: minHeight,
        maxWidth: imageWidth,
        maxHeight: imageHeight
    }
}
```

**Comment by itsikhar** [comment]
Cause i'm using custom component to wrap the Cropper I need to get the minWidth and the minHeight from the custom component.

**Comment by Norserium** [comment]
All right, I understand you. May I close the issue?

**Comment by itsikhar** [comment]
Yes, Thank you very much, again :)

**Comment by Norserium** [comment]
You are welcome!
