### ISSUE TITLE
Issue on iOS devices

### ISSUE THREAD

**Issue by KHgul** [Norserium/vue-advanced-cropper#150]
Thanks for the package and great work.

I'm using the package in one of the project. The package is working great on the desktop but having issue on the iOS devices all browsers. 

I have made a demo video who I've used the package and this videos is of laptop. But the issue I'm facing is on the iOS devices the cropper does not work like in the demo video use case if I resize the image less than the crop area it does not draw a proper border as it does in the laptop case.

Working video of Laptop: https://drive.google.com/file/d/1OKr7HGirj2BoTuWUzaRJAfcZ4b4EG-lG/view

This the actual video of the issue on iOS device: https://www.dropbox.com/s/8bt9oshekkwtcq6/RPReplay_Final1628881884.MP4?dl=0

**Comment by Norserium** [comment]
@KHgul, any news?
