### ISSUE TITLE
Issue with image load when the component isn't displayed

### ISSUE THREAD

**Issue by DraftProducts** [Norserium/vue-advanced-cropper#151]
If the src prop of the cropper is changed when the cropper is not displayed, the cropper can't display it and it takes the look of the cropper when no image is provided:

![image](https://user-images.githubusercontent.com/29425008/131511682-8ebe0e29-8042-4130-9b5d-0abfa7d437ed.png)

This can happen when the cropper is accessible from a modal and the cropped image can be changed from outside with a Save/Reset changes buttons.

Here a sandbox with three buttons to understand and test it.
https://codesandbox.io/s/bug-of-src-0rndk?file=/src/App.vue

**Comment by Norserium** [comment]
@DraftProducts, when the wrapper is hidden (`display:none`) its width and its height are equal to `0`, so at start the cropper has `0` height alike. The cropper doesn't know about the changes of its wrapper at all, hence when you open a modal window the cropper size is not recalculated and it's still equal `0`.

For such situations there is [`refresh`](https://norserium.github.io/vue-advanced-cropper/components/cropper.html#refresh) method. It forces the cropper recalculate its height. Look at [the example](https://codesandbox.io/s/bug-of-src-fixed-c4n3w?file=/src/App.vue).

**Comment by Norserium** [comment]
Similar issue: #55

**Comment by DraftProducts** [comment]
Thank you for such a quick response!
It's okay, I'll try this.
Have a nice day!

**Comment by Norserium** [comment]
@DraftProducts, you are welcome!
