### ISSUE TITLE
Still Stencil

### ISSUE THREAD

**Issue by ugurcanalyuz** [Norserium/vue-advanced-cropper#152]
Like on Facebook, I couldn't find anywhere to pin the Stencil and show the background only within the Stencil. Is this available?

**Comment by Norserium** [comment]
@ugurcanalyuz, could you provide the Facebook cropper screenshot? Do you want to achieve something like [the first example](https://norserium.github.io/vue-advanced-cropper/guides/advanced-recipes.html#fixed-stencil)?

**Comment by ugurcanalyuz** [comment]
@Norserium Thank you for your quick reply. I don't speak good English either, sorry for that. Facebook just scrolls the photo up and down within a fixed cutout area. This is exactly what I was looking for.

![image](https://user-images.githubusercontent.com/54191425/132137555-110458c5-91e3-46c0-a6db-e99e7ba4373d.png)

**Comment by ugurcanalyuz** [comment]
@Norserium  Actually your example is very nice, I just couldn't find fixing the photo as a width.

**Comment by ugurcanalyuz** [comment]
@Norserium As you can see, the remaining parts are also visible in this system. Is it possible to hide the outside parts?

![image](https://user-images.githubusercontent.com/54191425/132138187-e0cb0242-c64e-4699-b983-365a67ddc1f6.png)

**Comment by Norserium** [comment]
@ugurcanalyuz, I suppose I understood you. Check [this example](https://codesandbox.io/s/vue-advanced-cropper-facebook-like-uotjf?file=/src/App.vue).

**Comment by ugurcanalyuz** [comment]
@Norserium What level of man are you? You are great! <3 <3

**Comment by Norserium** [comment]
@ugurcanalyuz, thank you! I'm glad to help.

**Comment by ugurcanalyuz** [comment]
Greetings mate, I'm trying to add Radius for your example, but I can't subtract the radius during the demonstration. How can I do this? I couldn't add radius to the existing window :)

`.vue-preview {
  border-radius: 20px !important;
}

.vue-advanced-cropper__foreground {
  background-color: #242424 !important;
  border-radius: 20px !important;
}

.vue-advanced-cropper__image {
  border-radius: 20px !important;
}

.vue-advanced-cropper__background {
  border-radius: 20px !important;
}`

**Comment by Norserium** [comment]
@ugurcanalyuz, hello again! Could you provide the picture of the desired result and your current cropper?

**Comment by ugurcanalyuz** [comment]
Greetings mate. I am attaching the photo as well. Your code works great, I just need to add Radius to the crop area. I will also need to use Radius 100% in the profile photo upload area. I think it would make the same sense.

![image](https://user-images.githubusercontent.com/54191425/134244596-8d0a830d-d509-4458-867c-fd5ac7f69d80.png)

**Comment by ugurcanalyuz** [comment]
@Norserium This is how I actually need to make the crop area. For My Cover Photo.

![image](https://user-images.githubusercontent.com/54191425/134245061-56ca8b87-e404-47df-b246-b798409469ce.png)

**Comment by Norserium** [comment]
@ugurcanalyuz, check [this example](https://codesandbox.io/s/vue-advanced-cropper-facebook-like-rounded-n6iy6?file=/src/App.vue).

**Comment by ugurcanalyuz** [comment]
You are a wonderful man. I hope the library works with Nuxt 3 as well, I'll update it soon :) You're great mate! <3 @Norserium

**Comment by Norserium** [comment]
@ugurcanalyuz, you are welcome! 

Yes, Nuxt 3 finally will be soon in the public beta. And I assume that cropper will work well with it. It's based on Vue 3, and the version of cropper for the latest Vue version was released a long ago, and I assume it's stable now.

**Comment by rich06** [comment]
Thank you for this very useful software!

I am using the fixed stencil technique - based on your code sandbox [](https://codesandbox.io/s/vue-advanced-cropper-facebook-like-rounded-n6iy6?file=/src/App.vue) - however I have 2 instances of the cropper on the page...

A problem occurs when the Vue app calls the .zoom() method which causes a crash with this error - 
`[Vue warn]: Error in v-on handler: "TypeError: can't access property "left", n is null"`

Any ideas on how to fix this?
Thanks!

**Comment by Norserium** [comment]
@rich06, could you reproduce this error in the codesandbox?

**Comment by rich06** [comment]
> @rich06, could you reproduce this error in the codesandbox?

Yes - I edited your code sandbox example by copying the existing cropper to create a second cropper instance and gave both croppers different refs. Then I added v-on:ready event handlers to both instances and in the handler function I called zoom() for both refs and the error I mentioned got logged in the console.

**Comment by Norserium** [comment]
@rich06, could you send me link to your codesandbox?

**Comment by rich06** [comment]
> @ugurcanalyuz

I forked your codesandbox and have shared my version it with your username. Thanks.

**Comment by Norserium** [comment]
@rich06, I assume that the problem happens because one of the cropper isn't ready when you call `zoom` method. Look at [the example](https://codesandbox.io/s/vue-advanced-cropper-facebook-like-rounded-forked-zx4x2v?file=/src/App.vue). But it's recommended to use `default-visible-area` property to set the initial zoom.

**Comment by rich06** [comment]
Okay - thanks for that tip I will look at that prop
