### ISSUE TITLE
Twitter slider flickering if zoomed image size overlaps the min-width/min-height

### ISSUE THREAD

**Issue by allanvb** [Norserium/vue-advanced-cropper#153]
For some reasons, if the cropped images reaches the size closer to cropper's min-width/min-height, it starts flickering.
Is there any way to avoid this behaviour ?

Steps to reproduce:
- Go to original [Codesandbox](https://codesandbox.io/s/vue-advanced-cropper-twitter-suoyc?file=/src/App.vue)
- Change min-width/min-height of **cropper** to `650`
- Drag the slider to right

[GIF](https://s9.gifyu.com/images/vue-advanced-cropper.gif)

**Comment by Norserium** [comment]
@allanvb, it should be fixed now. Thank you for your report.

**Comment by allanvb** [comment]
@Norserium glad to help. Can you tell me please what exactly you changed so I'll be able to fix it in my app too ?

**Comment by Norserium** [comment]
@allanvb, I've changed `onZoom` method. Compare it with your method, you should see the difference in the used formula.

**Comment by allanvb** [comment]
@Norserium got it. It works like a charm. 

I think this can be closed now.

**Comment by Norserium** [comment]
@allanvb, you are welcome!
