### ISSUE TITLE
Paint something into Stencil (Preview) component

### ISSUE THREAD

**Issue by ehernandezColegium** [Norserium/vue-advanced-cropper#155]
Hey @Norserium! Me again 😄 

I'm willing with a requeriment that I saw in another web, and it looks good and interesting to reproduce with vue-advanced-cropper. We are working in a  "template" or "guide" in aras people will able to adjust their avatar photo exactly in the same position where guide is using the Circle Stencil component and its preview component.

![Captura de Pantalla 2021-10-06 a la(s) 5 00 36 p  m](https://user-images.githubusercontent.com/36742655/136289658-713652f8-b766-4c6d-bfd8-57a313760fe2.png)

I have started to read this docs section to accomplish it, but I stuck [in this part](https://norserium.github.io/vue-advanced-cropper/guides/advanced-stencil.html#handler-and-preview). 

Some hints to do it? I want to make a component apart for reusability reason and enable/disable the feature via props.

**Comment by ehernandezColegium** [comment]
Hey @Norserium!

Until now, I was able [to do this](https://codesandbox.io/s/vue-advanced-cropper-custom-stencil-forked-p90il). I was trying to do the ovals into Stencil Preview component (into the tag itself as a default slot), but look like itself doesn't accept default slots.

I fixed Stencil component too to avoid drag, and I painted ovals but with tricky (and messy) css. Responsiveness is awkward too, so it might be nice if you mind any help about how to I can continue here. 

I noted a z-index issue at moment to paint hr tag for vertical and horizontal lines. I know I have some lack of knowledge about css, but maybe with your kindly info about components under hood I could continue with guides into Preview component.

Thanks in advanced.

**Comment by Norserium** [comment]
@ehernandezColegium what's behavior you want to get? Could you provide the example of the stencil with the desired behavior? I don't see any handlers on your image above.

**Comment by Norserium** [comment]
@ehernandezColegium, currently, I don't see that there are cropper specific issues. There are plenty of ways to implement your example by the code. For example, you can use [percentages instead of absolute values](https://codesandbox.io/s/vue-advanced-cropper-custom-stencil-forked-z86ge?file=/src/Stencil.vue).

**Comment by Norserium** [comment]
> Looking your example (pretty nice, dude), I was mind about how do you know the exact percentage for each element. Do you use some "equation" for that or It was just a manual calc?

It was just a fast manual calculations. The basis is the width of the circle on your example. All other dimensions are calculated relative to its size.

For example:
```
relative_width_of_eye = width_of_eye / width_of_circle
```

Where `width_of_eye` and `width_of_circle` are the widths of the corresponding items on your example image.

**Comment by Norserium** [comment]
@ehernandezColegium, you are welcome!

> I don't know if it would be hard, but it might nice a Stencil Preview component slot to paint with css thing into it, just for easy coding

I don't get the idea. Could you explain what do you mean by "paint with css thing into it"?

**Comment by ehernandezColegium** [comment]
Hey @Norserium!

Yeah, I mean, a slot where preview component works like you have solved example above.

**Comment by Norserium** [comment]
@ehernandezColegium, I will think about it, but currently I suppose, that the custom stencil is the most flexible and obvious way to solve such tasks.
