### ISSUE TITLE
Empty FormData object when converting the canvas to Blob

### ISSUE THREAD

**Issue by roenfeldt** [Norserium/vue-advanced-cropper#157]
First off, thank you for this amazing cropper utility and for all the work you 've been doing on improving it.

My ultimate goal is, that I send the image data to a backend API (which is already built and accepting requests properly, but it's irrelevant to this issue).

The problem I'm facing with, is that I can't figure out how to append the cropped image to a FormData object, so that I can further send it over to the API (by the help of a library such as Axios etc.) and store it somewhere.

My code is here:
https://codesandbox.io/s/goofy-https-p2cwj

The relevant part is happening within the `uploadCroppedImage` method, see below:

```javascript
uploadCroppedImage() {
      const { canvas } = this.$refs.cropper.getResult();

      if (canvas) {
        canvas.toBlob((blob) => {
          let formData = new FormData(); // to submit as a "multipart/form-data" request
          formData.append("image-name", blob);

          /**
           * But now I'm getting an EMPTY Object. WHY?!?
           */
          console.log(formData);

          /**
           * And therefore, I can't use Axios or any other library
           * to send the image over to the server.
           */
        });
      }
    },
```
What am I doing wrong?

Thank you so much! :)

**Comment by Norserium** [comment]
@roenfeldt, is the issue still actual?

**Comment by roenfeldt** [comment]
@Norserium as a matter of fact, I'm currently trying to figure out how to actually make use of the actual image data that's included within the iterated FormData object, as per your suggestion. My `uploadCroppedImage` function looks like this now:

```javascript
uploadCroppedImage() {
      const { canvas } = this.$refs.cropper.getResult();

      if (canvas) {
        canvas.toBlob((blob) => {
          let formData = new FormData(); // to submit as a "multipart/form-data" request
          formData.append("image-name", blob);

          /**
           * Getting the object's contents as expected.
           */
          console.log(blob, [...formData]);

          /**
           * And therefore, I can't use Axios or any other library
           * to send the image over to the server.
           */
          axios.post(this.uploadImageEndpoint, {
            /** I believe this is where the problem starts, because by inspecting the XHR request parameters,
            * I'm getting {"cropped_imagel":[["image-name",{}]]}
            */
            cropped_image: (blob, [...formData]),
          })
          .then(response => {
            /* The API will simply return the request input data that was sent, nothing fancy. */
            console.log(response.data); // getting [["image-name",[]]]
          })
          .catch(error => {
            console.log('Error when trying to upload the cropped image: ', error);
          });
        }, "image/jpeg", .90);
      }
    },

```
So my question is now, how could I send the actual image data over to the API?

Many thanks for your help and patience!

**Comment by roenfeldt** [comment]
> @roenfeldt, you are welcome! I assume it will be right to create a separate issue (for the other users). Also, I need the codesandbox to reproduce the error or the video at least.

Sure thing @Norserium - here's the new issue for reference (for users reading this) https://github.com/Norserium/vue-advanced-cropper/issues/158
