### ISSUE TITLE
[NOT a bug] How to disable image zooming on scroll?

### ISSUE THREAD

**Issue by roenfeldt** [Norserium/vue-advanced-cropper#158]
As the issue's title says - I need to disable the image zooming that happens during the scroll event. 

My users find it a bit confusing, that when they are scrolling the page, if the mouse cursor happens to be over the Cropper instance, the image will get zoomed in/out. And therefore I would need the Cropper to stop listening (or at least reacting) to the scroll event. Here's a video where I'm trying to demonstrate what's happening. Using the default "minimal example" on the docs page https://norserium.github.io/vue-advanced-cropper/introduction/getting-started.html#minimal-working-example

https://user-images.githubusercontent.com/60813178/138085092-74b8e191-1f47-4053-b075-06112496d8db.mov

Thank you :)

**Comment by Norserium** [comment]
@roenfeldt, it's easy to solve:
```tsx
<cropper
    :src="src"
    :resizeImage="{ wheel: false }"
/>
```
