### ISSUE TITLE
How to propagate scroll to parent ?

### ISSUE THREAD

**Issue by cimpok** [Norserium/vue-advanced-cropper#159]
Thank you Norserium for this cool component!

What would be the best practice to propagate the scrolling to the parent when the drag reaches the upper/lower limits in the cropper?

I am using the Cropper in a scrollable main div, the cropper when activated is taking up most of the screen area making it difficult to touch and drag the outside area to scroll elsewhere on the website.  I am now leaving a thick margin to allow the user to touch it for scrolling.
Is it possible to watch the event of the stencil or the image dragging stopping at the upper and lower limits and propagate this event to the parent's scrolling method to allow the user scroll away the parent div by dragging the cropper beyond its limits in the vertical direction.
Thank you for any clues.

**Comment by Norserium** [comment]
@cimpok, it's not easy to do. The preventing of event happens before that event will been processed. By the way, what's the version of Vue do you use?

**Comment by Norserium** [comment]
@cimpok, could you take a look at the example in [the another cropper](https://norserium.github.io/react-advanced-cropper/docs/guides/advanced-recipes#scroll-the-cropper) (it's the React library, but anyway). Do you want to achieve the similar behavior? 

If not, could you explain the alternative. For example, the cropper can allow the default event when you can't resize the image anymore. It works good when you scroll down at initial zoom, but it doesn't work when you scroll up.

**Comment by cimpok** [comment]
@Norserium, yes, It's a nice solution, thank you.

The two-fingered scroll operation that obvious for me, (for zooming it is), that's why the on-screen hint, I think this is an elegant solution. 

I observed an interesting positive side effect on my Android tablet running Chrome (at least I don't think it was intended):  if I begin the scroll-up on the last image (with this backgroundwrapper feature) with enough momentum that the inertia-scroll is not stopping until I can touch any next image, I was able to maintain the scrolling forever even when only touching the cropper images without this feature.

I will look at the React code how it is done, would like to implement it in my Vue3 code. Is it a workaround we can do programming in the parent component, or also your Vue component needs some update for this ?

**Comment by Norserium** [comment]
> I will look at the React code how it is done, I would like to implement it in my Vue3 code

It can't be ported easily. This library is the my port of this library to React, that was totally rewritten. I have plans to port it back to Vue, but it will be later.

> Is it a workaround we can do in the parent component, or also your Vue component needs some update for this ?

I will try to figure out something. It's possible. The question is how beautiful it will be, because it will be some sort of a workaround anyway.

**Comment by Norserium** [comment]
@cimpok, I will try to offer some solution in 24 hours. I recommend don't spend time on this task, until this moment.

**Comment by Norserium** [comment]
@cimpok, well, I did port some code from the react library. There is [the sandbox](https://codesandbox.io/s/vue-advanced-cropper-custom-scroll-vue-3-21oqn) to test. The changes are available in `2.7.0` (Vue 3) and `1.9.0` (Vue 2).

**Comment by cimpok** [comment]
Wow @Norserium !   Perfect, thank you.
...and you have even managed to include it in the documentation, (i wish I could solve my coding problems that fast :)

**Comment by Norserium** [comment]
@cimpok, you are welcome! This feature is described in [the documentation now](https://norserium.github.io/vue-advanced-cropper/guides/advanced-recipes.html#scroll-the-cropper) shortly. Additional documentation is required, but it's better than nothing.

**Comment by Norserium** [comment]
@cimpok, is this issue still actual?

**Comment by cimpok** [comment]
@Norserium you mean we can close the issue, sorry I'm quite new in github commenting. Thanks again.

**Comment by Norserium** [comment]
@cimpok, you are welcome! 

That's exactly what I mean. I prefer that an issue creator closes his issue himself once this issue is resolved to prevent any sort of misunderstanding. 

Sometimes, however, I don't get the response and close issue himself.
