### ISSUE TITLE
SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.

### ISSUE THREAD

**Issue by thiagosaife** [Norserium/vue-advanced-cropper#16]
When installed version ^0.12.2, most browsers on early versions of IOs are throwing the error: 
`SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.`
preventing applications to render properly. Is there anybody else facing this same issue?

**Comment by Norserium** [comment]
Hello, @thiagosaife! How do you import this library in your project?

**Comment by thiagosaife** [comment]
Hello @Norserium.

We are importing as a member, like this:
import { Cropper, CircleStencil } from 'vue-advanced-cropper';

**Comment by Norserium** [comment]
@thiagosaife, please update to `0.13.0`.

**Comment by thiagosaife** [comment]
Dear @Norserium 

Thank you very much for being so helpful. Problem solved. Best.

**Comment by Norserium** [comment]
You are welcome!
