### ISSUE TITLE
Mistake in the documentation

### ISSUE THREAD

**Issue by TitouanBizet** [Norserium/vue-advanced-cropper#164]
Hi,
In the [documentation](https://norserium.github.io/vue-advanced-cropper/components/circle-stencil.html), linesWrapperClasses seems to be a mistake. It doesn’t work, however with linesWrappersClasses I have no problem.
Thanks a lot for the library by the way

**Comment by Norserium** [comment]
@TitouanBizet, thank you for your report! 

It's fixed by now. The writing of the documentation consumes pretty much time, so, alas, it's still can contain different mistakes. I only hope that they won't stand on the way of developers. Just like in your case.
