### ISSUE TITLE
Send cropped image to laravel controller

### ISSUE THREAD

**Issue by Jacobtims** [Norserium/vue-advanced-cropper#165]
I can't save my cropped image through my laravel controller.
**Vue code:**
```
uploadImage() {
            const { canvas } = this.$refs.cropper.getResult();
            if (canvas) {
                canvas.toBlob(blob => {
                    const form = new FormData();
                    form.append('file', blob);
                    axios.post(this.route('user.post.create'), form, {
                        headers: {
                            'Content-Type': 'multipart/form-data'
                        }
                    }).then((response) => {
                        console.log(response)
                    }).catch(function (error) {
                        this.toastMiddle('danger', error.response.data.message);
                    }.bind(this));
                }, this.image.type);
            }
        },
```

**In my controller I have this:**

```
public function createPost(Request $request)
    {
        $fileName = time().'.'.$request->file('file')->getClientOriginalExtension();
        $request->file('file')->storeAs('', $fileName, 'user_profiles');
        return response()->json(['success'=>'You have successfully upload file.']);
    }

```

It doesn't give me any error, but just create some random files without extension.
What am I doing wrong?

**Comment by Jacobtims** [comment]
I have tested something more.
I found the problem, and that is that my controller can't get the `getClientOriginalExtension()`.
When I set it manually it works fine!

**Comment by Norserium** [comment]
@Jacobtims, hello!

The method `getClientOriginalExtension` returns the extension based on [the file name](https://laravel.com/docs/8.x/filesystem#other-uploaded-file-information
):
> However, keep in mind that the getClientOriginalName and getClientOriginalExtension methods are considered unsafe, as the file name and extension may be tampered with by a malicious user. For this reason, you should typically prefer the hashName and extension methods to get a name and an extension for the given file upload

**Comment by Jacobtims** [comment]
Thx for your fast reply!
I fixed it with the `$file->extension()`.
I will also create a validation on the image.

**Comment by Norserium** [comment]
@Jacobtims, you are welcome!

**Comment by yellow1912** [comment]
This is greate content, please add it to the document if you can. It will save people like me tons of time digging the old issues.
