### ISSUE TITLE
Canvas undefined when using .getResult()

### ISSUE THREAD

**Issue by edshen17** [Norserium/vue-advanced-cropper#166]
Hello, I was playing around with the [Twitter showcase](https://norserium.github.io/vue-advanced-cropper/guides/showcase.html#twitter) and wanted to get the canvas from getResult(). However, it returns undefined.

Please check this [fork](https://codesandbox.io/s/vue-advanced-cropper-twitter-forked-ccow4?file=/src/App.vue). It's basically the same code, but I print the result in onChange().

I know that the documentation says that this example uses undocumented/unreleased features, but is there any way I can get the canvas, or the cropped image after zoom/movement? My end goal is to construct a blob with canvas.toBlob().

Thanks,
Edwin.

**Comment by Norserium** [comment]
Hello, @edshen17! 

The props `canvas` is `false`, that's the reason why the canvas from `getResult` is undefined.

You can enable canvas, but in this case I recommend to get the result not on change, but on some action. For example, clicking the button `continue`.

See [the second method](https://norserium.github.io/vue-advanced-cropper/guides/recipes.html#getting-the-result) of the getting result.

**Comment by edshen17** [comment]
Thank you for the quick reply! It works now once I set canvas to false.

Ah yes, I was just trying to show that it was undefined since it was easy to do in the onChange method. Thanks again!

**Comment by Norserium** [comment]
@edshen17, you are welcome!
