### ISSUE TITLE
export 'default' (imported as 't') was not found in 'vue' ?

### ISSUE THREAD

**Issue by majaofterra** [Norserium/vue-advanced-cropper#167]
Hello, just installed your lovely component on my laravel 8 project and rightaway  when just importing it i get this error

`export 'default' (imported as 't') was not found in 'vue' `

i am a bit new to vue and my googling seems to indicate its something with your side? 

thanks a lot!

**Comment by Norserium** [comment]
@majaofterra, I need more data. Did you install `vue`? How do you import libraries?

**Comment by majaofterra** [comment]
vue came installed with laravel and i'm dong the single page thing 
```

</template>
<script>
    import { reactive, computed } from 'vue'
    import BreezeAuthenticatedLayout from '@/Layouts/Authenticated.vue'
    import { usePage, Head } from '@inertiajs/inertia-vue3';
    import Swal from 'sweetalert2';

    import { Cropper } from 'vue-advanced-cropper'

    export default {
```

**Comment by Norserium** [comment]
@majaofterra, what's version of `vue-advanced-cropper` do you use?

**Comment by majaofterra** [comment]
"vue-advanced-cropper": "^1.9.0",

**Comment by Norserium** [comment]
@majaofterra, you should use `next` version for Vue 3 (the latest is `2.7.0` by now).

**Comment by majaofterra** [comment]
i see yeah that makes sence, i wonder why npm installed outdated version. 

sorry i am too new to vue and npm care to offer any advice on how i would do this?

**Comment by Norserium** [comment]
> i see yeah that makes sence, i wonder why npm installed outdated version.

The NPM package manager by default installs the version with tag `default`, an it's `1.9.0` now. This version is not outdated, but this version is supposed to use with Vue 2, that is still actual.

To support two versions of Vue simultaneously I use two tags for versions: `default` (Vue 2) and `next` (Vue 3). It's described in the documentation.

**Comment by Norserium** [comment]
To install the specific version you should use:
```bash
npm install --save vue-advanced-cropper@next
```

**Comment by Norserium** [comment]
@majaofterra, did you solve your problem?

**Comment by majaofterra** [comment]
howzit mate, soo sorry for very late reply, yes i got it sorted and super!
thanks so much it was the last day before a big hike!

**Comment by Norserium** [comment]
@majaofterra, you are welcome! I close the issue then.

**Comment by majaofterra** [comment]
thank you very much!
