### ISSUE TITLE
this.$refs.cropper.setCoordinates is not a function

### ISSUE THREAD

**Issue by guias12** [Norserium/vue-advanced-cropper#17]
I'm trying to use the setCoordinates function just like the <a href="https://norserium.github.io/vue-advanced-cropper/tutorials/recipes.html#set-coordinates">documentation</a> shows. But i'm getting the "is not a function" error on the console. It was deprecated? 

I'm using the vue-advanced-cropper on ^0.8.3 version.

There's another way of setting the coordinates programmatically?

**Comment by Norserium** [comment]
Hello, @guias12! Update to `0.13.0` version.
