### ISSUE TITLE
disable zoom?

### ISSUE THREAD

**Issue by zynth17** [Norserium/vue-advanced-cropper#175]
is there any way to set the default zoom and prevent the user to zoom the image?
can't find anything on the docs

**Comment by Norserium** [comment]
@zynth17, zoom is actually just the high level abstraction of changing the visible area. 

So, you can set the default visible area to get the default zoom. 

To prevent the possibility to zoom image by an user you can block image resize events by setting `:resize-image="false"`.

There is [the example](https://codesandbox.io/s/small-feather-jg2np?file=/src/App.vue).

But I'm curious, what is the use case for it? I slightly can imagine why do you need it.

**Comment by zynth17** [comment]
> @zynth17, zoom is actually just the high level abstraction of changing the visible area. 
> 
> 
> 
> So, you can set the default visible area to get the default zoom. 
> 
> 
> 
> To prevent the possibility to zoom image by an user you can block image resize events by setting `:resize-image="false"`.
> 
> 
> 
> There is [the example](https://codesandbox.io/s/small-feather-jg2np?file=/src/App.vue).
> 
> 
> 
> But I'm curious, what is the use case for it? I hardly can imagine why do you need it.

thanks! i will try it later. 
the case is, i want the user to upload an image, without restricted dimension.
but i need to set the picture to have max width to make all the image have the same width while they are cropping and also the cropper itself has a fixed size of 200x200 px so i dont want the user to zoom on the picture. the default zoom is for making the image visible in all area because of the zoom prevention

**Comment by Norserium** [comment]
@zynth17, I'm not sure, but did you consider for your use-case [the result resizing](https://norserium.github.io/vue-advanced-cropper/guides/recipes.html#resize-the-result)?

**Comment by Norserium** [comment]
@zynth17, consider the following use-case. 

User uploads his own photo (683px / 1024px).
![image](https://user-images.githubusercontent.com/9862719/150531308-ad3fd194-59bc-4f04-afec-cb8fb40a14cd.png)

He want to choice the selected area on the left image, but if you limit the choice to size 200x200 he will be able to select the area like on the right image.

It seems, that you shouldn't limit the size of the cropped area, you should scale the result to the needed size. But it's up to you, of course.

**Comment by zynth17** [comment]
> @zynth17, consider the following use-case. 
> 
> 
> 
> An user uploads the photo (683px / 1024px).
> 
> ![image](https://user-images.githubusercontent.com/9862719/150531308-ad3fd194-59bc-4f04-afec-cb8fb40a14cd.png)
> 
> 
> 
> He want to choice the selected area on the left image, but if you limit the choice to size 200x200 he will be able to select the area like on the right image.
> 
> 
> 
> It seems, that you shouldn't limit the size of the cropped area, you should scale the result to the needed size. But it's up to you, of course.

thanks! i will consider this. one more question. is there any way to make the image have max height? i try to wrapping the cropper element on a div and giving the div a max height but the image still overflowing the parent div.

**Comment by Norserium** [comment]
@zynth17, I need more information (the codesandbox would be perfect), but try to set the max height for the cropper itself.

**Comment by zynth17** [comment]
> @zynth17, I need more information (the codesandbox would be perfect), but try to set the max height for the cropper itself.

hey thankyou for the help! i will close this issues since this is already done now.

**Comment by Norserium** [comment]
@zynth17, you are welcome!
