### ISSUE TITLE
Lazy load

### ISSUE THREAD

**Issue by qxygene** [Norserium/vue-advanced-cropper#177]
const Cropper = () =>
  import(/*webpackChunkName: "cropper"*/ "vue-advanced-cropper");

It seems not working.

**Comment by qxygene** [comment]
const Cropper = () =>
  import(/*webpackChunkName: "cropper"*/ "vue-advanced-cropper").then(
    (module) => {
      console.log(module);
      return module.Cropper;
    }
  );

now it works.

**Comment by Norserium** [comment]
@qxygene, hello! 

It's the normal behavior. The explanation is pretty simple:
1. The [`import`](https://webpack.js.org/api/module-methods/#import-1) dynamically load **a module**, not one of named exports. Therefore to get the named export `Cropper` you need to process the promise result:
```ts
const Cropper = () =>
   import(/*webpackChunkName: "cropper"*/ "vue-advanced-cropper").then(module => module.Cropper)
```
2. The result of the code above is the literally [`async component`](https://vuejs.org/v2/guide/components-dynamic-async.html#Async-Components). The function that returns Promise whose value is the component options. So you can just pass it to the components list:
```ts
{
    /* ... */
    components: {
       Cropper
    }
}
```

**Comment by Norserium** [comment]
@qxygene, is your issue still actual?

**Comment by qxygene** [comment]
yes it is

**Comment by Norserium** [comment]
@qxygene. what's wrong? The example above should work.

**Comment by Norserium** [comment]
@qxygene, any news?

**Comment by qxygene** [comment]
version 1.10.1 fixed the issue. thank you.

**Comment by Norserium** [comment]
@qxygene, frankly, I don't get how it could solve your issue, but all is well that ends well. 

I close issue then.
