### ISSUE TITLE
Getting NaN on positional arguments after using setCoordinates()

### ISSUE THREAD

**Issue by guias12** [Norserium/vue-advanced-cropper#18]
Hi, I'm using the setCoordinates function on a image that contains an object which I already know the position.

The problem is that after I use the function, the positional arguments(left and top) are both returning NaN as value, the size arguments(width and height) are being seated correctly.

After that the image and the cropper starts to have a strange behave, like in the print.
![cropper](https://user-images.githubusercontent.com/38231441/67703882-e9872380-f992-11e9-8722-c90cf667fc02.png)

this is the code I'm using:

`this.$refs.cropper.setCoordinates({
  width: response.data.box.width,
  height: response.data.box.height,
  left: response.data.box.left,
  top: response.data.box.top
});`

I'm also attaching a print of the console error

![error](https://user-images.githubusercontent.com/38231441/67703883-e9872380-f992-11e9-901c-befae1b82d63.png)

Is it somenthing I did wrong? I couldn't find anything like this in the issues or in the docs.
Do you know how I can fix this?

**Comment by Norserium** [comment]
Could you output `response.data` in the console and send a screenshot to me?

**Comment by guias12** [comment]
sure
![response](https://user-images.githubusercontent.com/38231441/67706412-792ed100-f997-11e9-9700-feb653268d62.png)

**Comment by guias12** [comment]
This is the whole function code:
```
public capturarImagem() {        
        this.boxes = [];
        axios.get(url).then(response => {            
            this.srcImagemCrop = this.baseApiUrl + response.data.path;           
            this.fotoCapturada = true;
            this.hash = response.data.hash;

            if(response.data.box){                
                this.$refs.cropper.setCoordinates({
                    width: response.data.box.width,
                    height: response.data.box.height,
                    left: response.data.box.left,
                    top: response.data.box.top
                });
                //console.log(response.data)
            }            
        }).catch(e => {
            this.srcImagem = this.srcImagemErro;
            this.fotoCapturada = false;
            console.log(e)
        });
    }

```
As soon as the user clicks on the "Capture Image" button on the screen, I make a request to the server-side to save the image and do the processing to get the object position.
That's how I get the coordinates in the response and after that I'm trying to set them on the croppper

**Comment by Norserium** [comment]
Is `this.srcImagemCrop` passed to `src` prop of the cropper?

**Comment by guias12** [comment]
yes

**Comment by Norserium** [comment]
I assume there's the problem. Image is loaded after you set coordinates, so cropper operates undefined values during setting coordinates and you get `NaN`.

**Comment by Norserium** [comment]
Me need to think, what's the best solution of this problem (create an event `onLoad`, delay calls of `setCoordinates` or etc.)

Currently you can try to use the following solution.

```js
axios.get(url).then(response => {            
            this.image = {
                  src: this.baseApiUrl + response.data.path,
                  defaultCoordinates: response.data.box,
            }
            this.fotoCapturada = true;
            this.hash = response.data.hash;
        }).catch(e => {
            this.srcImagem = this.srcImagemErro;
            this.fotoCapturada = false;
            console.log(e)
        });
```

Add the new methods `defaultSize` and `defaultPosition`:
```ts
public defaultSize({imageWidth, imageHeight}) {
       return this.image.defaultCoordinates || {
            width: imageWidth * 0.8,
            height: imageHeight * 0.8
       }
}
```
```ts
public defaultPosition({imageWidth, imageHeight, stencilWidth, stencilHeight}) {
       return this.image.defaultCoordinates || {
               left: imageWidth / 2 - stencilWidth / 2,
               top: imageHeight / 2 - stencilHeight / 2,
       }
}
```

And pass them to `default-size` and `default-positions` props accordingly.

I didn't test it yet, but it should work.

**Comment by Norserium** [comment]
Or as an option you can update to `0.13.1`. The cropper now remember the last transforms that you apply after an image was changed and before one will be loaded and apply them right after an image finally have been loaded (without flickering due the flexible approach).

**Comment by guias12** [comment]
Updating to `0.13.1` fixed the problem!

Thank you a lot mate.
