### ISSUE TITLE
Image dimentions are not correct.

### ISSUE THREAD

**Issue by ijunaid8989** [Norserium/vue-advanced-cropper#180]
I am trying to load vuejs cropper with a binary image such as

```
{src: 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD…phoAcnfPrThTU6H604daAEJpppTTe1MBV70E0L3pO1ID/2QAA', width: 1920, height: 1080, transforms: {…}}
height: 1080
src: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAA
transforms: {rotate: 0, flip: {…}, translateX: 0, translateY: -0.25000000000000616, scaleX: 0.49583333333333335, …}
width: 1920

```

as a result of an API request.

when I download the actual Image and check the dimensions it says

![image](https://user-images.githubusercontent.com/13561999/154856517-dabe4e0b-de0d-4c6d-ac44-632431dd0360.png)

while the image object in 

`change({ coordinates, image }) {`

says: 

height: 1080
width: 1920

Am I missing something? 

I am adding the actual Image as well.

![here](https://user-images.githubusercontent.com/13561999/154856544-6db917ed-c57d-4373-a12b-2d8730ea8ad2.jpg)

**Comment by Norserium** [comment]
@ijunaid8989, could you create [the sandbox](https://codesandbox.io/s/vue-avanced-cropper-basic-jfy5w?file=/src/App.vue), that reproduces your issue? I can't reproduce it right now with this image.  Image has `3840` width and `2160` height.

**Comment by Norserium** [comment]
@ijunaid8989, any news?

**Comment by Norserium** [comment]
@ijunaid8989, any news?

**Comment by ijunaid8989** [comment]
Hi, sorry for the delay but you can close the issue now because I have stop working on that issue in the actual repository where I was trying to be create the feature.
