### ISSUE TITLE
unable to use setCoordinates method

### ISSUE THREAD

**Issue by giedriusStan** [Norserium/vue-advanced-cropper#181]
I have never worked with vue before and probably I'm just using the app wrong, but if I try to execute setCoordinates function, I get an error "Uncaught TypeError: Cannot read properties of undefined (reading 'setCoordinates')". This is my code:

https://jsfiddle.net/8hqs9fyj/

is this a bug, or am I missing something?

**Comment by Norserium** [comment]
@giedriusStan, you didn't set the `ref` property at the cropper. [The fixed example](https://jsfiddle.net/q714ngo6/). 

But, frankly, you have a lot of strange things here. What do you want to get?

**Comment by giedriusStan** [comment]
Thank you! This is it! This jsfiddle was taken from documentation page here
https://norserium.github.io/vue-advanced-cropper/introduction/getting-started.html#using-cdn
I just added the resize part

**Comment by Norserium** [comment]
> I just added the resize part

@giedriusStan, if you want to set the default coordinates it's recommended to use `default-position` and `default-size` properties. Also, if you indeed want to create the resizing method, I assume it shouldn't be the global application method.
