### ISSUE TITLE
Cropper does not show in Modal until window is resized

### ISSUE THREAD

**Issue by depressedpsychiatrist** [Norserium/vue-advanced-cropper#182]
I am using bootstrap modals. When I refresh the page and open the modal the copper doesn't show. But when I resize the window in some way; like resizing the inspect element window or maximizing chrome, the cropper then shows up. If I close the modal then and reopen, the cropper will show.

![vue-advanced-croper-modal](https://user-images.githubusercontent.com/62022057/157765482-8578c931-cde7-466e-8123-ee4b4a23bd62.gif)

Here is the sandbox for it: https://codesandbox.io/s/morning-night-9nl2v9?file=/src/components/HelloWorld.vue

**Comment by Norserium** [comment]
@depressedpsychiatrist, hello! 

1. When the external container has `display:none` the cropper can't set own size properly. 
2. When you resize the window, it calls `cropper.refresh` method internally, it recalculates the size of cropper.

You can call this method on your own when modal is opened (i.e. the container is visible). [The example](https://codesandbox.io/s/distracted-sky-rns17n?file=/src/components/HelloWorld.vue).

**Comment by depressedpsychiatrist** [comment]
Thanks for the quick reply.

**Comment by depressedpsychiatrist** [comment]
Thanks for the quick reply.
