### ISSUE TITLE
Reset Cropper

### ISSUE THREAD

**Issue by chemoral87** [Norserium/vue-advanced-cropper#19]
i use the input file upload image, but when i set image = null, it remains the size of the square vue-advanced-cropper__image, what is the propper manner to reset the vue-advanced-cropper__area, vue-advanced-cropper__stretcher to width auto

**Comment by Norserium** [comment]
Hello, @chemoral87! Could you check "Upload image" example [here](https://norserium.github.io/vue-advanced-cropper/tutorials/recipes.html#upload-image)? I've uploaded the changes to the documentation, and if the result satisfies you I will publish the new version.

**Comment by chemoral87** [comment]
Thanks, i can see the icon refresh in upload example, but i need the snippet of code to do via javascript, where i can find??

**Comment by Norserium** [comment]
This button just sets `this.image = null`. The difference is in the used version, in the documentation I've used not published version.

Now I've published `0.13.2`, so you can update to this version to solve your problem.

**Comment by Norserium** [comment]
@chemoral87, is your problem solved?

**Comment by Norserium** [comment]
@chemoral87, I close the issue. Feel free to open if you encounter this problem again.
