### ISSUE TITLE
Module '"vue-advanced-cropper"' has no exported member 'TransformableImage'.ts(2305)

### ISSUE THREAD

**Issue by artemaminov** [Norserium/vue-advanced-cropper#194]
**Module '"vue-advanced-cropper"' has no exported member 'TransformableImage'**

    <script setup lang="ts">
    import debounce from "debounce";
    import { TransformableImage } from "vue-advanced-cropper";
    ...

Or **'default' is not exported by node_modules/vue-advanced-cropper/dist/index.esm-bundler.js** if

    <script setup lang="ts">
    import debounce from "debounce";
    import TransformableImage from "vue-advanced-cropper";
    ...

**Comment by Norserium** [comment]
@artemaminov, what's version of `vue-advanced-cropper` do you use?

**Comment by artemaminov** [comment]
"vue-advanced-cropper": "^2.8.1",

**Comment by artemaminov** [comment]
I'm new to TS and JS and did fixed that issue creating vue-advanced-cropper.d.ts file and included it from tsconfig.json

    import { TransformableImage } from "vue-advanced-cropper";
    module 'vue-advanced-cropper' {
      export declare const TransformableImage;
    }

Is it correct?

**Comment by Norserium** [comment]
@artemaminov, actually you have found the bug in the typings.

Try to remove this fragment:
```
module 'vue-advanced-cropper' {
  export declare const TransformableImage;
}
```

And update to `2.8.2`.

**Comment by artemaminov** [comment]
It's pass now. Thank you for the great work and lightning fast respond!

**Comment by Norserium** [comment]
@artemaminov, you are welcome!
