### ISSUE TITLE
not working on mobile

### ISSUE THREAD

**Issue by lastlink** [Norserium/vue-advanced-cropper#195]
* used base64 image, if screen too small then cropper doesn't work. appears fine, but can't drag it anywhere.
* using iphone se

**Comment by Norserium** [comment]
@lastlink, could you provide the video of bug reproducing?

**Comment by Norserium** [comment]
@lastlink, do you have the similar issue when you use a link to an image or upload it via blob?

**Comment by lastlink** [comment]
I render the image as base64 after uploading. (but not submitted to the server yet). I was able to replicate it in the browser by changing to screen size to be much smaller. idk if there is an auto size canvas issue if it's too small.

**Comment by lastlink** [comment]
I figured out the issue, when the screen was smaller and I opened the inspect page there was a div from bootstrap that was covering the cropper causing the drag to fail and not be clickable. By moving the cropper to the bottom of my form and removed this issue.

**Comment by Norserium** [comment]
@lastlink, all is well that ends well.
