### ISSUE TITLE
cropper.reset not reseting rotation & flip done prior

### ISSUE THREAD

**Issue by darkylmnx** [Norserium/vue-advanced-cropper#198]
I'm doing some tests and the reset method on the cropper does not reset the rotation nor the flip.

**Comment by Norserium** [comment]
@darkylmnx, try to update to `1.11.0`.

**Comment by lucianobosco** [comment]
Any fast fix for Vue 3?

**Comment by Norserium** [comment]
@lucianobosco, it's fixed in `2.8.3` now also.

**Comment by lucianobosco** [comment]
> @lucianobosco, it's fixed in `2.8.3` now also.

Tested and working. You rock!

**Comment by Norserium** [comment]
@lucianobosco, you are welcome!

**Comment by darkylmnx** [comment]
@Norserium sorry for the late response, I fell pretty sick. Yes it seems everything is fine in 1.11.1

**Comment by Norserium** [comment]
> I fell pretty sick.

@darkylmnx, I wish you a speedy recovery!
