### ISSUE TITLE
default size/position and aspect ratio not respected

### ISSUE THREAD

**Issue by mms-** [Norserium/vue-advanced-cropper#2]
Should this be working: https://jsfiddle.net/jt58ogf6/

**Comment by Norserium** [comment]
Hello! 

It's not exactly the problem of the current library, it's specific of [passing props to Vue components](https://vuejs.org/v2/guide/components-props.html).

> HTML attribute names are case-insensitive, so browsers will interpret any uppercase characters as lowercase. That means when you’re using in-DOM templates, camelCased prop names need to use their kebab-cased (hyphen-delimited) equivalents:

So you should change the props names and you will get that you want
https://jsfiddle.net/norserium/0pmsowq1/

I've updated the documentation to make this aspect more clearly

**Comment by mms-** [comment]
Of course, thanks!
