### ISSUE TITLE
Question: Crop with fill

### ISSUE THREAD

**Issue by scheMeZa** [Norserium/vue-advanced-cropper#20]
Hello,

Let's say I have an image 320x500.

I'd like to allow a crop with aspect ratio 1:1 - so that the picture when done cropping is always square.

But I'd like to allow the crop to go all the way to 500x500; so that the crop is bigger than the image, and then the background to be filled with white.

Is there a solution for this?

**Comment by Norserium** [comment]
Hello, @scheMeZa. Currently this cropper doesn't support it.

**Comment by scheMeZa** [comment]
Thanks for your hasty reply :)

It's a feature I'd love to see.

Thank you for your work on this package; It's currently in use in production on https://onebid.co.za

**Comment by Norserium** [comment]
It's great! I'm always glad to hear about using this library in production.

**Comment by Norserium** [comment]
Hello, @scheMeZa! Could you illustrate the situation, where this feature will be useful?

**Comment by NikitaKA** [comment]
I'm using this lib to crop logo which will be uploaded to my Apple Wallet generator. Problem is that inside Wallet app logo is covering whole space by default, even if there is something on the right side - it overlapping it.

![image](https://user-images.githubusercontent.com/2543427/70631473-45092a00-1c3e-11ea-9c41-94caba20276f.png)

So I need to zoom it out a little bit and add transparent space on the right in Photoshop to make it to work.

[Vue CropperJS](https://agontuk.github.io/vue-cropperjs/) has ability to zoom out and add some space around.

**Comment by Norserium** [comment]
@NikitaKA, thank you for your example.

**Comment by Norserium** [comment]
@scheMeZa , @NikitaKA ,  I'm happy to report that this feature is in the alpha stage. You currently can test it in [the documentation](https://norserium.github.io/vue-advanced-cropper/tutorials/recipes.html#different-image-restrictions) (different image restrictions section).

**Comment by NikitaKA** [comment]
> @scheMeZa , @NikitaKA ,  I'm happy to report that this feature is in the alpha stage. You currently can test it in the documentation (different image restrictions section).

You are awesome, thank you!

**Comment by Norserium** [comment]
> How do you think when this feature will be available? smiley

I suppose within a week. It should be tested more carefully.

**Comment by Norserium** [comment]
@scheMeZa, @NikitaKA, please update to `0.15.0` version.

**Comment by Norserium** [comment]
I close this issue. If you encounter any problems, please create the corresponding issue.
