### ISSUE TITLE
Set Aspect Ratio

### ISSUE THREAD

**Issue by sstenn** [Norserium/vue-advanced-cropper#21]
Is it possible to change the aspect ratio?

    stencil () {
      console.log(this.ratio)
      return {
        aspectRatio: this.ratio[0] / this.ratio[1],
        handlers: {
          eastNorth: true,
          north: false,
          westNorth: true,
          west: false,
          westSouth: true,
          south: false,
          eastSouth: true,
          east: false
        }
      }
    }

When I change `this.ratio` the `console.log` is triggered, but the cropper is not updated. 

I tried to fire the `.update()` but it isn't working

**Comment by Norserium** [comment]
Hello, @sstenn! 

It's quite possibly, that cropper doesn't react at changes of stencil props. I'm still working at the development of listeners.

Could you call `resetCoordinates` on change of `this.ratio` now?

**Comment by sstenn** [comment]
@Norserium 

Thanks for your quick response. 

It is workable for now! I've had to set a timeout for this to work, but I'm not sure why

     this.ratio =[1,1]
     setTimeout(function () {
       this.$refs.cropper.resetCoordinates()
     }, 0)

Else it would change to the previous value

**Comment by Norserium** [comment]
You can use `Vue.nextTick` instead of `setTimeout`. It's needed because the changes of ratio actually applied only in the end of tick.

It's workaround and I will notice you when I fix this bug.

**Comment by sstenn** [comment]
@Norserium 

Thanks!

**Comment by Norserium** [comment]
@sstenn, this bug is fixed in `1.4.1`. Please update to this version and check if you can get rid of that workaround.

**Comment by sstenn** [comment]
@Norserium Thanks! It works :)
Great cropper btw. Keep up the good work!

PS. I think you mean version `0.14.1`

**Comment by Norserium** [comment]
Yes, I mean this version, of course.

You are welcome!
