### ISSUE TITLE
How do I limit the maximum height of the entire screenshot area?

### ISSUE THREAD

**Issue by bertms** [Norserium/vue-advanced-cropper#22]
When the picture height is too high, I want to set the maximum height of the entire area. Is there an interface for this?

Screenshot
http://h.pz.com/u/7875/44/5/157484391773.jpg

**Comment by Norserium** [comment]
Hello, @bertms! Do you want to set default size equal to image size and width?

**Comment by bertms** [comment]
hi Norserium 
> Do you want to set the default size equal to an image size and width?

**Comment by Norserium** [comment]
I don't see the answer.

**Comment by bertms** [comment]
HI Norserium ,

I want to set the size of the entire area.
http://h.pz.com/u/7875/46/1/157484519757.png

> Hello, @bertms! Do you want to set the default size equal to an image size and width?

**Comment by bertms** [comment]
> hi Norserium
> 
> > Do you want to set the default size equal to an image size and width?

When the picture height is too high, it cannot be displayed completely. Can I set the maximum height?

**Comment by bertms** [comment]
> > hi Norserium
> > > Do you want to set the default size equal to an image size and width?
> 
> When the picture height is too high, it cannot be displayed completely. Can I set the maximum height?

http://h.pz.com/u/7875/46/2/157484536597.png

**Comment by Norserium** [comment]
Do you want to fit all image in the square stencil (that have `aspectRatio` equals `1`) completely? But it will lead to appearing of the transparent columns around the edges.

**Comment by bertms** [comment]
> I'm sorry, but I still don't understand what you want to get.
> 
> Do you want to fit all image to the square stencil (that has `aspectRatio` equals `1`) completely? But it will lead to appearing of the transparent columns around the edges.

Thank you very much, I have found a way, I control the width and height of the parent DOM of the screenshot component.

**Comment by Norserium** [comment]
I'm glad that you solve it. 

I close the issue then.
