### ISSUE TITLE
Rotate image 

### ISSUE THREAD

**Issue by GhaniHaa** [Norserium/vue-advanced-cropper#24]
how to rotate image and the result too ?

**Comment by Norserium** [comment]
Hello, @GhaniHaa! 

Do you want to rotate an image inside the cropper or rotate the result will be enough?

**Comment by GhaniHaa** [comment]
both of them, it is possible ?

**Comment by Norserium** [comment]
Unfortunately, it's not supported now native, but maybe I will implement this feature in the future.

Now you can use perhaps not efficient, but working approach, that is illustrated at this [example](https://codesandbox.io/s/pensive-aryabhata-9nfls).

**Comment by GhaniHaa** [comment]
Thanks for your help mate.

anyway nice pic

**Comment by Norserium** [comment]
You are welcome!

**Comment by Norserium** [comment]
@GhaniHaa, the native rotation was added in `0.19.0`. [The rotate / flip example](https://norserium.github.io/vue-advanced-cropper/guides/advanced-recipes.html#rotate-flip-image).

**Comment by Lejla94** [comment]
Hello Norserium.
I got a picture that i flip with:
`this.$refs.cropper.flip(true, false);`
but when the user changes the route or the picture the image is not flipped on the same way.
So it was once flipped and it should be shown flipped on these conditions.
It should persist.
On my use case i have a preview that stays flipped, but the cropper not and it confuses.
Thanks.

Is there an attribute for this use case?

**Comment by Norserium** [comment]
@Lejla94, could you provide [the codesandbox](https://codesandbox.io/s/vue-avanced-cropper-basic-jfy5w) that reproduces your issue?

**Comment by Lejla94** [comment]
@Norserium 
Look at this [sandbox](https://codesandbox.io/s/vue-advanced-cropper-preview-experimental-forked-grr9j?file=/src/App.vue)
when the aspect ration is not 1 (one) the Preview does not show well!!
I want to keep the aspect ratio on the preview too, by setting only width on css or the element.
Thanks.

**Comment by Lejla94** [comment]
Is there a way to use `object-fit: contain;` on the image?

**Comment by Norserium** [comment]
@Lejla94, if I understand you correctly, do you want to get something like [this](https://codesandbox.io/s/vue-advanced-cropper-preview-experimental-fixed-qznxx?file=/src/App.vue)?

**Comment by Norserium** [comment]
@Lejla94, if I understood you correctly, do you want to get something like [this](https://codesandbox.io/s/vue-advanced-cropper-preview-experimental-fixed-qznxx?file=/src/App.vue)?

**Comment by Lejla94** [comment]
Yes, but the aspect ratio will change and the Preview should keep it

**Comment by Lejla94** [comment]
The aspect ratio changes based on the user input values, then the user chooses a part of the cropper that will reflect in the Preview.
So the Preview will keep a max width and `object-fit: contain;` so it will scale to fit the max size, but keeping aspect ratio.

**Comment by Norserium** [comment]
@Lejla94, let's do it step by step. You can pretty easy set the `width` and `height` in the template. [The example](https://codesandbox.io/s/vue-advanced-cropper-preview-experimental-fixed-dynamic-aspect-ratio-ek0ju?file=/src/App.vue).

**Comment by Lejla94** [comment]
I tried this before, so the only issue is i can not change the Preview with breakpoints.
I should keep a variable as max size.
But if i find no solution, i will scale it on the css or something to make it look bigger on PC and let 320 on small devices.
Thanks for your effort, if there is someway i could help tell me. (by contributing to the project)

**Comment by Lejla94** [comment]
I am trying that now.
Thanks
