### ISSUE TITLE
Validate the image height and width

### ISSUE THREAD

**Issue by zefexdeveloper** [Norserium/vue-advanced-cropper#25]
I want the user to select an image that will be cropped on the aspect ratio of `2:3` (vertical image), this crop will be sent to the backend to be resized. The question I have is: how can I validate the image the user selected so he can't select an image that is too small to be cropped as `2:3` or even on the minimum width `570px` for example?
The backend will also this `570px` width image with the `2:3` aspect ratio and make other variants like 50% smaller and so on.

**Comment by Norserium** [comment]
Hello, @zefexdeveloper!

 I suppose, that this checking should be performed before changing the `src` prop of the cropper. But anyway, what the cropper should do with such images?

**Comment by zefexdeveloper** [comment]
@Norserium Perhaps you are right, this checking should be done before passing the image to cropper. How am I supposed to lock cropper to `2:3` aspect ratio and `570px` minimum width?
I read somewhere that you said it's not possible to resize the image with cropper and it's totally understandable, that is why I want to validate the image, to make sure it has the required image width before the cropping, then setting the minimum crop area for `570px` is guarantee that the backend will always have an image that is at least `570px` width and `2:3` aspect ratio. There I can resize for all the sizes I need.

**Comment by zefexdeveloper** [comment]
And by the way, such a fast response, you rock, keep up the good work.

**Comment by Norserium** [comment]
> How am I supposed to lock cropper to 2:3 aspect ratio and 570px minimum width?

Did you see [this example](https://norserium.github.io/vue-advanced-cropper/tutorials/recipes.html#custom-restrictions) (custom restrictions)?

> And by the way, such a fast response, you rock, keep up the good work.

Thank you!

**Comment by zefexdeveloper** [comment]
@Norserium Thank you for the answers.

Before closing the issue I'd like to ask you a question regarding the best technique to create a component I want.

I want to create a component where the user can click on a button to select an image, when he selects a modal appears with the image he selected, crop and then the image will appear on the gallery, those images will be sent later to the backend using axios.

What you think is the best way to make this interaction between the button, the modal and the cropper and the gallery?

![image](https://user-images.githubusercontent.com/30276092/70561070-921acc80-1b68-11ea-82a1-17478afd6eaf.png)

**Comment by Norserium** [comment]
> @Norserium Thank you for the answers.

Did they help you?

> What you think is the best way to make this interaction between the button, the modal and the cropper and the gallery?

It depends. 

At the first blush, if you don't use the global state, you can use the approach that is described below:
1. The main component  `Gallery` contains the cropped images in the state and have the method, that uploads them to your backend.
2. The `ModalCropper` that contains the cropped image and have at least two props: image and submit callback, that will receive the cropped image.

So when an user selects image, you open modal and pass the image to it. After image was cropped, user press the submit button click and the callback will be called and one will add the cropped image to the gallery state.

**Comment by zefexdeveloper** [comment]
> Did they help you?

Yes, the example you mentioned is what I was looking for. I couldn't set the aspect ratio `2:3` tho. I tried `2;3`, `2/3` and none of them seems to work.

> The `ModalCropper` contains the cropped image and have at least two props: image and submit callback, that will receive the cropped image as parameter and add it to the state of the previous component.

I didn't get this one. You mean something like `<modal-cropper @onCrop="addToGallery"></modal-cropper>` - This is what I thought about the `submit callback`.

> So when an user selects image, you open modal and pass the image and the callback to it. After the image was cropped, an user press the submit button, modal closes and the callback will be called. This callback will add the cropped image to the gallery state.

The user selection of the image has to be on the `Gallery` component right? I needs to be an input with an event that will load and pass it to the modal as prop.

Tell me if I got this wrong.

**Comment by Norserium** [comment]
> Yes, the example you mentioned is what I was looking for. I couldn't set the aspect ratio 2:3 tho. I tried 2:3, 2/3 and none of them seems to work.

There should not be the fields for minimum and maximum aspect ratios in this example, it's the accidental result of my internal tests. Anyway, you can write 0.667 in that field and you will get the needed result.

I will answer the other part of your questions a little bit later

**Comment by zefexdeveloper** [comment]
@Norserium Thank you for the answers. The `0.667` worked. I will be waiting for your answer and in the mean time I will try to create something using codesandbox.

**Comment by Norserium** [comment]
@zefexdeveloper , there is the [simple example](https://codesandbox.io/s/vue-avanced-cropper-basic-5i429). I've chosen the other logic, but it's pretty similar. But in practice there is no silver bullet, and I can't offer the optimal solution for your project unless I don't see its source code and architecture.

**Comment by zefexdeveloper** [comment]
Your example is exactly what I needed.
As I mentioned on my earlier comment that I was going to be trying something on codesandbox and this is what I did: https://codesandbox.io/s/gallery-crop-rnk26

Of course it's not pretty, the idea was to make it work but I will be using Tailwindcss to make it look cool.

I will be checking your code and seeing what is different from mine and adapt, if you find something on mine and you want to point it out, I will appreciate.

**Comment by Norserium** [comment]
We just used different approaches, there are no better or worse ones. I've encapsulated the cropping in the `Uploader` component, at the same time you add cropping to the gallery and just wrapped `Cropper` in modal.

If you need to use cropper modal in different contexts, than uploading (for example, to recrop some images), your approach is more suitable.

**Comment by zefexdeveloper** [comment]
At the end it worked just fine and your component is awesome. Thank you for everything and for giving your time to help me with this. Keep up the good work and you are going to conquer a lot.

See you.

**Comment by Norserium** [comment]
You are welcome! Good luck!

**Comment by Norserium** [comment]
> I read somewhere that you said it's not possible to resize the image with cropper

@zefexdeveloper, just for your information, it's [possible now](https://norserium.github.io/vue-advanced-cropper/guides/recipes.html#resize-the-result).
