### ISSUE TITLE
Set aspect ratio based on the image orientation

### ISSUE THREAD

**Issue by zefexdeveloper** [Norserium/vue-advanced-cropper#26]
Is there a way to set the aspect ratio based on the image width and height?

I want to check if the image is landscape and set the aspect ratio as `4:3` and min width and height as `500x375`. If the image is portrait, the aspect ratio must be `2:3` and the width and height as `400x600` min.

**Comment by Norserium** [comment]
Hello, @zefexdeveloper! 

You are able to set stencil aspect ratio dynamically before changing `src` prop. That's the way to get what you want.

With regards to maximum and minimum height you should have the custom function, that able to implement any logic that you want.

**Comment by zefexdeveloper** [comment]
> With regards to maximum and minimum heights you should have the custom function, that able to implement any logic that you want.

You mean like:

```js
    restrictions({
      minWidth,
      minHeight,
      maxWidth,
      maxHeight,
      imageWidth,
      imageHeight
    }) {
      return {
        minWidth: minWidth,
        minHeight: minHeight,
        maxWidth: Math.min(imageWidth, maxWidth),
        maxHeight: Math.min(imageHeight, maxHeight)
      };
    },
```

> You are able to change the stencil aspect ratio dynamically before changing the src prop. That's the pretty good way to get what you want.

You mean like on the `reader.onload` callback? Like before setting the `this.image` so `Crooper` can read, I also set a `this.aspectRatio` and use `:aspectRatio="aspectRatio"` on `Cropper`?

I will try that out, thank you very much.

**Comment by Norserium** [comment]
> You mean like

Yes, something like that

> Like before setting the this.image so Crooper can read, I also set a this.aspectRatio and use :aspectRatio="aspectRatio" on Cropper?

That's right.

**Comment by zefexdeveloper** [comment]
Thank you very much.

**Comment by Norserium** [comment]
Is there any flickering or it works well?
