### ISSUE TITLE
Get the image loading status

### ISSUE THREAD

**Issue by zefexdeveloper** [Norserium/vue-advanced-cropper#27]
I was looking and I couldn't find anything related. When loading an external image it takes a while to appear, perhaps it would be nice to provide a loading event indicating so we can show a `loading` message?

**Comment by Norserium** [comment]
Hello, @zefexdeveloper! It's the nice idea. I suppose, that cropper might fire `ready` event on complete an image loading.

**Comment by zefexdeveloper** [comment]
It would be cool, would help improving UX as we could provide a feedback to the user while the image is being loaded and avoid a white screen.

**Comment by Norserium** [comment]
Please update to `0.15.0` version. Now cropper fires `ready` event when an image is loaded.

**Comment by zefexdeveloper** [comment]
@Norserium You rock, thank you very much.

**Comment by jonalxh** [comment]
Hi. Is there a method when image start loading? My idea is to show a loading alert when it starts loading and hide it when finished, it is easy if I have just an img, but I have a lot and sometimes user tries to open the same img and I dont want the loader be shown again.

**Comment by Norserium** [comment]
@jonalxh, could you provide some example (codesandbox, gif or etc)?
