### ISSUE TITLE
Moving image when imageRestriction set to 'none'

### ISSUE THREAD

**Issue by NikitaKA** [Norserium/vue-advanced-cropper#29]
Hi! Thank you very much for new feature added in 0.15!

I showed new implemented feature to my collegues and they said that it is not clear/not comfortable to move background image when bounding box is covering almost whole available space. So you have to aim at small area on a side or spam mousewheel up/down trying to position it right 😃

Is that possible to add a setting (prop) which will change behavior of the stencil and allow user to drag image even when cursor is over it? (Stencil size still able to be resized by dragging its handles.)

Thank you in advance.

**Comment by Norserium** [comment]
Hello, @NikitaKA! Do you want to prevent moving the stencil like in this [example](https://norserium.github.io/vue-advanced-cropper/tutorials/recipes.html#fixed-stencil) (fixed stencil)?

**Comment by NikitaKA** [comment]
> Hello, @NikitaKA! Do you want to prevent moving the stencil like in this [example](https://norserium.github.io/vue-advanced-cropper/tutorials/recipes.html#fixed-stencil) (fixed stencil)?

I swear I read almost all the documentation. And still I missed this piece. `movable` did the work. Thanks! 🎉

**Comment by Norserium** [comment]
You are welcome! 

The documentation still has disadvantages, for example, I forgot to describe this props in the corresponding component pages.

**Comment by NikitaKA** [comment]
Taught by errors, I try to study the documentation in detail first, because the examples do not always include everything that library really can does. That rare case, when reading the documentation does not work. 😄

**Comment by Norserium** [comment]
It will work. I still have few time for this project, so now the writing examples is the first, that I do, because they are used for UI testing.
