### ISSUE TITLE
@change and upload images problem

### ISSUE THREAD

**Issue by basitiyidir** [Norserium/vue-advanced-cropper#3]
Hello

1. Uploading pictures.
2. Adding the @change method.
3. Picture is growing forever.

Where am I making a mistake.

source code

https://jsfiddle.net/0x1b7oau/

**Comment by Norserium** [comment]
Hello! 

You upload image and put in `data.image`. When it's uploaded `data.image` changes, that emits  `change` event, that update `data.image` again and so on.

So you should keep your result in another variable. For example:
https://jsfiddle.net/5dj7taq4/

**Comment by basitiyidir** [comment]
Very fast answer. :)

Problem is solved. Thank you for your help.

**Comment by Norserium** [comment]
@basitiyidir, you are welcome!
