### ISSUE TITLE
toDataURL returning nothing

### ISSUE THREAD

**Issue by zefexdeveloper** [Norserium/vue-advanced-cropper#30]
It was working before, including the examples @Norserium made and I:
- https://codesandbox.io/s/vue-avanced-cropper-basic-f711u
- https://codesandbox.io/s/gallery-crop-rnk26

You select the image, crop but the images are not being loaded as the base64 representation of the crop is not being return by `toDataURL`

**Comment by Norserium** [comment]
Hello, @zefexdeveloper! Both examples [works](https://i.ibb.co/7nd6J1k/example.png). Could you provide some details? Maybe this problem occurs when you upload the specific image.

**Comment by zefexdeveloper** [comment]
![image](https://user-images.githubusercontent.com/30276092/71309489-ef274580-23e6-11ea-85a4-fd4fdd1aa354.png)

For me it's not, any image I select is like this. The `toDataURL` is returning empty for some reason.

**Comment by Norserium** [comment]
It's interesting. What's the browser do you use? What are the images do you upload?

**Comment by zefexdeveloper** [comment]
@Norserium For some reason it works sometimes and other times it doesn't. I'm using Brave that is actually chromium. The images are regular images from unsplash.

**Comment by Norserium** [comment]
Please send me links at the images, that have problems with uploading.

**Comment by zefexdeveloper** [comment]
That is the image: https://unsplash.com/photos/K4mSJ7kc0As
In the console there's two errors but I don't know if it's related:
![image](https://user-images.githubusercontent.com/30276092/71310174-d7a08a80-23ef-11ea-8254-7d022709517d.png)

**Comment by Norserium** [comment]
This image is uploaded correct.

Do you save the image and then upload to the sandbox? Does this error occur when you upload image in the private mode?

**Comment by zefexdeveloper** [comment]
I just download the image and upload, nothing else. Even on private doesn't work.

**Comment by Norserium** [comment]
Could you try to upload image at the any other browser / device?

**Comment by zefexdeveloper** [comment]
![image](https://user-images.githubusercontent.com/30276092/71310283-0bc87b00-23f1-11ea-9438-0add29237d51.png)

It does work on Firefox

**Comment by Norserium** [comment]
It look like the problem of Brave browser. I will try to install it and test it on my virtual machine later.

**Comment by zefexdeveloper** [comment]
@Norserium It might be, the weird part is that it's chromium but still they might have changed something. It was working before and not it's not.

**Comment by Norserium** [comment]
I'm sure this problem is specific to conflict of _Brave Shield_ and _Codesandbox_. The examples at the demo site works well.

**Comment by Norserium** [comment]
@zefexdeveloper do you encounter this problem at your site?

**Comment by zefexdeveloper** [comment]
@Norserium Nop, it's working locally, sometimes it doesn't, it's weird, might be a bug somehow on Brave but it's all good. Sorry the delay to answer.

**Comment by CryptoSmileee** [comment]
We had the same problem with Brave mobile on our website.
I reported that some time ago but I think it got lost lost there. 

https://community.brave.com/t/htmlcanvaselement-todataurl-htmlcanvaselement-toblob-do-not-work-on-brave-mobile-with-fingerprint-protection/67774

**Comment by zefexdeveloper** [comment]
@CryptoSmileee Yes, I thought it was something related to the component but it's the browser. https://github.com/brave/brave-browser/issues/6081
