### ISSUE TITLE
InvalidStateError in Safari after file selection

### ISSUE THREAD

**Issue by silhouettepoms** [Norserium/vue-advanced-cropper#31]
The component is working fine in Chrome. However in Safari I see the following error after selecting a file to upload.

```
[Error] InvalidStateError: The object is in an invalid state.
	drawImage (app.js:68072:53179)
	updateCanvas (app.js:68072:53179)
	updateCanvas
	getResult (app.js:68072:52000)
	getResult
	update (app.js:68072:53288)
	update
	onChangeCoordinates (app.js:68072:53637)
	onChangeCoordinates
	(anonymous function) (app.js:68072:59834)
```

So it fails to do anything else after that point. It's working in Chrome but I do see the below error in the Developer tool (This is on page load, with an initial image URL supplied). You do not see an error in Chrome after file selection and it proceeds normally despite this error, Not sure if they might be related.

```
Uncaught DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
    at VueComponent.updateCanvas (http://xxx/js/app.js:68072:53169)
    at VueComponent.getResult (http://xxx/js/app.js:68072:51987)
    at VueComponent.update (http://xxx/js/app.js:68072:53278)
    at VueComponent.onChangeCoordinates (http://xxx/js/app.js:68072:53630)
    at http://xxx/js/app.js:68072:59814
```

**Comment by silhouettepoms** [comment]
Actually nevermind this is most likely due to my combination of components rather than an issue with the cropper itself. I'm probably passing some data at some point.

**Comment by TitanFighter** [comment]
[Possible solution](https://github.com/Norserium/vue-advanced-cropper/issues/34#issuecomment-578507001)
