### ISSUE TITLE
cropper box does not show the right section of the image at start

### ISSUE THREAD

**Issue by hamedsrk** [Norserium/vue-advanced-cropper#33]
hello . first of all i have to say thanks for developing this useful component
i have an issue and i dont know the reason. when i put my image to cropper, at start the cropper box does not show the right section of the image.like the picture below(pay attention to the hand that exist in picture. it cut the hand and move it)

<img width="852" alt="Screen Shot 2020-01-12 at 4 04 17 PM" src="https://user-images.githubusercontent.com/47821202/72218933-c1509f00-3555-11ea-9b4b-49d3bbecb08d.png">

but when i move the box 1 or 2 times across the whole image it works correctly. 

<img width="853" alt="Screen Shot 2020-01-12 at 4 14 42 PM" src="https://user-images.githubusercontent.com/47821202/72219016-b9ddc580-3556-11ea-910d-8e68982b7062.png">

can you see the diffrence between this two images ? how can i solve this problem ?
thanks

**Comment by Norserium** [comment]
Hello! Could you provide more details? Did you try to reproduce this bug at the codesandbox?

**Comment by hamedsrk** [comment]
> Hellol, @hamedsrk! Could you provide more details? Did you try to reproduce this bug at the codesandbox?

i find the solution. my project is rtl and this problem happen in rtl direction. i changed the direction of the component to ltr and the problem solved

**Comment by Norserium** [comment]
Thank you for details! It's definitely bug, therefore don't close the issue. I will investigate how to fix it.

**Comment by Norserium** [comment]
This issue is resolved in `0.15.3`.

**Comment by Norserium** [comment]
@hamedsrk, I close this issue. If you encounter this problem again, please inform me.
