### ISSUE TITLE
CDN Competent Not Registered

### ISSUE THREAD

**Issue by digitalgym** [Norserium/vue-advanced-cropper#36]
I'm using the CDN option but am unable to access the canvas component via $refs it's always undefined, do you have a working example using CDN and accessing global components?

**Comment by Norserium** [comment]
Hello, @digitalgym! Could you provide some code please to illustrate your problem?

**Comment by Norserium** [comment]
@digitalgym, is your problem solved?

**Comment by Norserium** [comment]
I close this issue. But if you encounter this problem again, feel free to inform.
