### ISSUE TITLE
how to download crop image 

### ISSUE THREAD

**Issue by Arun27862786** [Norserium/vue-advanced-cropper#37]
anyone answer me to how to add a button to download crop image 
like  this  code not available url 
https://norserium.github.io/vue-advanced-cropper/tutorials/recipes.html#different-image-restrictions
![Untitled](https://user-images.githubusercontent.com/58700666/74857989-8e4ab980-5312-11ea-9b3f-8d88a579efc8.png)

**Comment by Norserium** [comment]
Hello, @Arun27862786! 

Sorry, but I don't understand completely what you want to get. 

Do you want to implement the same button like the button in this example? In this case, you should investigate this [sandbox example](https://codesandbox.io/s/vue-avanced-cropper-basic-jfy5w).

**Comment by Norserium** [comment]
@Arun27862786, is your problem still actual?

**Comment by Norserium** [comment]
@Arun27862786, I close the issue. If your problem is still actual feel free to ask me to reopen it.
