### ISSUE TITLE
Scroll and restrict area doesn't works

### ISSUE THREAD

**Issue by ErriourRU** [Norserium/vue-advanced-cropper#38]
I use cropper in modal of VueBootstrap, and it's important to use cropped area for crop image. I'm getting code from [example](https://norserium.github.io/vue-advanced-cropper/tutorials/recipes.html#upload-image). No problems in example but not on my site...

```
<b-modal size="xl" id="cropAvatar" hide-footer>
<template v-slot:modal-title>
    Загрузка аватара
</template>
<div>
    <div class="row">
        <div class="col-12">
            <div class="avatar-area">
                <cropper
                    classname="upload-example-cropper"
                    :src="loadedAvatar"
                    :defaultPosition="defaultPosition"
                    :defaultSize="defaultSize"
                    :restrictions="pixelsRestriction"
                    :stencil-props="{
                        movable: true,
                        scalable: true,
                    }"
                    :minHeight="200"
                    :minWidth="200"
                    :maxWidth="200"
                    :maxHeight="250"
                    @change="loadAvatar"
                ></cropper>
            </div>
        </div>
    </div>
</div>
</b-modal>
```

```
defaultPosition() {
    return {
        left: 100,
        top: 100
    }
},
defaultSize() {
    return {
        width: 200,
        height: 250,
    }
},
pixelsRestriction({minWidth, minHeight, maxWidth, maxHeight, imageWidth, imageHeight}) {
    return {
        minWidth: minWidth,
        minHeight: minHeight,
        maxWidth: maxWidth,
        maxHeight: maxHeight,
    }
},
handleAvatar() {
    var input = event.target;
    if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = (e) => {
                this.loadedAvatar = e.target.result;
        }
        reader.readAsDataURL(input.files[0]);
    }
},
loadAvatar() {

}
```

```
<style>
    .upload-example-cropper {
        width: 100%;
        height: 400px;
    }
</style>
```
With this code I'm getting this: image can't be scallable, it is reduced to a height in the style that everything becomes 2 times smaller. If I'm deleting style, size becomes normally, but scaling doesn't works.
![image](https://user-images.githubusercontent.com/43105218/75664226-daf0a600-5cbd-11ea-9f7a-76b7d07c1953.png)
No errors and warnings in console.

-----------
**UPD**: Problem because restrictions was set. But I need them.

**Comment by Norserium** [comment]
Hello, @ErriourRU! Could you provide codesandbox, that will illustrate your problem? The template is [here](https://codesandbox.io/s/vue-avanced-cropper-basic-jfy5w).

**Comment by ErriourRU** [comment]
@Norserium [https://codesandbox.io/s/vue-avanced-cropper-basic-1ilk9](https://codesandbox.io/s/vue-avanced-cropper-basic-1ilk9). I think image must be cropped to 100% and part beyond the borders of block hidden and movable... Frame must have exactly default set sizes.

**Comment by Norserium** [comment]
Thank you! Could you provide the image to reproduce your problem also?

**Comment by Norserium** [comment]
In other words, you want to make the cropping area width always be equal to `200 - 250 px` and height to `200 px`  ?

**Comment by ErriourRU** [comment]
Yes. Image may be any with large sizes. If what matters is what I used: [https://i.imgur.com/mUZFNyz.jpg](https://i.imgur.com/mUZFNyz.jpg)

**Comment by Norserium** [comment]
I suppose you want to get something like that
![example](https://user-images.githubusercontent.com/9862719/75677635-ff885600-5c9c-11ea-8b7e-2eef26f3d960.png)

Unfortunately it's not possible right now. In theory it's pretty easy to implement, but it's not obvious what should I do with the edge cases.

**Comment by Norserium** [comment]
@ErriourRU, hello! Could you look at [the example](https://codesandbox.io/s/vue-advanced-cropper-fixed-stencil-dbnyj). Is that you want to implement?
