### ISSUE TITLE
Default Stencil with Aspect Ratio and Maximum Width

### ISSUE THREAD

**Issue by NRiebesel** [Norserium/vue-advanced-cropper#39]
Hello,

firstly: Great component, thanks!
Could you provide an example for a cropper configuration with a default stencil having maximum width of 100% of the image but also sticks to a custom aspect ratio (for e.g. 16/9).

I tried a few things and also searched through the docs. Using `setCoordinates`, `ready` event , `stencilProps`, but I cant get it to work. Thank you!!

**Comment by Norserium** [comment]
Hello, @NRiebesel! If I understood you correctly, there is [the example](https://codesandbox.io/s/vue-avanced-cropper-169-k67t7), that you need.

**Comment by NRiebesel** [comment]
Wow, it's as simply as that.
It works. Thanks a lot!
