### ISSUE TITLE
Disable zoom image

### ISSUE THREAD

**Issue by moniroth0310** [Norserium/vue-advanced-cropper#40]
is there any way to disable the zoom of the image? i only want to crop the original size of the image
thank you

**Comment by Norserium** [comment]
@moniroth0310, hello! What do you mean by "zoom of the image"? You can disable wheel and touch resize by setting props `wheelResize` and `touchResize` to `false`.

**Comment by moniroth0310** [comment]
actually i want to disable touch resize, i just couldn't find the right word to put. by the way, could you please give me a short demo on where exactly do you put the touchResize props?

**Comment by Norserium** [comment]
[There you are.](https://codesandbox.io/s/vue-avanced-cropper-basic-w81q5)

**Comment by Norserium** [comment]
@moniroth0310, did you solve the problem?

**Comment by moniroth0310** [comment]
yes, my problem has been solved. Thank you

**Comment by Norserium** [comment]
You are welcome!
