### ISSUE TITLE
Pass cropper to every image and get the result 

### ISSUE THREAD

**Issue by moniroth0310** [Norserium/vue-advanced-cropper#42]
hello, allow me to explain my point first before going to the questions.
imagine I have select 3 images from input and set them same aspect ratio, and a button OK that later convert a base64 image (i get from using getResult() method) into an image file and upload it. Using this
```
const {coordinates, canvas} = this.$refs.cropper.getResult()
this.coordinates = coordinates
this.image = canvas.toDataURL()
```
or this
```
onChange({coordinates, canvas}) {
    this.coordinates = coordinates
    this.image = canvas.toDataURL()
}
```
can only get the result if I have clicked on each image at least once. my question is if I select 3 images from the browser then click OK right away I couldn't get the result of all 3 images, so is there any way to pass the cropper to every image?

**Comment by Norserium** [comment]
Hello, @moniroth0310! Could you provide [codesanbox example](https://codesandbox.io/s/vue-avanced-cropper-basic-jfy5w)?

**Comment by Norserium** [comment]
@moniroth0310, any news?

**Comment by Norserium** [comment]
@moniroth0310, I close issue. Feel free to write here if you encounter this problem in the future.
