### ISSUE TITLE
PixelRestrictions for minWidth and minHeight stopt working at Version 0.15.0

### ISSUE THREAD

**Issue by typedcode** [Norserium/vue-advanced-cropper#43]
Hi,

setting the Pixel-Restrictions with
`{
    minHeight: 10,
    minWidth: 10,
    maxWidth: 480,
    maxHeight: 110
}`

used to work up to Version 0.14.1, since Version 0.15.0 (testet it up to current version 0.16.0) setting the minWidth and minHeight is broken. The Image used is 1024x786px and I get the following error message when trying to set the default Size to 186x50px:

`Warning: default size breaking size restrictions. Check your defaultSize function 
Object { width: 186, height: 50 }
Object { minHeight: 89, minWidth: 89, maxWidth: 480, maxHeight: 110 }`

Setting the max-Values still works.

Thanks in advance.

**Comment by Norserium** [comment]
@typedcode, thank you for your report. Fixed in `0.16.1`.

**Comment by typedcode** [comment]
@Norserium, thanks for the quick fix!
