### ISSUE TITLE
Handling errors

### ISSUE THREAD

**Issue by ThePendulum** [Norserium/vue-advanced-cropper#47]
Hi,

I was wondering if there's a recommended way to handle whatever error this library may encounter. I figured an `@error` event or the like would be useful to have, so if the cropper fails to load an image for any reason, I can properly reset the interface and inform the user, without having to rely on an arbitrary timer to check whether the `@ready` event fired.

Thanks you in advance!

**Comment by Norserium** [comment]
Hello, @ThePendulum! Could you provide some codesandbox example, that illustrates your problem?

**Comment by ThePendulum** [comment]
Hi, thanks for replying!

I added a URL input to one of your examples: https://jsfiddle.net/ThePendulum/9prse6ky/, and a 'loading...' indicator. If you enter the URL to an image, such as https://images.pexels.com/photos/580012/pexels-photo-580012.jpeg?h=650 from the original example, 'loading...' will show up and disappear when the cropper is ready. However, if you enter an invalid image URL, such as https://httpstat.us/404, the cropper won't show up and the interface will be stuck at 'loading...'.

There will be some errors in the console, since those occur within your library, there doesn't seem to be a straight-forward way to know that something went wrong. If this scenario errors trigger an 'error' event or the like, I can reset the interface and tell the user their URL is not a valid image.

**Comment by Norserium** [comment]
@ThePendulum, thank you for so detailed response! I will investigate the solution.

**Comment by Norserium** [comment]
@ThePendulum, I've added `error` event in `0.16.2`. The example of using this event is added to [recipes too](https://norserium.github.io/vue-advanced-cropper/tutorials/recipes.html#events).

**Comment by Norserium** [comment]
@ThePendulum, any news?

**Comment by ThePendulum** [comment]
Thank you so much! This will make it much easier to offer a smooth user experience :-)

**Comment by Norserium** [comment]
I'm happy to help!
