### ISSUE TITLE
Get avatar from facebook with 404 error

### ISSUE THREAD

**Issue by chehonte** [Norserium/vue-advanced-cropper#48]
Hi!

I use cropper for edit avatar, when user is sign up with facebook. Cropper add timestamp get param to image url before request and facebook send an error.

It was in v0.16.1 but the image appeared. In v0.16.2 i have a blank editor without image. I downgraded version to v0.16.1 and it works.

I don’t understand how it can be in 0.16.1 when we have 404 error but image was appeared.

I think you can provide an option to disable timestamp for some user cases.

**Comment by Norserium** [comment]
Hello, @chehonte! What's the error does Facebook send to you?

**Comment by chehonte** [comment]
@Norserium 

https://platform-lookaside.fbsbx.com/platform/profilepic/?asid=110928713939171&height=200&width=200&ext=1591361354&hash=AeTkH7LMSPx5oYJo&timestamp=1588769355170

This link with timestamp and we get 404 error, i think facebook validate get params. If we remove timestamp from this link we get an image.

**Comment by Norserium** [comment]
@chehonte, I've rolled back the busting cache changes in `0.16.3`.

**Comment by chehonte** [comment]
@Norserium Thank you!
