### ISSUE TITLE
Zoom in/out of image

### ISSUE THREAD

**Issue by DavidScicluna** [Norserium/vue-advanced-cropper#49]
Hi, I noticed that the image can be zoomed in/out with the mousepad and when I inspect the element it shows that some style is added to the image that enables it to zoom in/out.

My question is if there is a way to bind that zoom in/out feature to a button?

**Comment by Norserium** [comment]
Hello, @DavidScicluna! 

No, there is not. But it's the most desired feature request. Alas, me need pretty much time to implement it.

**Comment by DavidScicluna** [comment]
Okay, thank you for the fast reply. I love your component thank you for all the work and hope you can implement as soon as possible

**Comment by Norserium** [comment]
@DavidScicluna, could you take a look at [this example](https://norserium.github.io/vue-advanced-cropper/tutorials/advanced-recipes.html#manipulate-image)?

**Comment by Norserium** [comment]
@DavidScicluna,` zoom` method is finally added. Please update to version `0.17.1`.
