### ISSUE TITLE
Thoughts and plans about 1.0

### ISSUE THREAD

**Issue by Norserium** [Norserium/vue-advanced-cropper#50]
This issue is created to discuss new changes, include breaking changes in the new version. Feel free to discuss about the planned changes.

**Breaking changes:**
1. Move the styles to independent `.css` file. It will require to add `<link  href="/path/to/vue-advanced-cropper.css" rel="stylesheet">` to your code, but make this process more clearer.
2. Rename `classname`, `backgroundClassname`, `imageClassname`, `linesClassnames` and `classnames` to `class`, `backgroundClass`, `imageClass`, `linesClasses` and `classes` respectively.
3. Rename `restrictions` prop to `sizeRestrictionsAlgorithm`.
4. Set the pixels restrictions by default instead of the percents restrictions.
5. Change the list of available image restrictions to `fill-area`, `fit-area`, `stencil` and `none`. 
6. Move algorithms in the external package.

**Comment by Atluss** [comment]
Maybe add muiltycrop functions?

**Comment by Norserium** [comment]
@Atluss, what do you mean by "multicrop"?

**Comment by Atluss** [comment]
Crop multiple areas.

**Comment by Norserium** [comment]
@Atluss could you provide the example of such cropper? I can't imagine any use cases where it would be needed.

**Comment by Atluss** [comment]
For example to crop several faces on photo. In my case i use two libraries for it.

**Comment by Norserium** [comment]
@Atluss, what's libraries? I prefer to implement this task by creating multistep cropper, so I would be glad to see the screenshots, examples or video.

**Comment by Atluss** [comment]
First library vue-advanced-cropper for single crop image, second vue-moveable for multicrop(but this library use react dependencies). For example on this screenshot, selected regions of image for OCR scans. [screenshot](https://cloud.mail.ru/public/HdaU/2NXobRk9M)

**Comment by Norserium** [comment]
@Atluss, thank you. I understand your use-case now. But it's pretty hard to save the all current features and implement this feature at the same time.

**Comment by Atluss** [comment]
Ok, i understand:) if there are more ideas I will write about it.

**Comment by Utsav-upadhyay** [comment]
Yes, Indeed multi-cropping is the biggest feature and No one is providing it with Zoom, rotate feature, some libraries have multi-cropping like JCrop but they do not have zoom feature in it, Please see multiple cropping examples below, one can crop multiple area at a time
![Screenshot 2022-02-11 104551](https://user-images.githubusercontent.com/81962784/153541047-b8284334-a547-49c0-8075-41296ae4f0f5.png)

**Comment by Norserium** [comment]
@Utsav-upadhyay, hello! 

The most right approach is the creating the in-depended library to solve this task. This library can't support this feature due its concept and design now. There is [the discussion about this feature](https://github.com/Norserium/vue-advanced-cropper/discussions/162#discussioncomment-1681700).

But anyway, did you encounter some croppers (proprietary perhaps) that implements the multi-crop in the right way? I want to see how it should behave.
