### ISSUE TITLE
"export 'MoveableArea' was not found in 'vue-advanced-cropper'

### ISSUE THREAD

**Issue by ChileNetwork** [Norserium/vue-advanced-cropper#52]
Hi there:
I would like to put this issue. Not sure what is going on. Can anybody help here??? Thank you

**Comment by Norserium** [comment]
Hello, @ChileNetwork. Yes I can.  Could you provide the code that produces this error?

**Comment by Norserium** [comment]
@ChileNetwork, is your problem solved?

**Comment by Norserium** [comment]
The example is fixed. Closing issue.
