### ISSUE TITLE
Error while using this library on IE Browsers

### ISSUE THREAD

**Issue by pujara83** [Norserium/vue-advanced-cropper#53]
Error : “TypeError: Object doesn’t support property or method ‘toBlob’

**Comment by Norserium** [comment]
Hello, @pujara83! It's not the problem of this library.  IE doesn't support [this method](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob). Use polyfill to solve this problem.

**Comment by Norserium** [comment]
@pujara83, any news?

**Comment by Norserium** [comment]
I close this issue due to inactivity. If you encounter this problem in the future feel free to reopen the issue.
