### ISSUE TITLE
Resize goes away with restrictions

### ISSUE THREAD

**Issue by lexicalninja** [Norserium/vue-advanced-cropper#54]
Hello,

Thank you for this great tool. It was super easy to use and get going. 

I have an issue where I am telling the cropper to set the following restriction: 
```typescript
pixelsRestriction({minWidth, minHeight, maxWidth,maxHeight, imageWidth, imageHeight}: any) {
      return {
        maxWidth: this.width,
        minWidth: this.staticSize ? this.width : 64,
        minHeight: this.staticSize ? this.height : 64,
        maxHeight: this.height
      }
    }
```
but when i set those to the cropper, it stops being able to use the wheel to resize the image while cropping. 

I have tried forcing the `:wheelResize="true"` and was not successful. 

Any idea on how to get this working? Thank you in advance for your time. It is greatly appreciated.

**Comment by Norserium** [comment]
Hello, @lexicalninja! 

I suppose there is the little misunderstanding. The restrictions apply only to the real size of cropped image, not the size of stencil on your screen.

**Comment by lexicalninja** [comment]
ok. so if I want the cropped image say 64 x64 and no other size, but to allow resizing while cropping is there currently a way to do this?

Thanks for getting back so fast

**Comment by Norserium** [comment]
Unfortunately, it's not possible right now. 

I want to rebuild all resize image system in the future (to make it possible and add the possibility to resize image programatically), but I have too much another work right now.

**Comment by lexicalninja** [comment]
understandable. I may see if I can hack around it with a 1 pixel difference. Thanks for the quick reply.

**Comment by Norserium** [comment]
Hello, @lexicalninja! Could you take a look at [the following example](https://codesandbox.io/s/vue-advanced-cropper-another-fixed-stencil-1yi6f?file=/src/App.vue). Did you want to implement it?

**Comment by lexicalninja** [comment]
Let me take a look next week and see if it works. Thanks for getting back 

⁣Sent from TypeApp ​
