### ISSUE TITLE
Displaying Cropper within modal or element with display none

### ISSUE THREAD

**Issue by bribar** [Norserium/vue-advanced-cropper#55]
I use UIkit specifically, but also tried on a div element with display:none;

When the modal is displayed, the image and cropper doesn't display.

https://jsfiddle.net/bribar/6chtk9pe/

I've noticed with a div, if I hide the div from within the Cropper Ready event, I can toggle the display attribute and Cropper has no issue.

I really want to use it in a modal. Any work-arounds?

**Comment by Norserium** [comment]
@bribar, there are always some [workarounds](https://jsfiddle.net/d35zv1t2/). But I suppose a special method for such cases should be added.

**Comment by bribar** [comment]
Oh ok that works. Wasn't aware of onResizeWindow(), that in the docs? If not, might be helpful or a reload method :)

**Comment by Norserium** [comment]
No, it's an undocumented approach. It's a workaround. There should be reload method and I will try to implement it soon.

**Comment by bribar** [comment]
Ok thanks a lot! Nice work with the plugin btw!

**Comment by Norserium** [comment]
@bribar, now you can freely use the method `refresh`. It's called on window resize and it should be called on the external container resize.
