### ISSUE TITLE
Black background of the image preview with Cropper makes .png with black and transparent not visible.

### ISSUE THREAD

**Issue by heons** [Norserium/vue-advanced-cropper#56]
`<cropper
        ref="imageCropper"
        classname="cropper"
        :src="imagePreview"
        :stencil-props="{ aspectRatio: 1/1 }"
      />`

    currentImage: function(img) {
      if (img) {
        const fr = new FileReader();
        fr.readAsDataURL(img);
        fr.addEventListener("load", () => {
          // Save the file and preview.
          this.imageFile = img;
          this.imagePreview = fr.result;
          // Open the crop dialog.
          this.dialogs.imageCrop = true;

        });
      }
imagePreview is base64 dataURL.
If it has back and transparent alpha channel, it is not visible.

original image.
<img width="129" alt="Screen Shot 2020-06-23 at 6 20 36 PM" src="https://user-images.githubusercontent.com/26397909/85471422-7021ee00-b57e-11ea-9c6c-21df9c849331.png">
displayed image.
<img width="631" alt="Screen Shot 2020-06-23 at 6 20 59 PM" src="https://user-images.githubusercontent.com/26397909/85471443-7748fc00-b57e-11ea-8226-f381808e3ed6.png">

**Comment by heons** [comment]
I was able to remove the alpha channel of png using this.
https://stackoverflow.com/a/54068589/7917275

**Comment by Norserium** [comment]
@heons, could you attach the image as file and provide a codesandbox?

**Comment by heons** [comment]
Image : 
![add_circle_black_108x108](https://user-images.githubusercontent.com/26397909/85550035-8ebfcd80-b5ee-11ea-8c1a-71cc1101e89c.png)

Sandbox : 
https://codesandbox.io/s/youthful-proskuriakova-et7rv?file=/src/components/HelloWorld.vue

**Comment by Norserium** [comment]
@heons, this bug is fixed in `0.16.6`. Please update to this version and change the color of your background. Example is [here](https://codesandbox.io/s/charming-engelbart-ej0zd).

**Comment by heons** [comment]
@Norserium Thank you for the fix. It works ok. But I found one weird thing. Ff the style is scoped <style scoped>, it doesn't work.

**Comment by Norserium** [comment]
@heons, I know. I will investigate the solution, but I'm not completely sure that it's possible.

**Comment by heons** [comment]
> @heons, I know. I will investigate the solution, but I'm not completely sure that it's possible.

It is ok.Just letting you know. Thank you so much~!!!

**Comment by Norserium** [comment]
@heons , I close this issue. The using scoped styles bug is registered.
