### ISSUE TITLE
Fixed stencil can't be moved (/w code example)

### ISSUE THREAD

**Issue by tre-dev** [Norserium/vue-advanced-cropper#57]
First off: thanks for the great tool!

I'm trying to implement the `fixed stencil` ala [twitter style](https://user-images.githubusercontent.com/59442299/85801934-2b47b400-b744-11ea-8e52-c33578581199.png), where the stencil is in fullscreen and it can be moved towards the edges of the images & zoomed.

But I'm running into a problem. I've used exactly the code from the fixed-stencil example, but I'm not able to move the stencil towards the edges unless I zoom in, but even then; I can only move a bit.

Here is a codesandbox example: https://codesandbox.io/s/vue-avanced-cropper-169-fo2sx

**Comment by Norserium** [comment]
Hello, @tre-dev!

There was the undocumented aspect. I missed the line `image-restriction="stencil"`. Also you have used the outdated version of the cropper.

Take a look at [the fixed version of your codesandbox](https://codesandbox.io/s/vue-avanced-cropper-169-djycs?file=/src/App.vue:349-376).

**Comment by tre-dev** [comment]
Awesome! I used the up-to-date version locally, but `image-restriction="stencil"` fixed it. Thanks!

**Comment by Norserium** [comment]
@tre-dev, unfortunately, it's not possible, because you can't set the stencil height directly (only cropped area). I'm thinking how to fix this limitation in the next version.

**Comment by tre-dev** [comment]
Ok, thank you.

Is there any way to set a maxWidth/Height within a `fixed stencil`? It seems to be working fine when I reduce the browser width, as in the image keeps the aspect ratio and just "shrinks". But when I set the width/height directly for `.cropper`, it's just "cut" on the sides.

**Comment by Norserium** [comment]
@tre-devб сould you take a look at [this example](https://norserium.github.io/vue-advanced-cropper/tutorials/showcase.html#twitter). Is that you wanted to implement?

**Comment by tre-dev** [comment]
Amazing! Is it also auto-scaling/zooming to a fixed height/width?

When taking this image: 

<img width="590" alt="longimage" src="https://user-images.githubusercontent.com/59442299/92301618-68f76300-ef65-11ea-9322-d6f22187e24a.png">

I would like it to fit inside the red-cube:

![image](https://user-images.githubusercontent.com/59442299/92301601-5e3cce00-ef65-11ea-8dd1-061cf5cd66ad.png)

Otherwise, the more rectangular the image gets, the smaller it becomes and the more difficult the handling will get.

**Comment by Norserium** [comment]
@tre-dev , that's what you will get:
![example](https://user-images.githubusercontent.com/9862719/92303652-b84a8d00-ef7f-11ea-95ac-9bb73b952bae.png)

I've moved the code to [codesandbox](https://codesandbox.io/s/vue-advanced-cropper-twitter-zr3np?file=/src/App.vue), so you can experiment with it on your own. But I should warn you: the code is not production ready, because it uses the not released features.

**Comment by Norserium** [comment]
@tre-dev, have you seen the last example? Is that what you wanted to get?

**Comment by tre-dev** [comment]
Yes, sorry. Exactly what I want!

**Comment by Norserium** [comment]
@tre-dev, nice! I will try to optimize code later and publish it in the showcase documentation section. It's not straightforward solution, but. at least, the implementing of the new cropper concepts makes this possible.

**Comment by Norserium** [comment]
@tre-dev, nice! I will try to optimize code later and publish it in the showcase documentation section. It's not straightforward solution, but. at least, the implementing of the new cropper concepts makes this possible.
