### ISSUE TITLE
Image restriction "stencil" with custom circle stencil

### ISSUE THREAD

**Issue by tre-dev** [Norserium/vue-advanced-cropper#58]
I would like to combine the `image-restriction="stencil"` with the custom `circle stencil`.

Below is an example. When you remove `:stencil-component="$options.components.CircleStencil"` it works as it should, just with the wrong stencil.

https://codesandbox.io/s/vue-avanced-cropper-169-3hnj2?file=/src/App.vue

**Comment by Norserium** [comment]
Hello, @tre-dev! 

The stencils props `movable` and `scalable` are not used by cropper, they are used only by stencil. Default components processes them correctly and block moving and scaling, but your custom stencil doesn't.

There is [the example of processing that props](https://codesandbox.io/s/vue-avanced-cropper-169-bydn0?file=/src/circle.vue) by your stencil.

**Comment by Norserium** [comment]
@tre-dev, any news?

**Comment by tre-dev** [comment]
Thought I had already commented, sorry. Yes, your example worked!

The only thing I'm missing is an autozoom with fixed width/height, as modifying a pretty wide image will make the height tiny. But AFAIK, you're already aware of that feature request, but don't have enough time, right?

**Comment by Norserium** [comment]
@tre-dev, yes you are right.
