### ISSUE TITLE
default size or position, get all the space

### ISSUE THREAD

**Issue by euberdeveloper** [Norserium/vue-advanced-cropper#59]
Hi, I want the cropper to cover all the image by default.

I tried with:

```js
function defaultPosition() {
			return {
				left: 0,
				top: 0,
                                right: 0,
                                bottom: 0
			};
		}
```

And passing it to `:default-position="defaultPosition"`, but it does not recognize right and bottom.

How to solve the problem, if you do not know the given image width and height?

**Comment by euberdeveloper** [comment]
I looked better at the docs and I used

```js
this.$refs.cropper.setCoordinates((coordinates, imageSize) => ({
          width: imageSize.width,
          height: imageSize.height
        }));
```

**Comment by Norserium** [comment]
@euberdeveloper, just for your information, to init coordinates you may use `defaultPosition` and `defaultSize` props separately. But your method is also suited now.
