### ISSUE TITLE
Rotate mobile upload image

### ISSUE THREAD

**Issue by yankaled** [Norserium/vue-advanced-cropper#6]
Hi, Norserium. When uploading images on mobile, if the image is not - almost - a square - as it is the case with pictures taken with a mobile camera - it defaults to landscape orientation, even if the image was originally in portrait orientation. Is it possible to fix this? By the way, this is a great library, good work!!

**Comment by Norserium** [comment]
Hello, @yankaled!

It's actually pretty complicated task. I've prepared the new release that fixes it, but it need to be tested.

The documentation is currently using `11.0.0` version of this library, so you can test it himself too by uploading that images here:
https://norserium.github.io/vue-advanced-cropper/tutorials/recipes.html#custom-restrictions

**Comment by yankaled** [comment]
Thanks, @Norserium !! Yeah, I figured out it's a hard task when I tried to rotate the image with css and frontend script. I'll keep an eye out for your new release :)

**Comment by Norserium** [comment]
I've released `0.11.0`. Please update to this version and check.

**Comment by tschut** [comment]
Hi, I ran into the same thing. Upgraded to 0.11.0 and it's fixed :)

**Comment by yankaled** [comment]
Tested it as well, it's fixed!! Nice upgrade @Norserium !!

**Comment by Norserium** [comment]
@yankaled, it's nice. I'm closing this issue now, if you encounter any problems with this aspect, write me.
