### ISSUE TITLE
Restore zoom level on cropper image

### ISSUE THREAD

**Issue by stuartraines** [Norserium/vue-advanced-cropper#61]
Firstly, I'd just like to say it's an awesome component! Really appreciate your hard work building it.

For my use case, after cropping an image, I give the user the ability to edit the cropped area at a later date. I then want to load the original image pre-cropping back into the component, and then restore the image position and zoom level, so that it shows the previously cropped area within the stencil.

Is there any way to control these parameters for the image via props or programatically?

**Comment by Norserium** [comment]
Hello, @stuartraines! You can't set or control initial zoom programatically right now. It's the most desired feature, but one is pretty hard to implement, and I still have not got time to do it.

**Comment by stuartraines** [comment]
Hello @Norserium. No worries, I'll work around it for now.

**Comment by Norserium** [comment]
@stuartraines , could you take a look at [this example](https://norserium.github.io/vue-advanced-cropper/tutorials/advanced-recipes.html#default-visible-area) ("default visible area" section)? Is that you want to implement?

**Comment by stuartraines** [comment]
@Norserium looks great in terms of setting the position and dimensions. I was also looking for a way to set the initial zoom. Will there be a way to do that too?

**Comment by Norserium** [comment]
@stuartraines, technically it's the initial zoom. Try to zoom out the example with the girl on the beach.

**Comment by stuartraines** [comment]
@Norserium i'm not sure I follow. I can see that the girl on the beach image is zoomed in a bit initially, but I can't see how that initial zoom is set via a prop or method?

**Comment by Norserium** [comment]
I suppose there is little misunderstanding about what is the visible area.  I'm updating the documentation now where I will try to explain this concept.

Let's remember, what is the cropper structure:

![cropper](https://user-images.githubusercontent.com/9862719/91986567-8514bd80-ed35-11ea-927a-c82fa88f298b.png)

The image is displayed inside the boundaries. But what's part of the image we see? When image is not zoomed user sees the whole image, but what's the part of image user sees when he zoom or translate image? This part can be called literally "visible area".

The visible area is the most abstract, flexible and determined way to define the image zoom and translation. 

![visible-area](https://user-images.githubusercontent.com/9862719/91987745-1d5f7200-ed37-11ea-8130-6cf8d19ffd1b.png)

It's demonstrated below at the examples how the zoom and translate is bind with visible area.

![visible-area-examples](https://user-images.githubusercontent.com/9862719/91988127-95c63300-ed37-11ea-8770-f84c3fcbf672.png)

Therefore to set default zoom and translation you just need to set default visible area.

**Comment by Norserium** [comment]
It's possible now by [setting default visible area](https://norserium.github.io/vue-advanced-cropper/guides/advanced-recipes.html#default-visible-area).
