### ISSUE TITLE
Minimum Pixel-Restrictions not working since Version 0.16.2

### ISSUE THREAD

**Issue by typedcode** [Norserium/vue-advanced-cropper#64]
Hi,

setting the Pixel-Restrictions with
`{ minHeight: 15, minWidth: 15, maxWidth: 480, maxHeight: 110 }`
worked since Version 0.16.1. It is broken since 0.16.2.

The Vue-Developer-Tools show, that the values were correctly set
`stencilRestrictions:Object
maxHeight:110
maxWidth:480
minHeight:15
minWidth:15`

No error is reported in JS-Console.

The Smallest selection one can make is 102,39 x 76,8. Changing the values does not effect the result. Since the Original Image is 1024*768 it looks like the minimum is (ignoring  rounding errors) 10% of the original image.

Thanks in advance.

**Comment by Norserium** [comment]
Hello, @typedcode!

You're right. Currently there is the limitation for image. It is indeed equal to 10% of visible area and is designated to prevent resize stencil to a point.

But [there is a problem](https://en.wikipedia.org/wiki/Sorites_paradox). When I should prevent resize? So I still think how to solve this problem more elegant.

**Comment by typedcode** [comment]
Hello @Norserium,

how about shifting the responsibility for this matter to the user? Leave the restriction to 10% but let the user override it with the pixelRestrictions. Then the user has to deal with it.

**Comment by Norserium** [comment]
@typedcode, I thought about that too. But, there is catch, because your `pixelRestrictions` is used to prevent all possible resizes that will make the stencil smaller than your restrictions. The new limitation prevents only stencil resizing but doesn't prevent wheel or touch zoom.

**Comment by Atluss** [comment]
Hi all, i have same problem:( Any trick or options for it?

**Comment by Norserium** [comment]
@typedcode, @Atluss I suppose I can reduce the internal limitation for height and width to make them as small as possible. It's not the ideal solution, but I suppose it will be nice compromise in the current situation.

**Comment by Atluss** [comment]
I think this will help 👍

**Comment by Norserium** [comment]
@Atluss, @typedcode could you update to `0.16.10` and give your response.

**Comment by Atluss** [comment]
Now works fine :) thanks a lot!

**Comment by typedcode** [comment]
I still cant go smaller than 20*20px. There is a new parameter "minimum" which is set to 20. I would like to overwrite it, but I cant.

**Comment by Norserium** [comment]
@typedcode, could you send me the screenshot? I'm pretty sure that you won't be able to work with stencil smaller than 20px anyway.

**Comment by Norserium** [comment]
@typedcode is your problem still actual?

**Comment by Norserium** [comment]
I close this issue. Feel free to write here if you have any related questions.
