### ISSUE TITLE
Black background issue with SVG under VueJS

### ISSUE THREAD

**Issue by MattiaFailla** [Norserium/vue-advanced-cropper#66]
Hello,
the background of every svg files is black. 
On vue it is impossible to change the background due to the scoped style. (I am using the latest version of this plugin).

Example svg rendering on a normal Chrome tab:
![image](https://user-images.githubusercontent.com/11872425/90232543-21296400-de1d-11ea-8a99-ab64aaabfae7.png)

Under the plugin:
![image](https://user-images.githubusercontent.com/11872425/90232571-2f778000-de1d-11ea-975f-15c40e8377ae.png)

If you need the svg image I can send it to you by mail. 
Thanks!

**Comment by Norserium** [comment]
Hello, @MattiaFailla! Did you try to turn off scoped styles for the cropper and change the background color?

**Comment by MattiaFailla** [comment]
Hello @Norserium. Yes, I have tried to disable scoped style in the vue component but unfortunately it does not seems to have any effect. If you feel more comfortable I can share the code.

**Comment by Norserium** [comment]
> If you feel more comfortable I can share the code.

Yes, please.

**Comment by MattiaFailla** [comment]
Template:
```
<cropper
                classname="cropper"
                :src="img"
                backgroundClassname="cropper-background"
                :stencil-props="{ aspectRatio: 1 }"
                @change="change"
 ></cropper>
```

Script:
```
<script>
import { Cropper } from 'vue-advanced-cropper'

export default {
name: "ImportFloorPlan",
  comments: {
    Cropper
  },
  data() {
    return {
      coords: '',
      img: '../src/assets/img/deposito.svg'
    }
  },
  methods: {
    change({coordinates, canvas}) {
      console.log(coordinates, canvas)
      this.coords = coordinates;
    }
  }
}
</script>
```

Style:
```
<style scoped>
.elastic {
  width:100%;
  height:70vh;
}

.cropper-background {
  color: white !important;
}

/*
	Maybe you need to set the limits for the cropper sizes or its container sizes
	otherwise a cropping image will try to fill all available space
*/
.cropper {
  height: 85vh;
  background: #DDD;
}
</style>
```

**Comment by Norserium** [comment]
It's better to publish code to codesandbox, for example. You save the developer time to check your code by doing this. There is [the example](https://codesandbox.io/s/vue-avanced-cropper-svg-problem-f7qcv).

Notice, that you set `color` property for `.cropper-background` class instead of `background`.

**Comment by MattiaFailla** [comment]
Thank you very much and I apologize for the sandbox. 
The `color` tag was one of the tests to understand if the problem was related to my misconception of the use of the library API.

I modified the example you made in codesandbox applying "`scoped`" to the style, and as you can see now it doesn't work.

[Example code](https://codesandbox.io/s/vue-avanced-cropper-svg-problem-forked-xn8g8?file=/src/App.vue)

**Comment by Norserium** [comment]
> I apologize for the sandbox.

Not problem at all, I'm just trying to popularize this method of code sharing.

> I modified the example you made in codesandbox applying "scoped" to the style, and as you can see now it doesn't work.

Yes, it doesn't. It's [known bug](https://github.com/Norserium/vue-advanced-cropper/issues/65).

**Comment by MattiaFailla** [comment]
> Not problem at all, I'm just trying to popularize this method of code sharing.
>
I absolutely understand, especially if you are trying to keep an open-source project!
> Yes, it doesn't. It's the [known bug](https://github.com/Norserium/vue-advanced-cropper/issues/65).
>
I just missed it! Thanks so much. I'll keep an eye on that issue.

**Comment by Norserium** [comment]
@MattiaFailla, you can use [the following approach](https://codesandbox.io/s/vue-avanced-cropper-svg-problem-scoped-styles-teqtb) now.

**Comment by MattiaFailla** [comment]
@Norserium Thanks!

**Comment by Norserium** [comment]
According the docs:
> With scoped, the parent component's styles will not leak into child components. However, a child component's root node will be affected by both the parent's scoped CSS and the child's scoped CSS. This is by design so that the parent can style the child root element for layout purposes.

So I'm not sure that other way is possible. I should somehow pass the `data` attribute to child element from the root, and I'm not sure that there is right way to do it.

Also you can use [not scoped and scoped styles](https://vue-loader.vuejs.org/guide/scoped-css.html#mixing-local-and-global-styles) in your SFC in the same time.

**Comment by MattiaFailla** [comment]
There is probably no elegant way to do this, but I would suggest you set a default color (eg white) directly in the component or try to see if inherit can work.. 
Eventually this problem occurs with transparent images and is more common have a white background rather than a black one.

**Comment by MattiaFailla** [comment]
![image](https://user-images.githubusercontent.com/11872425/90385347-44554d00-e083-11ea-8ed2-a59a085af076.png)
![image](https://user-images.githubusercontent.com/11872425/90385444-74045500-e083-11ea-840c-45bfb27d0dfa.png)

I have tried the inherit keyword and it seems to work pretty well. 

Do you think it is possible to define a style class directly in the component and set the background to inherit?

**Comment by Norserium** [comment]
> There is probably no elegant way to do this, but I would suggest you set a default color (eg white) directly in the component or try to see if inherit can work..

I can't, because by default the background of cropper and background of area should are different (transparent and black accordingly).

> Eventually this problem occurs with transparent images and is more common have a white background rather than a black one.

Yes, but you will see this background when you resize not transparent image with `imageRestriction` that is not equal to `area`. Look at [the example](https://norserium.github.io/vue-advanced-cropper/tutorials/advanced-recipes.html#different-image-restrictions).

**Comment by phena109** [comment]
I don't mind to use non-scoped style just for the background. But I basically had to read all the related threads in order to work out that is what I should do. A bit of hint in the doc will help immensely.

**Comment by Norserium** [comment]
@phena109, I've added [the styling notice section](https://norserium.github.io/vue-advanced-cropper/tutorials/customize-appearance.html#styling-notice) to "Customize appearance" page.
