### ISSUE TITLE
dynamic ratios do not work with fixed widths

### ISSUE THREAD

**Issue by karelbyte** [Norserium/vue-advanced-cropper#69]
Hello, thank you very much for this great tool, I have a query to clarify, the component I want to give in some cases a minimum and maximum width equal, so that the user does not go beyond the width that I preset, but I want to be able to change the aspect ratio, so that it becomes a square (1), or "rectangle", 3/2, but when I apply the restriction to the width the dynamic ratios stop working! Because this happens, some clue, or clarification
 ```
<cropper
              ref="cropper"
              classname='cropper'
              :src="image"
              :stencil-props="ratio.value"
              @change="onChange"
              :stencil-component="shape"
              :restrictions="pixelsRestriction"
              :min-width="restriction"
              :max-width="restriction"
              :min-height="10"
          ></cropper>
```

**Comment by Norserium** [comment]
@karelbyte is this issue still actual?

**Comment by Norserium** [comment]
@karelbyte, any news?

**Comment by Norserium** [comment]
I close this issue for now. If you have questions, feel free to ask.
