### ISSUE TITLE
How to set the initial size of cropper area?

### ISSUE THREAD

**Issue by jonalxh** [Norserium/vue-advanced-cropper#70]
Hi, I want to define an initial size of the cropper, my images resolutions may vary, but I want the cropper initially has 800px width and 300px height, I've set it in restriction but it shows me an initial size bigger.

```
imgPixelsRestriction({ minWidth, minHeight, maxWidth, maxHeight, imageWidth, imageHeight }) {
			return {
				minWidth: 800,
				minHeight: 300,
				maxWidth: 1900,
				maxHeight: 580,
			};
		},
```

How to set the initial size according to my requirements?

**Comment by Norserium** [comment]
Hello, @jonalxh. Do you want to set the initial width of [cropper or its stencil](https://norserium.github.io/vue-advanced-cropper/introduction/concepts.html#cropper)?

**Comment by jonalxh** [comment]
The concepts are a little strange for me because I'm not English speaker, but what I need is to set the size of default selected area, like in the picture below: 
 ![image](https://user-images.githubusercontent.com/12530606/91772813-36d3b300-ebab-11ea-834f-45f0f1570f6b.png)

**Comment by Norserium** [comment]
I don't understand you clearly, but did you see this [example](https://norserium.github.io/vue-advanced-cropper/tutorials/advanced-recipes.html#default-size-and-position) (Default size and position)?

**Comment by jonalxh** [comment]
Yeah, that's it, thanks a lot, I've not seen this example.

Can you tell me how to set the default width to 100% of the img?

**Comment by Norserium** [comment]
You can use this approach:
```js
defaultSize({ imageWidth, imageHeight }) {
	return {
		width: imageWidth,
		height: imageHeight ,
	};
}
```

It will be deprecated soon, but it is only one way do it by this method now. As an alternative you can use `setCoordinates` method to set default size.

**Comment by jonalxh** [comment]
Thanks a lot, It worked like a charm.
