### ISSUE TITLE
.setCoordinates Issue, top value is not being recognised as a number when passed in

### ISSUE THREAD

**Issue by CraigWallsauce** [Norserium/vue-advanced-cropper#71]
My code sets the width and height from inputs, my code:

this.$refs.cropper.setCoordinates({
          width: parseInt(this.width),
          height: parseInt(this.height),
          top: parseInt(10),
          left: parseInt(10)
})

The top value is always NaN in your cropper component no matter what I pass in.

**Comment by Norserium** [comment]
Hello, @CraigWallsauce! Could you provide the codesandbox for your problem? What are `this.width` and `this.height` values?

**Comment by CraigWallsauce** [comment]
I replaced my values in the submitted code, the original was:

this.$refs.cropper.setCoordinates({
width:parseInt(this.customermural.customerwidth),
height:parseInt(this.customermural.customerheight),
top:parseInt(10),
left:parseInt(10)
         })

I have tried with and without parseInt.

A working sample which isn't complete can be found at:

https://dev1.wallsauce.com/wall-murals-wallpaper/dinosaur-hunting-mural-wallpaper

Add values to the width and height fields.

Regards

Craig

**Comment by Norserium** [comment]
You shouldn't set the coordinates until you define both `this.customermural.customerwidth` and `this.customermural.customerheight`.

When you change width, `croppersetsize` is called and you set width correctly (`parseInt(100) = 100`), but you set height incorrectly (`parseInt("") = NaN`).

**Comment by CraigWallsauce** [comment]
Thank you, I have amended my code and it appears to be working correctly now

**Comment by Norserium** [comment]
@CraigWallsauce, you are welcome!
