### ISSUE TITLE
Support vue 3

### ISSUE THREAD

**Issue by bzd2000** [Norserium/vue-advanced-cropper#72]
Hello,

Is there any plan to foresee a next branch for vue 3?

thx,
Filip

**Comment by Norserium** [comment]
Hello, @bzd2000. I've not tried yet this library with Vue 3. Have you encountered any troubles?

**Comment by bzd2000** [comment]
Yes, it doesn't work currently.

There are some breaking changes -> https://v3.vuejs.org/guide/migration/introduction.html#overview
(also plugin system changed)

I managed to copy the Cropper component (with all sources) in a vue 3 project and with some minor adjustments it seems to work in my use case. So I think it want be a huge work to migrate it.

I forked your project and try to update all necessary dependencies to vue 3, but got stuck on the rollup config.
It cannot load the the scss part of the vue files for some reason.  Maybe due some of the rollup-plugins it uses.

So if you would be able to create an next branch, I could merge it with updated dependencies and then you could maybe check what is wrong.

kr,
Filip.

**Comment by Norserium** [comment]
I will try to preserve one branch and save backward compatibility. But I need time to investigate this problem, so I think I delay this task to next weekends.

**Comment by Norserium** [comment]
@bzd2000 the version of `rollup-plugin-vue` compatible with the next version of Vue is in the beta stage. It has at least one 
 [the painful issue](https://github.com/vuejs/rollup-plugin-vue/issues/364) right now.

**Comment by bzd2000** [comment]
ok :)
that was exact the issue I had too

**Comment by phena109** [comment]
Seems like they have 1 commit related to style since beta 9 (beta 11 as of now). Also there is a mention [vite](https://github.com/vitejs/vite#readme).

**Comment by phena109** [comment]
I am sorry, I think `rollup-plugin-vue` actually just got out of beta. It's 6.0.0 now. The setting in the `rollup.config.js` should have the plugin portion like this (sort of explained in the readme of the plugin).
```
Vue({
    preprocessStyles: true
}),
```

Then you will change the index.js to adopt the new vue 3 way (`createApp()` etc.).

On my computer, it compiles fine, passed all test as a standalone and compiles fine in my own project, too. But it started to throw errors when I really make use of the library. I hope this is just my project and I will continue to check.

**Comment by alekbarszczewski** [comment]
For me importing vue-advanced-cropper in ionic/vue3 project breaks the app (without any specific errors logged to the console).

**Comment by Norserium** [comment]
I've started work on [the adaption to breaking changes in Vue 3](https://github.com/Norserium/vue-advanced-cropper/tree/vue-next). It works already now, but it's pretty raw, just like the ecosystem of the last Vue version.

**Comment by Norserium** [comment]
@bzd2000, @phena109, @alekbarszczewski finally, it has arrived. The vue-advanced-cropper is available for Vue 3 now.
```bash
npm install --save vue-advanced-cropper@next
```
```bash
yarn add vue-advanced-cropper@next
```
Examples: [Bundler](https://codesandbox.io/s/vue-advanced-cropper-vue-3-yrxou?file=/src/App.vue) / [CDN](https://jsfiddle.net/norserium/w5o7z6ts/)

**Comment by Norserium** [comment]
@bzd2000, @phena109, @alekbarszczewski, I close the issue. If you encounter any troubles, feel free to create the specific issue.

**Comment by bzd2000** [comment]
Thx for the work!
