### ISSUE TITLE
Background positioning issues with mobile camera image

### ISSUE THREAD

**Issue by zSoulweaver** [Norserium/vue-advanced-cropper#78]
Having an issue with mobile camera uploads, specifically it's a Samsung Galaxy S20+, although I can use a photo from my older S8 and the issue persists. I'm able to drop the image into photoshop, re-save, and it works, I'm also able to strip the exif data and it works fine (although no longer rotated correctly).

I'd imagine it has something to do with the exif orientation of the image, it's just not positioning correctly for the background, but the cropped selection seems correct, see the video below for a visual.

https://streamable.com/yotszi

Picture of issue, courtesy of fluffy white dog
![image](https://user-images.githubusercontent.com/11328975/93042876-95ad2800-f693-11ea-91da-2b09f04551f2.png)

**Comment by Norserium** [comment]
@zSoulweaver, could you transfer me that image (archived)?

**Comment by zSoulweaver** [comment]
@Norserium I yoinked all the exif data from it except for the orientation, issue is still persisting so it should reproduce on your side. https://1drv.ms/u/s!Am6aenL1_cmUkUXX0PmPieRBUt3S?e=jUIaCd

Cheers!

**Comment by Norserium** [comment]
@zSoulweaver, could you update to `0.17.3` and check? Nice puppy by the way!

**Comment by zSoulweaver** [comment]
@Norserium Can do, as soon as I get home from work, I'll give it a go and close the issue if it's all g. 

Cheers for the fast work

**Comment by kramalexx** [comment]
Hello @Norserium! I met the same issue when I try to use vertical image in the cropper. I see this problem even on the demo page. Look at the example below

<img width="684" alt="Снимок экрана 2021-01-26 в 15 59 07" src="https://user-images.githubusercontent.com/42442717/105848056-86e66280-5fef-11eb-8ac0-79528c7c2fef.png">

**Comment by Norserium** [comment]
@kramalexx, it's completely my fault. There is the bug in `1.2.3`. Please  update to `1.2.5`.

**Comment by kramalexx** [comment]
Thanks for the reply, but unfortunately it still looks the same even with the version `1.2.5`.

![image](https://user-images.githubusercontent.com/42442717/105955869-0162c100-6088-11eb-818d-fe7f343d8097.png)

I use the image below to test. Maybe it will be useful to you
![image](https://user-images.githubusercontent.com/42442717/105955971-23f4da00-6088-11eb-8907-66001b003618.png)

**Comment by Norserium** [comment]
It works just fine:
![image](https://user-images.githubusercontent.com/9862719/105992132-c4adbe80-60b5-11eb-892c-6593b036ec95.png)

Could you test your image in [this sandbox](https://codesandbox.io/s/vue-advanced-cropper-rotate-2-k37kl?file=/src/App.vue)?

**Comment by Norserium** [comment]
@kramalexx I've updated the documentation also.

**Comment by kramalexx** [comment]
@Norserium It was the problem not with the .js file, but with .css. So I updated the styles to version 1.2.5 and the issue was gone. Thanks a lot!

**Comment by Norserium** [comment]
@kramalexx you are welcome!
