### ISSUE TITLE
Maximize cropper on image

### ISSUE THREAD

**Issue by Nemesis19** [Norserium/vue-advanced-cropper#79]
Dear Norserium,

I'm sorry to use the repo issue to ask a support question, but I can't find any answers to these questions:

1. how can I maximize the cropper rectangle stencil till the border of the image? I set a cropper like here below to have a fixed draggable square only. But on images with 4:3 proportions the cropper doesn't reach the edges. I expect to have a square from left to right border in a portrait photo and from top to bottom border in a landscape picture.

```
<cropper
				v-if="file && !isRepost"
				ref="cropper"
				class="dg_cropper"
				:src="file._url"
				:touch-resize="true"
				:wheel-resize="false"
				:stencil-props="{
					aspectRatio: 1/1,
					handlers: {
						eastNorth: true,
						north: false,
						westNorth: true,
						west: false,
						westSouth: true,
						south: false,
						eastSouth: true,
						east: false
					},
					linesClasses: {
						default: 'dg_cropper-line'
					},
					handlersClasses: {
						default: 'dg_cropper-handler',
						eastNorth: 'dg_cropper-handler--east-north',
						westNorth: 'dg_cropper-handler--west-north',
						westSouth: 'dg_cropper-handler--west-south',
						eastSouth: 'dg_cropper-handler--east-south',
					},
				}"
				@change="onChange">
```

2. in your rectangle stencil page under section "Service props" you mention "You should not pass this props to stencil, they are passed by cropper itself". Opening the inspector I see the code as below, but I don't understand if the cropper is doing something wrong or I'm missing something here. The cropper seems to work perfectly but I'm wondering why this code in html.
![Schermata 2020-09-15 alle 23 17 32](https://user-images.githubusercontent.com/5808262/93266032-ca130800-f7a9-11ea-82c3-94624b27e0e1.jpg)

Many thanks! Please close if inappropriate.

**Comment by Norserium** [comment]
Hello, @Nemesis19! 

1. Could you provide [codesandbox](https://codesandbox.io/s/vue-avanced-cropper-basic-jfy5w) for the first question and the corresponding image?

2. The cropper passes `result-coordinates` prop to stencil, but `RectangleStencil` doesn't have `result-coordinates` in its props, so it's used as html attribute. I will fix this problem in the future.

**Comment by Norserium** [comment]
If you encounter problems with extracting your code to codesandbox you can provide the screenshots with actual and desired results.

**Comment by Nemesis19** [comment]
Hello, thanks for your quick reply.

Ok for question number 2, I can just ignore the thing then.

About question number 1 I could not easily make a working sandbox and I have some proprietary code that I can't expose. What I can tell you is that once the cropper gets rendered in my component **mounted** I do this.

```
if (this.$refs.cropper) {
				// set cropper to square dimension and full size of canvas
		
					this.$refs.cropper.setCoordinates((coordinates, imageSize) => ({
						width: imageSize.width,
						height: imageSize.height,
						left: imageSize.width / 6,
          }));
  			}
```

this works perfectly for 16:9 images made with my iphone but when I use a 4:3 and not all the 4:3 photos. So when I upload with a input file the image, I run that code to set the cropper size on the image.

Now I made several try and it seems the issue is only with one particular photo and one particular size. I made some test and it's not happening again.

Maybe you can just comment if that code is a good way to set the stencil size. Otherwise we can close the issue.

Thanks for your help

**Comment by Norserium** [comment]
Could you provide the screenshots with actual and desired results?

**Comment by Nemesis19** [comment]
Sure.

So far these are good, look at the orange cropper, please forgive the red boxes I put on the photos:

![Schermata 2020-09-15 alle 23 47 21](https://user-images.githubusercontent.com/5808262/93269529-6db2e700-f7af-11ea-98a2-11f161957b9e.jpg)
![Schermata 2020-09-15 alle 23 59 15](https://user-images.githubusercontent.com/5808262/93269627-a9e64780-f7af-11ea-8fb0-288d8e5da0c8.jpg)

this is not:
![Schermata 2020-09-15 alle 23 59 31](https://user-images.githubusercontent.com/5808262/93269675-c2566200-f7af-11ea-9f26-e260f6949a19.jpg)

After further investigation the last image has a weird size that I cannot reproduce because all my iphones cameras front and back are now making photos that the cropper parse as in the first 2 screens.

I'm really sorry because I also made random screenshots on my mac and given to the cropper but it's working everything as intended except for that picture mentioned earlier.

**Comment by Norserium** [comment]
You shouldn't be sorry, it's all right. 

If I understood you correctly you should pass the following function to `default-size`:
```js
defaultSize({ imageSize }) {
   const size = imageSize.width > imageSize.height ? imageSize.height : imageSize.width;
   return {
       width: imageSize.width,
       height: imageSize.height,
   }
}
```

[The codesandbox](https://codesandbox.io/s/vue-advanced-cropper-changed-default-size-ryjv7?file=/src/App.vue).

**Comment by Nemesis19** [comment]
Your sandbox is perfect, in my case firefox complains that

`Warning: the default size breaks size restrictions. Check your defaultSize function 
Object { width: 2954, height: 2954 }
 Object { minWidth: 0, minHeight: 0, maxWidth: 2954, maxHeight: 2202.4522968197884, minimum: 0 }`

**Comment by Nemesis19** [comment]
I consider this issue as solved, I don't think the problem with that picture is worth any investigation.

Thank you very much again!

**Comment by Norserium** [comment]
@Nemesis19, I suppose, that you pointed out the unknown bug. It's strange, that I can reproduce it only in production release. I will investigate and fix it the next releases.
<details>
  <summary>The image to reproduce</summary>
  <img src="https://user-images.githubusercontent.com/9862719/93275099-a5785980-f7c4-11ea-9240-48acfd8a0720.png">
</details>

**Comment by Norserium** [comment]
@Nemesis19 could you check if your error reproduces in `0.17.4`?

**Comment by Nemesis19** [comment]
@Norserium I've been trying with your yellow image and my image with the new version. It seems the issue still occurs.

I'm really sorry that I can't help more than this. If you were able to reproduce it and in .4 it's fixed, I believe it's fixed.

If you still desire to dig deeper I'm sorry but I can't give you the component code here in public. We need to reach out privately and I'll need to white label it.

Thanks in any case for the effort!

**Comment by Norserium** [comment]
@Nemesis19, I can't reproduce this bug in the documentation examples with this image anymore. Are you sure, that you have updated the package version? Could you provide the console error?

**Comment by Nemesis19** [comment]
I have 0.17.4 and the console error is gone. I can just tell you that on component init this piece of code

```
this.$refs.cropper.setCoordinates((coordinates, imageSize) => ({
						width: imageSize.width,
						height: imageSize.height,
						left: imageSize.width / 6,
					}));
```

that I'm using procuces these two outputs in console:

```
coordinates {
  "left": 375.7738515901058,
  "top": 879.7738515901058,
  "width": 2202.4522968197884,
  "height": 2202.4522968197884
}
```

and 

```
imageSize
![Schermata 2020-10-23 alle 18 45 11](https://user-images.githubusercontent.com/5808262/97030993-e439c600-155f-11eb-8c49-e6db65746e16.jpg)
```

**Comment by Norserium** [comment]
I've create [the codesandbox](https://codesandbox.io/s/vue-advanced-cropper-example-6ui34?file=/src/App.vue), that should reproduce your problem. But I can't reproduce it.

**Comment by Nemesis19** [comment]
I don't remember why I used setCoordinates, maybe defaultSize has been introduced later?

Anyway, I think I've found the problem. I'm giving to te cropper component a `max-height: 40vh;` because it's a mobile UI and I can't give to the wrapper the whole page.

I disabled it because it was something absent from your both examples given. Disabling it now the cropper works as intented with my original image and your yellowish one.

Any workaround that you can suggest to both have a max-height but working with those pictures too?

I tried to apply that style to the parent div but the cropper keeps enlarging in height going beyond the max space it should take.

In the end it seems there is some incompatibility between css, cropper and image sizes.

many many thanks!

**Comment by Norserium** [comment]
I'm not sure that it's the reason. Look, I've added [the height limitation to my example](https://codesandbox.io/s/vue-advanced-cropper-example-6ui34?file=/src/App.vue). The problem is not reproducing.

**Comment by Nemesis19** [comment]
No modal....here you can find my reproduction https://codesandbox.io/s/vue-advanced-cropper-example-forked-ffy58

I changed some code with the one I use....forget about the `if (this.coordinates && this.coordinates.width) {` because in that page I move to another to add details to an object in vuex, so when I get back to the cropper page if I saved the coordinates I set it again on the cropper to start from where have been left. Anyway that code doesn't create any problem because it happens on first load of the image.

This is the procedure I do:
1. I have one component with an input file
2. the file gets stored in vuex
3. from vuex I pull the file to give it the cropper

I'm sorry but I have no clue to how to test anymore. Even with my code and without the default size it seems to work.

I have notices that if in my example I re-upload the yellow image, the cropper gets smaller, but I can always enlarge it. Instead in my real code I can't resize to the border. The cropper seems to be blocked to that dimension.

**Comment by Norserium** [comment]
Could you replace using `init` method by using `defaultSize` prop? I suppose it's the problem.

**Comment by Nemesis19** [comment]
I commented all the content of the init() method and added exactly your method defaultSize as from your examples and indeed the prop to the <cropper> element.

Unfortunately no changes...I'm sorry man.

**Comment by Norserium** [comment]
Did you add `default-size="defaultSize"` line to your cropper template definition?

**Comment by Nemesis19** [comment]
Yes, as I said earlier "and indeed the prop to the element."

**Comment by Norserium** [comment]
I suppose I've reproduced your problem. Thanks. But I need sime time to investigate it.

**Comment by Nemesis19** [comment]
Many thanks to you! Can you explain more or less what could you understand?

**Comment by Norserium** [comment]
Currently I understand that this problem is pretty random. I suppose it can be associated with the order of recalculation computed properties inside my cropper.

I need to reproduce this bug locally now.

**Comment by Norserium** [comment]
@Nemesis19 try to update to `0.17.6`.

**Comment by Nemesis19** [comment]
Awesome, solved! 🎉

Thank you very much!

**Comment by Norserium** [comment]
The problem finally solved. Nice! 

I close issue then.
