### ISSUE TITLE
Your size break the restrictions. Check your default size function

### ISSUE THREAD

**Issue by isferrei** [Norserium/vue-advanced-cropper#81]
Hello team,

I'm facing an issue when opening my pop-up to crop my images using this component. Please take a look on bellow image:
![image](https://user-images.githubusercontent.com/54048443/96604177-2e564980-12cb-11eb-964c-15b90313e8e1.png)

this is my default size function
`  defaultSize(currentIndex) {
      console.log(this.coordinates.width)
      console.log(this.coordinates.height)
      return {
        width: 300,
        height: 100,
      }; 
`
this is the crop compponent:
```
 <div v-if="secoesData[currentIndex] != null && secoesData[currentIndex].layout == 1 && secoesData[currentIndex].conteudo.length == 1">
                        <cropper 
                          classname="cropper" 
                          :src="image" 
                          :min-width="640" 
                          :max-width="640" 
                          :size-restrictions-algorithm="pixelsRestriction" 
                          ref="cropper" 
                          @change="onChange" 
                          image-restriction="stencil"
                          :touchResize="true"
                          ready
                        ></cropper>
                      </div>
                      <div v-if="secoesData[currentIndex] != null && secoesData[currentIndex].layout == 2 && secoesData[currentIndex].conteudo.length == 1">
                        <cropper 
                          classname="cropper" 
                          :src="image" 
                          :size-restrictions-algorithm="pixelsRestriction" 
                          ref="cropper"
                          @change="onChange"
                          :touchResize="true"
                        ></cropper>
                      </div>
                      <div v-else>
                        <cropper 
                          classname="cropper" 
                          :src="image"
                          ref="cropper"
                          :default-size="defaultSize"
                          :stencil-props="{
                            handlers: {},
                          }"
                          @change="onChange"
                          :movable="true"
                          image-restriction="stencil"
                        ></cropper>
                      </div>
```

**Comment by Norserium** [comment]
Hello, @isferrei! I'm investigating this problem. Alas, September and October was pretty hard for me, so I didn't have time for my library.

**Comment by Norserium** [comment]
@isferrei could you provide the image that causes this problem?

**Comment by Norserium** [comment]
It's pretty suspicious, that `minWidth` is equal to `2304` on your screenshot. What's one of three croppers causes the problem on the screenshot?

**Comment by isferrei** [comment]
> It's pretty suspicious, that `minWidth` is equal to `2304` on your screenshot. What's one of three croppers causes the problem on the screenshot?

I didn't have a chance to upload any image, it came to me when I opened my modal that contains the crop component
![image](https://user-images.githubusercontent.com/54048443/96617997-b728b180-12da-11eb-987a-cd28ce8242c0.png)

**Comment by Norserium** [comment]
@isferrei, could you update to `0.17.4`? Then, please, tell me what's one of three croppers above causes this error.

**Comment by Norserium** [comment]
@isferrei, any news?

**Comment by Norserium** [comment]
@isferrei, any news?

**Comment by Norserium** [comment]
@isferrei this issue should be fixed now. If you encounter this problem after update, feel free to reopen the issue.
