### ISSUE TITLE
Stencil breaks restriction when zooming

### ISSUE THREAD

**Issue by yusuf-io** [Norserium/vue-advanced-cropper#82]
Hi,
I am working on building cropper for my Vue 2 app, but by using the latest version` vue-advanced-cropper@0.17.4`  the stencil seems break the restriction and overflows outside the cropper when zooming. Pls check out the codesand link:
[](url)https://codesandbox.io/s/advance-vue-cropper-4gc1o
BTW, the bug is fixed when using` vue-advanced-cropper@0.17.3`

**Comment by Norserium** [comment]
Hello, @yusuf-io! It's fixed in `0.17.5`. I've picked in this release some changes from the upcoming big release.

**Comment by yusuf-io** [comment]
Thank you for fixing the issue, it works fine with the new release.

**Comment by Norserium** [comment]
Nice. I close issue then.
