### ISSUE TITLE
Weird issue with images in documentation

### ISSUE THREAD

**Issue by hbalenda** [Norserium/vue-advanced-cropper#83]
Hi there, the image examples in the documentation & sandbox featuring scantily clad women should be replaced if you wish to be perceived as professional. Women do not like being reminded that they live in a society that objectifies and sexualizes them constantly :) Thank you!

**Comment by Norserium** [comment]
Hello, @hbalenda!

There are a large variety of different cultures in the world. Therefore I can assume that in your culture some of used images were inappropriate.

To avoid similar claims in the future I would have to use only simplest neutral images for the documentation. For example, only geometric figures (with caution anyway). But I want to avoid it to preserve individuality and brilliance of the documentation. 

Thus we are in the complex situation here. However, the set of used images is constantly changing and I hope that the images in the newest and future editions won't provoke your protest.

I should note also that the set of documentation images is the least of my library issues anyway.
