### ISSUE TITLE
One of the worst documentation ever! Incomplete examples and bad explanation! Thanks!

### ISSUE THREAD

**Issue by enoh-barbu** [Norserium/vue-advanced-cropper#84]

**Comment by Norserium** [comment]
Hello, @enoh-barbu! 

Welcome to the open source. This documentation is written by me. I don't receive any financial support and do it on my own, so I don't have enough time to make it perfect. Moreover, it's the beta version and this library is still in the development as well as its documentation.

So instead of indiscriminate criticism, I suggest you to write an specific comments, what should be improved. It would be very helpful for our community.

**Comment by enoh-barbu** [comment]
I got crazy last night trying to make it working, spent about 3 hours on that, still no results. I understand your statements and agree with them, but in my opinion, this should not go live if the job is half done. I won't put more details. Just wanted to release my stress out here.

**Comment by Norserium** [comment]
@enoh-barbu there are two kinds of people in the world: who knows how to do things right and who do things. Besides, it's impossible to make the documentation that will be clear for all users without its beta testing. To facilitate their lives I don't mind if users asks their questions in issues in this situation, I try to reply them quickly enough.

>  I won't put more details.

Why? Just describe your problem in a nutshell.

**Comment by enoh-barbu** [comment]
**PreviewResult** is nowhere documented. In code examples seems to accept an image which should be an object?? with what properties? How the image can be passed to that? This is just an example, but again, I won't put more work on your belt as I understand you're doing in your spare time.

**Comment by Norserium** [comment]
@enoh-barbu, first of all, `PreviewResult` is the service component used to display the image in the stencil component. The `img` is object, indeed, and it's passed to this component by cropper itself. Did you want to create the custom stencil?

**Comment by Norserium** [comment]
I suppose that this fragment of documentation misled you:
![screenshot](https://user-images.githubusercontent.com/9862719/99059953-5a09de00-25b0-11eb-9185-c9194811e36c.png)

It's pretty rare situation when it will be needed you (only for custom stencil),

**Comment by enoh-barbu** [comment]
I just tried to copy paste the last code example from [here](https://norserium.github.io/vue-advanced-cropper/guides/custom-stencil.html) 
I've created a component for that. I need to pass my image. I get this Invalid prop: type check failed for prop "img". Expected Object, got String with value "blob

**Comment by enoh-barbu** [comment]
Oh, so PreviewResult is that image on the right side, you've showed above....great! I just now barely understood what it does!

**Comment by Norserium** [comment]
> Oh, so PreviewResult is that image on the right side, you've showed above....great! I just now barely understood what it does!

No, no. It's the service component, that is used in the stencil.

> I've created a component for that. I need to pass my image. I get this Invalid prop: type check failed for prop "img". Expected Object, got String with value "blob

You cannot pass image to this stencil directly, it's the stencil, not cropper. I suppose you should need take a look at [the full example](https://codesandbox.io/s/vue-advanced-cropper-custom-stencil-omseq?file=/src/Stencil.vue).

The stencil code is in `Stencil.vue`, the cropper code is in `App.vue`.

**Comment by Norserium** [comment]
Anyway, what did you want to get exactly? The cropper with this specific circle?

**Comment by enoh-barbu** [comment]
I thought the code above is to have this result
![image](https://user-images.githubusercontent.com/24221572/99079255-5e41f580-25c8-11eb-990c-79ac03ca4894.png)

**Comment by enoh-barbu** [comment]
> at [the full example](https://codesandbox.io/s/vue-advanced-cropper-custom-stencil-omseq?file=/src/Stencil.vue).
now this makes sense

**Comment by Norserium** [comment]
> I thought the code above is to have this result

Now I understand that it's not obvious at all. I will try to make it more clear to users and provide the link to that codesandbox (I suppose, that similar codesandboxes will be useful for other examples too). 

Thanks.

**Comment by enoh-barbu** [comment]
that will make it easier! thanks! sorry for the hard words

**Comment by Norserium** [comment]
All's well that ends well. I hope that my library helped you to solve your task.

**Comment by yogsky** [comment]
> > at [the full example](https://codesandbox.io/s/vue-advanced-cropper-custom-stencil-omseq?file=/src/Stencil.vue).
> > now this makes sense

I believe this example now include a bug where if you try first to resize the stencil (not drag it), stencil is stuck and cannot move afterwards.

**Comment by Norserium** [comment]
@yogsky, thank you! It's fixed now.

**Comment by yogsky** [comment]
@Norserium 🥇 
First off, thanks a lot (also for the awesome package).
May I ask what was the needed change that you made 🤓 ?

**Comment by Norserium** [comment]
My pleasure. 

In the previous versions `ResizeEvent` received three arguments, include the native event. I decide, that the first argument (i.e. event) is redundant, because I can't rely on event, that user passes, so it was removed in the new versions. 

To fix this problem I just removed the passing of the native event as the first argument of `ResizeEvent` constructor (line 50).

**Comment by yogsky** [comment]
@Norserium, 
got it, Thank you! ❤️

**Comment by Elvincth** [comment]
Would be nice to add a search bar to the documantaion!
