### ISSUE TITLE
Change method name in input tag from Load image from disc section

### ISSUE THREAD

**Issue by dishantsethi** [Norserium/vue-advanced-cropper#85]
Since the method name is uploadImage(event), The method called inside input tag should also be uploadImage() instead of loadImage()

![Screenshot from 2020-11-13 14-12-58](https://user-images.githubusercontent.com/31399916/99047598-6eeb6f00-25ba-11eb-9e63-3d12cc42b987.png)
![Screenshot from 2020-11-13 14-13-07](https://user-images.githubusercontent.com/31399916/99047611-714dc900-25ba-11eb-8352-a11b0f09ee8f.png)

**Comment by dishantsethi** [comment]
Create a Pull request for the same https://github.com/Norserium/vue-advanced-cropper/pull/86

**Comment by Norserium** [comment]
@dishantsethi I've merged it. The changes are published now.

**Comment by dishantsethi** [comment]
Thank You @Norserium
