### ISSUE TITLE
PNG images with transparency, will be converted to black

### ISSUE THREAD

**Issue by enoh-barbu** [Norserium/vue-advanced-cropper#87]
Original image
![image](https://user-images.githubusercontent.com/24221572/99111634-29986300-25f5-11eb-958e-0245b902e7ab.png)

uploaded image

![image](https://user-images.githubusercontent.com/24221572/99111614-20a79180-25f5-11eb-8328-2f6213800699.png)

try it [here ](**https://codesandbox.io/s/vue-advanced-cropper-custom-stencil-omseq?file=/src/Stencil.vue**)

**Comment by Norserium** [comment]
@enoh-barbu, cropper background is black by default and you see it (#66). The default background may be changed in the future major release, but I should investigate the advantages and disadvantages of any alternative. 

But for now feel free [to change it](https://codesandbox.io/s/vue-advanced-cropper-customize-background-lbwmx?file=/src/App.vue).

**Comment by Norserium** [comment]
@enoh-barbu, there is two aspects.

Cropper background is black by default and you see it (#66). The default background may be changed in the future major release, but I should investigate the advantages and disadvantages of any alternative. The good news, that you are able to change the background if you want.

But it's just the visual aspect. When you click crop image you indeed receive the image with black background, but the only reason of it, that when `toDataURL` method is called the parameter `image/jpeg` is passed to it. It's nothing to do with cropper, it's just specific of this codesandbox example (converting to jpeg reduces the result image size).


Both of problems are solved [here](https://codesandbox.io/s/vue-advanced-cropper-customize-background-lbwmx?file=/src/App.vue).

**Comment by enoh-barbu** [comment]
Ok, problem solved. I'll close this then, 10x
