### ISSUE TITLE
What if we want to let image be nullable

### ISSUE THREAD

**Issue by matinwd** [Norserium/vue-advanced-cropper#89]
How can we let image as nullable?
when i leave it null it says "can't access property "left", e is null"

**Comment by Norserium** [comment]
@matinwd, when does this error appear? On calling `getResult`?

**Comment by matinwd** [comment]
Yes

**Comment by Norserium** [comment]
I am going to fix the error, but what do you await to receive on calling this function? It will return just:
```js
{
    visibleArea: null,
    coordinates: { left: 0, top: 0, width; 0, height: 0 }
}
```

**Comment by Norserium** [comment]
This error is already fixed in `0.17.9`. Please check it.

**Comment by matinwd** [comment]
Updated
Thanks

**Comment by Norserium** [comment]
Did it solve your problem?

**Comment by matinwd** [comment]
Actually no
because what if we want to send form with or without cropped image? 
the way you made we only can send form with image

**Comment by matinwd** [comment]
that is because of blob callback function

**Comment by Norserium** [comment]
> the way you made we only can send form with image

No, it's not. You always can process the case when `image` is null separately.

Could you provide the code of your submit function?

**Comment by matinwd** [comment]
![2020-11-21_14-54-11](https://user-images.githubusercontent.com/52950867/99876039-75f12d80-2c09-11eb-9f95-b807081cc494.png)

and with the code i sent you here, there will not any image in the request

**Comment by matinwd** [comment]
![2020-11-21_14-55-52](https://user-images.githubusercontent.com/52950867/99876110-d1232000-2c09-11eb-9bc3-59a41f7b3156.png)

and if i do like this, i can not send form without image

**Comment by Norserium** [comment]
It's the normal behavior, because `canvas.toBlob` is an asynchronous operation, and you submit the form before this operation is completed.

There are plenty of different ways to implement the desired behavior. The most simple is [here](https://codesandbox.io/s/vue-advanced-cropper-load-upload-2-zkd2u?file=/src/App.vue).

**Comment by matinwd** [comment]
solved thanks

**Comment by Norserium** [comment]
You are welcome!
