### ISSUE TITLE
TypeError: Property 'handleEvent' is not callable in Firefox

### ISSUE THREAD

**Issue by gustavomelki** [Norserium/vue-advanced-cropper#9]
Hi Norserium! I'm getting an error in console after selecting the image and passing the cursor over the document, just in Firefox: 

`TypeError: Property 'handleEvent' is not callable.`

I'm using the last version 0.12.2.

Please, can you help?

**Comment by Norserium** [comment]
Hello! Could you provide the minimal working example or video that illustrates problem?

**Comment by gustavomelki** [comment]
I found the problem, there is not related to your library. It is related to Sentry, running in my application: https://forum.sentry.io/t/undefined-event-listener-results-in-property-handleevent-is-not-callable-error/4315

Thank you for the quick support.

**Comment by Norserium** [comment]
You are welcome!
