### ISSUE TITLE
How I can show only stencil (visible area) and hide the rest of image?

### ISSUE THREAD

**Issue by alekbarszczewski** [Norserium/vue-advanced-cropper#91]
On mobile devices I want to make stencil (visible image area) to be 100% of screen width, and hide the rest of image (and black borders). I am talking about variant where you don't move stencil, only image.

```vue
<cropper
   :src="value.url"
   :stencil-props="{
      handlers: {},
      movable: false,
      scalable: false,
      aspectRatio: 1,
    }"
    default-boundaries="fill"
    image-restriction="stencil"
/>
```

Right now it looks like this:

<img width="471" alt="photo" src="https://user-images.githubusercontent.com/2742373/100938469-00cd0480-34f5-11eb-8153-dce111ad622a.png">

But I would like it like this:

<img width="368" alt="image" src="https://user-images.githubusercontent.com/2742373/100938087-5a80ff00-34f4-11eb-9a78-7ff02658afb7.png">

**Comment by Norserium** [comment]
@alekbarszczewski, I'm not sure that I understand you exactly. Let's try to make it gradually. Is[ this example](https://codesandbox.io/s/confident-firefly-uvkis?file=/src/App.vue) close to your desired result?

**Comment by Norserium** [comment]
Do you have the example of similar cropper?

**Comment by alekbarszczewski** [comment]
@Norserium yes, it's very close, just would like to get rid of black borders/margins on top and bottom.
What I want to achieve is same as in Instagram application - when you edit / adjust photo you see only visible square on the screen - the rest of the image is hidden.

**Comment by Norserium** [comment]
@alekbarszczewski are you referring to this window?
![image](https://user-images.githubusercontent.com/9862719/100988347-b08b8c00-3560-11eb-91ca-73e441ce00f3.png)

You should note, that visible area in their case may be larger than image, so you would see the borders (in their case white borders).
![image](https://user-images.githubusercontent.com/9862719/100988602-f47e9100-3560-11eb-8bc8-9139743cc23b.png)

**Comment by Norserium** [comment]
Is [this example](https://codesandbox.io/s/vue-advanced-cropper-instagram-like-d3gi9?file=/src/App.vue) close to your desired result?

It's the most simple approach to implement stretching. But it has some limitations: for example, it's pretty hard to set limitation of minimum and maximum width/height.

The solution is very simple:
1. Set the cropper width equal to width of container.
2. Set the cropper height equal to its height (by padding trick).
3. Set that boundaries fill the cropper.
4. Set that visible area should calculates before coordinates (by `priority` prop). It will have the same proportions as boundaries by the way (i.e. 1/1).
5. Set that default size should be equal to visible area.

The more advanced approach is the redefining of  `default-visible-area`, `fit-visible-area` and `fit-coordinates` algorithms.

**Comment by alekbarszczewski** [comment]
Thank you! This is exactly what I need!
Great library btw.

**Comment by Norserium** [comment]
You are welcome!

**Comment by alekbarszczewski** [comment]
@Norserium Hey, I still have one more problem with your approach / example.
In my app it must be possible to edit cropped area - AFAIK normally you do this with `default-size` and `default-position` properties like in one of your examples. However `default-size` is already defined (as per your example) to fill visible area:

```ts
/* :default-size="fillArea"
const fillArea = ({ visibleArea }: { visibleArea: { width: number, height: number } }) => {
      return {
        width: visibleArea.width,
        height: visibleArea.height,
      }
    }
```

When I change this to some other value it breaks stencil (stencil position is correct, but it's no longer centered and it does not fill parent).

https://codesandbox.io/s/vue-advanced-cropper-instagram-like-forked-9q134

I guess another position trick is needed to make it work but so far I couldn't figure it out.

**Comment by Norserium** [comment]
What do you mean by "editing cropped area"? Do you want to set default size and default position?

**Comment by alekbarszczewski** [comment]
Thanks,
I couldn't find it (`default-visible-area`) because in docs this prop is missing (https://norserium.github.io/vue-advanced-cropper/components/cropper.html#props) and instead there is "default-position".
Thanks for help it works nice now :)

**Comment by Norserium** [comment]
@alekbarszczewski it's the unstable API now, so it's poorly documented now. By the way, `default-position` and `default-size` works well, but not in your case.

**Comment by Norserium** [comment]
@alekbarszczewski in the last release `0.18.0` the recommended approach to create such croppers [was changed](https://codesandbox.io/s/vue-advanced-cropper-instagram-like-0180-1fhgk?file=/src/App.vue).

**Comment by alekbarszczewski** [comment]
Thanks, I can't try it because I upgraded Vue in my app to 3.x and vue-advanced-cropper fails to load - I am going to create separate issue for that.

**Comment by Norserium** [comment]
@alekbarszczewski I close issue. If you encounter this issue in the future, feel free to ask.
