### ISSUE TITLE
Show only cropped area?

### ISSUE THREAD

**Issue by jbonnett92** [Norserium/vue-advanced-cropper#92]
Hi,
Is it possible to show only the cropped area? No resizing controls...
So if I wanted to crop image to an aspect ratio of lets say 16/9 and the image for example was 4/3, what I would like to see is that 4/3 image filling the 16/9 area along with still being able to move the image within that area along with the ability to zoom the image within that area too. Not the current examples that are the 4/3 area with a 16/9 box to show where the crop would be. Basically the inverse.

**Comment by Norserium** [comment]
@jbonnett92 I assume that you want to get something like [that](https://codesandbox.io/s/vue-advanced-cropper-instagram-like-d3gi9?file=/src/App.vue)?

**Comment by jbonnett92** [comment]
That looks good to me 👍 
Is there a rotation handler like with the twitter zoom example?

**Comment by Norserium** [comment]
Alas, there is no possibility to rotate an image inside this cropper. I have suggested the workaround in #24 earlier.

**Comment by jbonnett92** [comment]
Thank you!

**Comment by jbonnett92** [comment]
I just realised the example breaks on window resize?

**Comment by Norserium** [comment]
@jbonnett92 could you provide the screenshot? It shouldn't.

**Comment by jbonnett92** [comment]
It may have been my edit: [example](https://codesandbox.io/s/vue-advanced-cropper-instagram-like-forked-kic9w?file=/src/App.vue)

**Comment by Norserium** [comment]
It's the bug obviously. I will try to investigate how to fix it lately, thanks.

[Temporary workaround](https://codesandbox.io/s/vue-advanced-cropper-instagram-like-142-q8k4c?file=/src/App.vue).

**Comment by Norserium** [comment]
@jbonnett92 in the last release `0.18.0` the recommended approach to create such croppers [was changed](https://codesandbox.io/s/vue-advanced-cropper-instagram-like-142-q8k4c?file=/src/App.vue).

**Comment by Norserium** [comment]
> It may have been my edit
All I did was remove the grid and change the aspect ratio and the padding bottom on the cropper container to match.

This bug is fixed in `0.18.1` now.

**Comment by Norserium** [comment]
@jbonnett92 the native rotation was added in `0.19.0`. [The rotate / flip example](https://norserium.github.io/vue-advanced-cropper/guides/advanced-recipes.html#rotate-flip-image).
