### ISSUE TITLE
Error: [Vue warn]: Error in v-on handler: "TypeError: this.$refs.cropper is undefined"

### ISSUE THREAD

**Issue by damianlluch** [Norserium/vue-advanced-cropper#94]
Hi! thanks for your job.

I try with your library (example code) in my project with Vue 2 - Typescript.

And when call to crop function, I get this error:

![image](https://user-images.githubusercontent.com/1463804/102123531-42d83d80-3e47-11eb-8eba-f42c6ff90aa2.png)

Any suggestion?

**Comment by Norserium** [comment]
@damianlluch I suggest, that you've not set the appropriate ref on the cropper:
```html
<cropper ref="cropper" />
```

**Comment by damianlluch** [comment]
thanks bro!

**Comment by Norserium** [comment]
@damianlluch you are welcome!
