### ISSUE TITLE
Question:  Cropper overlay with links ?

### ISSUE THREAD

**Issue by scramatte** [Norserium/vue-advanced-cropper#95]
Hello,

First of all thank you to made this amazing work. It's well documented and works great. It saves me  lot of time.

Can you post an example to create buttons/link  over the cropper as they achieve in IOS? 
![image](https://user-images.githubusercontent.com/188766/102194103-30005000-3ebd-11eb-91e8-1743b204b54f.png)
**IOS orignal cropper**

![image](https://user-images.githubusercontent.com/188766/102194472-a1d89980-3ebd-11eb-85e4-87aaef041e92.png)
**My APP + vue-advanced-cropper**

Moreover I'm unable to set bigger circle stencil area that cover most the screen but keeping a small margin.
Thank you for your help.

Regards

**Comment by Norserium** [comment]
@scramatte, could you provide the codesandbox for your example? The buttons above the cropper can be set by using absolute positioning. There are [similar examples](https://github.com/Norserium/vue-advanced-cropper/blob/master/example/docs/.vuepress/components/set-coordinates-example.vue) in the documentation code.

**Comment by Norserium** [comment]
> Moreover I'm unable to set bigger circle stencil area that cover most the screen but keeping a small margin.
I don't understand this problem exactly. Do you want to reduce the image size to fit to the stencil? Then use `image-restriction: none`.

**Comment by scramatte** [comment]
Hello,

following your example I've been able to set buttons over cropper.  It's work fine but do you think that is possible to place such buttons relative to the circle stencil?

![image](https://user-images.githubusercontent.com/188766/102223286-cac05500-3ee4-11eb-8f59-03f0fa5ff146.png)

```
.top-buttons {
  position: absolute;
  left: 50%;
  top: 50px;
  transform: translateX(-50%);
  width: 60%;
  display: flex;
  color: #fff;
  justify-content: center;
}

.bottom-buttons {
  position: absolute;
  left: 50%;
  bottom: 50px;
  transform: translateX(-50%);
  width: 60%;
  display: flex;
  justify-content: space-between;
}

.cropper-button {
  color: #fff;
}

```

```
<div class="bottom-buttons">
   move_and_adjust_scale
</div>

<div class="bottom-buttons">
     <f7-link class="cropper-button" @click="$refs.popup.close()">{{ $t('cancel') }}</f7-link >
     <f7-link  class="cropper-button" @click="uploadImage()">{{ $t('select') }}</f7-link >
</div> 
```

**Comment by Norserium** [comment]
> It's work fine but do you think that is possible to place such buttons relative to the circle stencil?

Why do you need it? It looks as pretty strange usecase. There are different approaches to implement it, but I suppose the most elegant way is the creating of the custom stencil component.

**Comment by Norserium** [comment]
@scramatte, any news?

**Comment by Norserium** [comment]
@scramatte  I close issue. If you encounter this issue in the future, feel free to ask.
