### ISSUE TITLE
Moving a cropped image up and down also scrolls the page

### ISSUE THREAD

**Issue by Flawe** [Norserium/vue-advanced-cropper#97]
When moving a cropped image around on a mobile device the up/down movements also scroll the page at the same time. Is there a way to stop the touchmove event (I assume this is the one causing this) to propagate past the cropper?

**Comment by Norserium** [comment]
Hello, @Flawe! It shouldn't. I've tested it on my devices. Could you provide more details? What's the used version of the library, the browser, the device?

**Comment by Norserium** [comment]
Do you encounter this problem with the examples in the documentation?

**Comment by Flawe** [comment]
Hey @Norserium,

I'm using

nuxt@2.14.7
bootstrap-vue@2.19.0
vue-advanced-cropper@0.18.0

And tested on both Chrome and DuckDuckGo on a Pixel 3 with whatever is latest Android version as of today.

I haven't tested the examples, I'll see if I can create a small repro case.

**Comment by Norserium** [comment]
@Flawe, please test the examples. It helps to understands whether it's the internal bug of the library or its depends on your code somehow.

**Comment by Norserium** [comment]
@Flawe, any news?

**Comment by Flawe** [comment]
@Norserium
Sorry, I haven't gotten to this yet. Will keep you posted once I have some more info.

**Comment by Norserium** [comment]
@Flawe, any news?

**Comment by Norserium** [comment]
@Flawe, I close the issue for now. If you encounter this trouble in the future, feel free to reopen.
