### ISSUE TITLE
[vue-advanced-cropper@next] change event not emitted during stencil drag/resize

### ISSUE THREAD

**Issue by RenchuSong** [Norserium/vue-advanced-cropper#98]
Not sure if I am doing the work correctly, but following the documentation I can make every work except no change event is emitted when I drag or resize the stencil

Here is the code change to implement croppping: https://github.com/RenchuSong/PRESS/pull/8/files?file-filters%5B%5D=.vue#diff-a58a39731588df2e03dd299875905e28577393f1135e9455a7c54a66b1f2103dR28-R48

As the code shows, @change should trigger cropImage method, which will log the change event.
However when I test the code, nothing is logged.

Am I doing something wrong here? Does vue-advanced-cropper have some edge case when used inside an ant-design form?

**Comment by RenchuSong** [comment]
Ok, I have verified the issue with barebone vue projects.
I created a vue 2 project and installed vue-advanced-cropper@release, it works and the @change event is triggered.
I created a vue 3 project and installed vue-advanced-cropper@2.0.0 and vue-advanced-cropper@next, the image can be loaded, and the slencil can be dragged and resized, but @change event is not triggered.

**Comment by RenchuSong** [comment]
Steps to reproduce:
1. Install vue/cli 4.5.9, yarn 1.22.10
2. vue create test, choose vue 3 default settings
3. cd test & yarn add vue-advanced-cropper@next
4. yarn serve
5. Copy the minimal example in https://norserium.github.io/vue-advanced-cropper/ to replace App.vue
6. Reproduce in browser

**Comment by Norserium** [comment]
@RenchuSong thank you for so detailed report and investigation. Such bug reports are even nice to receive. 

This bug is fixed in `2.0.3` now.

By the way, you can easily test the different versions in codesandboxes ([Vue 2](https://codesandbox.io/s/vue-avanced-cropper-basic-jfy5w) / [Vue 3](https://codesandbox.io/s/vue-advanced-cropper-vue-3-yrxou?file=/src/App.vue)). Sometimes it's much faster.

**Comment by RenchuSong** [comment]
@Norserium thank you so much for the fix and it works!
