### ISSUE TITLE
Twitter range slider not smooth

### ISSUE THREAD

**Issue by tre-dev** [Norserium/vue-advanced-cropper#99]
When upgrading to 1.0.1 and using the example Twitter Cropper, the ranger isn't smooth anymore and jerks around. Would be awesome if you could fix that.

https://norserium.github.io/vue-advanced-cropper/guides/showcase.html#twitter

**Comment by Norserium** [comment]
@tre-dev, nice to meet you again! Could you provide the video of its jerking? Do you encounter that effect [here](https://codesandbox.io/s/vue-advanced-cropper-twitter-suoyc?file=/src/App.vue)?

**Comment by tre-dev** [comment]
Hey! 👋 I actually edited the example you linked with 1.0.1 version as well and it jerked (jerking meaning that instead of being able to smoothly scroll with the range slider, it stops working for half a second or so). The example you linked now though is working smoothly. Did you change something?

**Comment by Norserium** [comment]
I've disabled `transitions` for the cropper. 

They are not needed in this example. I'm still testing the another approach to prevent transitions  only for zoom:
`this.$refs.cropper.zoom(0.5, null, { transitions: false })`

It look pretty good, but I'm still not sure about it.

**Comment by tre-dev** [comment]
Ah awesome, that fixed it.

**Comment by tre-dev** [comment]
I think there's another bug.

![image](https://user-images.githubusercontent.com/59442299/103790734-e5986c00-5041-11eb-8b61-56a256c8692d.png)

https://codesandbox.io/s/vue-advanced-cropper-twitter-forked-tdmcc?file=/src/App.vue

Even if I set minWidth & minHeight to 0, it gets stuck at a certain zoom level. This includes zooming with scrolling as well range slider, though with the range slider its visible that it gets stuck.

**Comment by Norserium** [comment]
It's not exactly the bug of my example, because it's designed for 1/1 aspect ratio. But it's possible to improve the code for an arbitrary aspect ratio.

[The example.](https://codesandbox.io/s/vue-advanced-cropper-twitter-improved-clnnp?file=/src/App.vue)

**Comment by tre-dev** [comment]
Sorry for responding late. That worked. Thanks!

**Comment by Norserium** [comment]
You are welcome! I close issue then.
